### ISSUE TITLE
Document the `I` state.

### ISSUE THREAD

**Issue by corvus1** [htop-dev/htop#1001]
![Screenshot_20220507_103323](https://user-images.githubusercontent.com/4068104/167242101-116189ba-9c04-4893-90a6-7871bfb21f18.png)

Not documented in help or in the man page. What does it even mean?

**Comment by BenBE** [comment]
The state `I` stands for idle, as can be found in https://github.com/htop-dev/htop/blob/79db69c48da9c4ffa514e060d893da5ec401107b/Process.c#L759-L779 (where all the other states are listed too).

**Comment by corvus1** [comment]
Okay, thanks, that clarifies things. 
It is still a bit funny that the the btrfs thread takes 14.8% of cpu, while idling, but I'm sure there's a rational explanation to that too. :-D

**Comment by BenBE** [comment]
The CPU usage is calculated over a certain time period, while the state is read just at that moment when data is collected. Also there's a subtle difference between an idle process and a sleeping one (the normal state most userland processes are in is sleeping, idle seems to be a special case for kernel threads).

**Comment by corvus1** [comment]
Okay, got it.
