### ISSUE TITLE
Default color scheme: Avoid using dark color fonts on black bg

### ISSUE THREAD

**Issue by darkblaze69** [htop-dev/htop#1013]
htop 3.2.0
Dark color fonts on black bg shouldn't be used.
e.g. Previously in <3.2 threads where green, but now they are unreadable dark blue.

![htop](https://user-images.githubusercontent.com/6976920/168428136-c70030f7-8200-441b-9326-1c1588353980.png)

**Comment by fasterit** [comment]
In the default color profile, we have:
~~~
      [PROCESS_THREAD] = ColorPair(Green, Black),
      [PROCESS_THREAD_BASENAME] = A_BOLD | ColorPair(Green, Black),
~~~

Showing custom thread names, which you have enabled in Setup (F2) -> Display Options, we chose another color to differentiate these. And that is Blue by default. Try a different color preset if that works better for you?

**Comment by eworm-de** [comment]
I would second that. The default color preset is great, except for its usage of (non-bold) blue.
Any chance to switch that to bold blue? Should be perfectly visible with light and dark background then.

**Comment by fasterit** [comment]
@BenBE Custom thread names is your turf...

**Comment by fasterit** [comment]
~~~
diff --git a/CRT.c b/CRT.c
index 868f2377..4391f7c0 100644
--- a/CRT.c
+++ b/CRT.c
@@ -156,7 +156,7 @@ static int CRT_colorSchemes[LAST_COLORSCHEME][LAST_COLORELEMENT] = {
       [PROCESS_THREAD] = ColorPair(Green, Black),
       [PROCESS_THREAD_BASENAME] = A_BOLD | ColorPair(Green, Black),
       [PROCESS_COMM] = ColorPair(Magenta, Black),
-      [PROCESS_THREAD_COMM] = ColorPair(Blue, Black),
+      [PROCESS_THREAD_COMM] = A_BOLD | ColorPair(Blue, Black),
       [BAR_BORDER] = A_BOLD,
       [BAR_SHADOW] = A_BOLD | ColorPairGrayBlack,
       [SWAP] = ColorPair(Red, Black),
~~~

This looks much better, I second @eworm-de's proposal.

**Comment by BenBE** [comment]
> @BenBE Custom thread names is your turf...

Bold (light) has not been used there, as bold is a marker for the executable basename.

**Comment by fasterit** [comment]
> > @BenBE Custom thread names is your turf...
> 
> Bold (light) has not been used there, as bold is a marker for the executable basename.

Aah, that makes sense. Shall move the basename to bold cyan or so to make it still differentiate?
The bold blue is much more readable than the plain blue so it would be nice to be able to change that.
Without breaking porcelain elsewhere...

**Comment by eworm-de** [comment]
Is there a reason not to have bold blue in network and I/O meters? That's where it bother even more.

**Comment by fasterit** [comment]
Now you get greedy, @eworm-de :-)

**Comment by BenBE** [comment]
I'm not sure I like to make everything bold … Will have to see it in action.

But given threads are green usually, marking COMM there as orange may be an alternative …

**Comment by eworm-de** [comment]
Please test #1023, give feedback and let me know if this causes any color conflicts or other issues.

**Comment by BenBE** [comment]
Okay, quick test feedback:
- The `[]` brackets around inactive tabs look strange. Also the dark-grey on blue is kinda hard to read. Would be better to have black there for the tab text).
- The digits overlapping the text at the right of meters are still dark blue, making that area hard to read (could be updated when touching this anyway)
- Can't check the ZRAM changes due to lack of having ZRAM configured.

**Comment by Explorer09** [comment]
>     * The digits overlapping the text at the right of meters are still dark blue, making that area hard to read (could be updated when touching this anyway)
> 
Is this particular point similar to what I tried to fix in #930 ? I have screenshots posted there, so check whether if it's the same issue.

**Comment by BenBE** [comment]
> > The digits overlapping the text at the right of meters are still dark blue, making that area hard to read (could be updated when touching this anyway)
> 
> Is this particular point similar to what I tried to fix in #930 ? I have screenshots posted there, so check whether if it's the same issue.

Yes. Was with that PR in mind …

**Comment by jarppiko** [comment]
I second that the new lighter blue works **much** better on black background (i.e. the default colors). I had to install my first ever `snap` to get the latest `htop` version on Ubuntu LTS.  

Big thanks for a simply awesome process monitor 🥇

**Comment by JosefLitos** [comment]
With the darkgrey instead of light (7=dark fg) it can fortunately be mitigated by using the "broken grey" theme, despite the grey being correct, only the default theme uses the wrong grey (8=light bg)

**Comment by fasterit** [comment]
Is there a PR with the change(s) left on this issue to be fully resolved?
/DLange

**Comment by BenBE** [comment]
Looking at the history of this issue I think @eworm-de may have some …

**Comment by eworm-de** [comment]
My changes were about bold blue and have been merged in 2ca75625ee5c2ac0ef1571e6918d7c94f3aa011c (& 37d30a3a7d6c96da018c960d6b6bfe11cc718aa8).

**Comment by BenBE** [comment]
If there's nothing left, I think we can close this one.

**Comment by JosefLitos** [comment]
Has the grey been fixed too? From what has been said here it seems only the blue was taken care of.

**Comment by eworm-de** [comment]
No grey, no green. Just blue.

Personally I am fine with current state.

**Comment by JosefLitos** [comment]
I mean, I really don't understand how anyone finds fine the looks that are atvertised in the readme. You can clearly see even there that the grey is just not visible at all.

**Comment by fasterit** [comment]
For that you can use the "Broken Gray" color scheme, @JosefLitos

**Comment by JosefLitos** [comment]
Yes, but that removes the grey entirely, instead of using the correct colour. Also the grey isn't broken, broken are the defaults of the colorscheme.

**Comment by fasterit** [comment]
Can you do two screenshots please:
1) Your preferred "gray"
2) The "broken gray" colorscheme
for comparison.
I am confused on what you want but have a different default color scheme (which is likely not going to happen, see above)
/DLange

**Comment by JosefLitos** [comment]
My issue comes mainly from the day variant of my colour scheme, which has very subtle secondary background (the grey that is being used for text here)
![light](https://github.com/htop-dev/htop/assets/54900518/714ca845-403a-419f-a9b6-9aafec938d39)
![dark](https://github.com/htop-dev/htop/assets/54900518/65be6341-6e99-4602-9a42-108362c9ee7b)
