### ISSUE TITLE
Mem: 16.0Z on FreeBSD

### ISSUE THREAD

**Issue by grahamperrin** [htop-dev/htop#1039]
#863 was fixed by 7039abe109956852b8fd8d04eea81a1c4581535e in `main` (tagged 3.2.1 and 3.2.0). 

With port _sysutils/htop_ 3.2.1 on FreeBSD 13.1-RELEASE: 

![2022-06-12 19-25-15](https://user-images.githubusercontent.com/192271/173986551-1a9e3b44-f12e-4a56-8b67-ae6e11718e00.png)

Screen recording (looping GIF): 

![2022-06-12 19-33 recording](https://user-images.githubusercontent.com/192271/173986631-33f99aae-9b4f-4d5a-9a70-f19e64161e04.gif)

* beginning with a run of [gitup(1)](https://www.freebsd.org/cgi/man.cgi?query=gitup&sektion=1&manpath=FreeBSD-Ports) around uptime 00:16:27
* measurements drop from 801 M (not consistent with the bar to the left) to 21.2 M (more obviously incorrect)
* around uptime 00:17:00 there's the impossible leap to 16.0 Z. 

<https://www.freshports.org/sysutils/htop/#history>

**Comment by grahamperrin** [comment]
Cross-references: 

* members-only <https://forums.freebsd.org/profile-posts/4048/> (2022-06-12, screenshot below)
* [htop is reporting quite high memory usage : freebsd](https://old.reddit.com/r/freebsd/comments/vd227g/htop_is_reporting_quite_high_memory_usage/) (2022-06-15)

![image](https://user-images.githubusercontent.com/192271/173988630-f0be3e99-e031-4546-b11e-e5ade31048dc.png)

**Comment by BenBE** [comment]
Can you comment out the following block in `freebsd/Platform.c` (lines 239-247) and check if this changes the display (probably: Yes)?

https://github.com/htop-dev/htop/blob/611ea4606f8538abf9c3db839f13c52dbc3a9605/freebsd/Platform.c#L239-L247

What are the values reported by `vnstat` compared to the values in `fpl->zfs.size` (line 243)?

More generally: is ZFS ARC reported as part of used and/or cached and/or buffers memory on FreeBSD?

**Comment by grahamperrin** [comment]
Thanks, I can't build: 

[2022-06-17 02-00 make error.txt](https://github.com/htop-dev/htop/files/8923649/2022-06-17.02-00.make.error.txt)

**Comment by grahamperrin** [comment]
> More generally: is ZFS ARC reported as part of used and/or cached and/or buffers memory on FreeBSD?

I don't know, sorry. 

I'll ask around, including an e-mail to the maintainer of _sysutils/htop_.

**Comment by grahamperrin** [comment]
> … comment out the following block in `freebsd/Platform.c` (lines 239-247) …

Thanks. This does appear to avoid the 16.0Z effect. 

First the original htop, then htop built with the changes to `freebsd/Platform.c`: 

https://user-images.githubusercontent.com/192271/174225854-9ff10721-db4b-4d85-8dfd-a048fc394de3.mp4

**Comment by grahamperrin** [comment]
> What are the values reported by `vnstat` compared to the values in `fpl->zfs.size` (line 243)?

I'm not sure how to answer that, do these screenshots help? 

![2022-06-18 08-35-36](https://user-images.githubusercontent.com/192271/174428303-f817459d-9215-4b9f-86a7-f05d7627c8e0.png)

* FreeBSD 14.0-CURRENT
* original htop (uppermost) showed `6.37` G
* htop built with the changes to `freebsd/Platform.c` showed `7.47` G
* [systat(1)](https://www.freebsd.org/cgi/man.cgi?query=systat&sektion=1&manpath=FreeBSD+14.0-current) `systat -vmstat` at top right.

Less than a minute later (08:36:16), netdata (using metrics reported by [arcstat.py](https://github.com/openzfs/zfs/blob/master/cmd/arcstat/arcstat.in) and [arc_summary.py](https://github.com/openzfs/zfs/blob/master/cmd/arc_summary/arc_summary3)) showed an actual size of `1.6` GiB for ARC:

![image](https://user-images.githubusercontent.com/192271/174428336-655b993f-b815-44b7-9d15-b7d154a1b776.png)

Later (08:54), whilst drafting this comment, `systat -zarc`: 

![image](https://user-images.githubusercontent.com/192271/174428633-08524fa4-a1f0-449d-8ec5-f24672822d58.png)

**Comment by grahamperrin** [comment]
If it helps: 

https://github.com/freebsd/freebsd-src/commit/2e52fb92ff82120099f4358b47ce51a2b62fda17

> Add a new line to top that provides a brief summary of the ZFS ARC memory usage on hosts using ZFS.  The new line displays the total amount of RAM used by the ARC along with the size of MFU, MRU, anonymous (in flight), headers, and other (miscellaneous) sub-categories.  The line is not displayed on systems that are not using ZFS.

Thanks to _Darius_ under <https://discord.com/channels/727023752348434432/757305573866733680/987654507062251530>.

**Comment by mnsanghvi** [comment]
I'm seeing the same issue on Freebsd 13.1-RELEASE-p2 running on amd64.

First, htop information:

![image](https://user-images.githubusercontent.com/1726664/189510401-484656ac-663f-4df6-a9cf-e85366a1ce1d.png)

What the htop shows:
![image](https://user-images.githubusercontent.com/1726664/189510366-a9d95a0f-1892-464a-9498-944e1153768c.png)


Output of `systat -vmstat 2`
![image](https://user-images.githubusercontent.com/1726664/189510461-0ed7a78a-1e5e-407f-b18d-92012647b5b3.png)


Here is the output of `top`
![image](https://user-images.githubusercontent.com/1726664/189510493-b11a636d-ae4b-4494-984a-70320e783824.png)



Based on comments in this issue,  #1039, it seems like I need to wait till 3.2.2 is released, yes ? 

Let me know if I can help in anyway.

**Comment by BenBE** [comment]
> Based on comments in this issue, #1039, it seems like I need to wait till 3.2.2 is released, yes ?
> 
> Let me know if I can help in anyway.

You can check if this issue is already resolved when you run the version from the `main` branch and report back if you see any issues persist.

**Comment by grahamperrin** [comment]
I have not seen the 16.0Z symptom with htop built from source from this repo.

**Comment by grahamperrin** [comment]
Please: is there any show-stopper to a release with the fix for this issue?

**Comment by er-azh** [comment]
I think I found the issue. There are 2 places where we're subtracting the ARC size from our used memory.
one is [here](https://github.com/htop-dev/htop/blob/4d40680aa04370b06e9a2acd732f0be2ee6b6eba/freebsd/FreeBSDProcessList.c#L364).
```c
   if (fpl->zfs.enabled) {
      fpl->memWire -= fpl->zfs.size;
      pl->cachedMem += fpl->zfs.size;
   }
```
and the second one as already mentioned in this issue is [here](https://github.com/htop-dev/htop/blob/4d40680aa04370b06e9a2acd732f0be2ee6b6eba/freebsd/Platform.c#L244).
```c
      if (fpl->zfs.size > fpl->zfs.min)
         shrinkableSize = fpl->zfs.size - fpl->zfs.min;
      this->values[MEMORY_METER_USED] -= shrinkableSize;
      this->values[MEMORY_METER_CACHE] += shrinkableSize;
```

The one in 
I can also crate a pull request to fix it if anyone can tell me which one should be kept.
