### ISSUE TITLE
Using F10 does not save the configuration 

### ISSUE THREAD

**Issue by 1to5pc** [htop-dev/htop#1046]
Using F10 stops the program from responding until I hit enter and if I open a new instance of htop the previous config does not load up.

**Comment by BenBE** [comment]
Which exact `htop` version? On which OS/distro?

Is the `htop` configuration in `~/.config/htop/htoprc` writable to `htop`?
What's its contents?

Does pressing <kbd>q</kbd> work?
Have you tried pressing  <kbd>alt</kbd>+<kbd>0</kbd> instead?

**Comment by 1to5pc** [comment]
Version 3.0.5 on pop OS

 # Beware! This file is rewritten by htop when settings are changed in the interface.
# The parser is also very primitive, and not human-friendly.
fields=0 48 17 18 38 39 40 2 46 47 49 1sort_key=46
sort_direction=-1
tree_sort_key=0
tree_sort_direction=1
hide_kernel_threads=1
hide_userland_threads=0
shadow_other_users=0
show_thread_names=0
show_program_path=1
highlight_base_name=0
highlight_megabytes=1
highlight_threads=1
highlight_changes=0
highlight_changes_delay_secs=5
find_comm_in_cmdline=1
strip_exe_from_cmdline=1
show_merged_command=0
tree_view=0
tree_view_always_by_pid=0
header_margin=1
detailed_cpu_time=0
cpu_count_from_one=0
show_cpu_usage=1
show_cpu_frequency=0
show_cpu_temperature=1
degree_fahrenheit=0
update_process_names=0
account_guest_in_cpu_meter=0
color_scheme=5
enable_mouse=1
delay=15is
left_meters=LeftCPUs Memory Swap
left_meter_modes=1 1 1
right_meters=RightCPUs Tasks LoadAverage Uptime
right_meter_modes=1 2 2 2
hide_function_bar=0

>Is the htop configuration in ~/.config/htop/htoprc writable to htop?
Can you explain how I can check this? I ran htop with root privileges too, but it didn't help. 

`q` works `alt` + `0` doesn't though. But still the config file does not get updated.

**Comment by fasterit** [comment]
Downloaded popos 22.04 and ran it in a VM:
<kbd>F10</kbd> is broken by `gnome-terminal` grabbing it as "the menu accelerator key".
Disable that by burger menu -> Preferences -> Global -> Disable "the menu accelerator key" option.

Saving `htoprc` works out of the box.
