### ISSUE TITLE
Values that are not configured do not match default settings (screen_tabs only?)

### ISSUE THREAD

**Issue by C0rn3j** [htop-dev/htop#1057]
```console
$ htop --version
htop 3.2.1
```
Reproduction:

```console
$ cat > ~/.config/htop/htoprc << EOF
hide_kernel_threads=1
hide_userland_threads=1
delay=4
EOF
$ htop
```
![image](https://user-images.githubusercontent.com/1641362/180523996-0bfacdbb-7a51-4b4b-be83-a8f61bbcde98.png)

htop will have no tabs

```console
$ rm .config/htop/htoprc
```

![image](https://user-images.githubusercontent.com/1641362/180524424-ea953161-8f66-4d16-b76c-613ca7c43721.png)

htop will now have tabs enabled and the config will be generated with `screen_tabs=1`, however, `screen_tabs` was not set before, and I would expect it to default to the same value that the default configuration is generated with, if not specified.

This makes it very hard to override default values without breaking future functionality and even "breaks" on updates as new functionality isn't enabled until user deletes current configuration or explicitly enables new functionality that they are unlikely to be aware about (I only noticed that tabs are a thing days ago - big thanks to the person/people who worked on implementing them!)

**Comment by smalinux** [comment]
Nowadays the default is to enable screen_tabs for new install since you delete htoprc,, htop detect that as a new installation...
You can disable tabs from setting, F2 (Setup) > Display options panel > Show tabs for screens

**Comment by smalinux** [comment]
```
$ cat > ~/.config/htop/htoprc << EOF
screen_tabs=0
hide_kernel_threads=1
EOF
$ htop
```

**Comment by C0rn3j** [comment]
Yes, I understand that.

My issue is with the conflicting behavior or default configuration versus unconfigured value.

If the default is 1, then the behavior should be 1 unless explicitly set to 0, and unset should equal default.

**Comment by BenBE** [comment]
This difference is (as mentioned) intentional for users who upgraded from a previous version of htop that did not have this setting (where it thus will be missing). Thus when there's any htoprc htop assumes it's upgrading such an older installation. If the htoprc is completely missing htop opts for the case of clean installation and activates the tab display.

**Comment by C0rn3j** [comment]
To confirm my understanding - the expected workflow on every update if one wants new features is to
* Delete ~/.config/htop/htoprc
* Start htop
* Quit htop
* Reapply your overrides

?

This is the first time I am seeing such behavior from an application, and it makes it near impossible to control htop configuration with a configuration management tool like Ansible without hardcoding every single variable, meaning user's changes will simply be overridden.

Or am I missing something and it is possible to override specific parts of htop configuration while leaving other parts intact through some other means?

**Comment by BenBE** [comment]
No. Much simpler:

1. Start the new version
2. Open the settings
3. Activate the new features if you want something different

Not all features are enabled by default (even if you start from a fresh configuration). On the contrary we try to keep existing behavior as much as possible, if having the new feature would be "unexpected". This was done for the screen tabs as having them enabled when they previously weren't might cause confusion. If instead you explicitly enable them when you want to use them, this is (IMHO) a much cleaner approach.

Maybe some background to that: Don't you hate it when programs like firefox or chrome decide that this new version is going to override your UI/UX on upgrade? At least firefox had several occasions where they decided "fuck the configuration the user had and force a new setting". And "Oh hey, we got that completely reworked fancy UI shit we drop on you and you wont be able to go back to what you're used to". At least _I_ hate when programs do that. Thus: If there's a configuration from the user, try to stick to what that they are used to and let them decide to include new features as needed. And those enabled by default after the upgrade are usually those vetted to be as non-intrusive as possible (e.g. difference highlighting is off by default as it causes quite a bit of distraction on the screen, thus if you want it, you'll have to set it up yourself anyway).

**Comment by C0rn3j** [comment]
```
Start the new version
Open the settings
Activate the new features if you want something different
```

This is only applicable if you have a single system which you do not preconfigure. 

I have many and I do use a configuration management tool, I cannot go through tens of systems manually, nor do I want to manually configure every application on a reinstall.

> Maybe some background to that: Don't you hate it when programs like firefox or chrome decide that this new version is going to override your UI/UX on upgrade?

No, I am fine with buttons moving around. 

But I understand that not everyone is, which is why I think this behavior should be configurable, and ideally off by default.

> If there's a configuration from the user, try to stick to what that they are used to 

Currently, even on a fresh install of mine I will not have tabs as my system will push `delay=4` into a newly created file, and `htop` considers this an old installation.

Can I tell it otherwise with an existing value?

Because even if my configuration is just the htop version and one variable, the behavior is broken.

```ini
htop_version=3.2.1
delay=4
```

>  If instead you explicitly enable them when you want to use them, this is (IMHO) a much cleaner approach.

I agree with not making htop look like a Christmas tree by default, but new default values should be respected, and user can change them as they wish.

**Comment by BenBE** [comment]
> Can I tell it otherwise with an existing value?

As @smalinux mentioned above, just put it there:
```
screen_tabs=1
```

`htop` ignores values it does not understand, thus old versions will ignore them when reading that config, but *will remove them* when the configuration is saved. HTH.

**Comment by C0rn3j** [comment]
Is there a list of values which behave differently when unconfigured vs what is in the default config or is `screen_tabs` the only one?

Could it be mentioned in the changelog when such behavior happens in future releases?

**Comment by BenBE** [comment]
> Is there a list of values which behave differently when unconfigured vs what is in the default config or is `screen_tabs` the only one?

As referenced above, `screen_tabs` [is currently the only value](https://github.com/htop-dev/htop/blob/f3e70ab389879db5b250bab29f14acb543bfd11f/Settings.c#L752-L756) with this behavior.

> Could it be mentioned in the changelog when such behavior happens in future releases?

We can try to remember when writing the changelog.
