### ISSUE TITLE
The field Command is missing from Available Columns when configuring Screens in htop

### ISSUE THREAD

**Issue by Ximalas** [htop-dev/htop#1075]
If you delete the field ``Command`` from Active Columns when configuring Screens, you cannot reinsert it from Available Columns.

A workaround is to edit the configuration file, adding the field ``Command`` to the appropriate ``screen:<name-of-screen>=`` line.

**Comment by BenBE** [comment]
It shouldn't usually be possible to remove that column in the first place …

**Comment by Ximalas** [comment]
You're right.

When the configuration file was converted from one version to the newest, all fields had disappeared from the Main screen. I don't recall the version numbers involved. The solution was to delete the configuration file and start anew.
