### ISSUE TITLE
Spawning many (many) processes causes htop to stop working 

### ISSUE THREAD

**Issue by dave9997** [htop-dev/htop#1077]
I was doing some testing with C code and fork(), and once I started doing some heavy tests (like spawning 2^20 processes), I noticed htop stopped reporting all active processes properly. Top continued working properly, showing all of them.
This is the code I used (don't mind it, it's for teaching purposes):
```c
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>


int main() {
    char * arg_list[] = { "ls", "-Alh", ".", NULL };

    if (fork() == 0) {              // 2nd part
        for (int i=0; i<20;i++){
            printf("fork= %d\n", fork());
            }
        execvp ("ls", arg_list); //after exec() the original program is substituted
    }                               // 2nd part

    printf ("Main program exiting...\n");

    return 0;
}

```
Can you reproduce? I'm currently running Linux 5.19 on Fedora 35.
Please also see the attached screencast.

https://user-images.githubusercontent.com/48243072/188283869-1c4193ef-929a-4dff-bf3b-c6f4fdc3484f.mov

**Comment by dave9997** [comment]
Hey everyone, I want to apologize since I just realized yesterday I must have hit F5 by accident and toggled tree view while coding frantically. I've never used that view and didn't recognize it straight away. 
This is unacceptably stupid, I'm sorry.

**Comment by BenBE** [comment]
Okay. I'll close this for now. Feel free to create a new issue if there's some other issue.
