### ISSUE TITLE
Customizable Header Layout(s)

### ISSUE THREAD

**Issue by chrishem** [htop-dev/htop#1078]
As of htop v3.2.1, it is possible to split the header layout in one of 9 different configurations (2 Col 50/50; 2C33/67; 2C67/33; {...}; 3C40/20/40; 4C25/25/25/25). Screenshot of current configuration submitted.
![image](https://user-images.githubusercontent.com/3074454/188901406-7bf2eb1e-ac2c-43d5-adcb-dd4da86ca05f.png)

Can this become a configurable option? My thought would be to allow the user to set/choose the number of columns, and then set/choose the percentages, on their own (even if there are minimum/maximums for each column). For example, if I wanted 3 columns, 40/40/20, or 3C 50/30/20, or 2 Columns 80/20.. etc etc. 

--EDIT--
I found the existing configurations inside the current code base in order to compile my own version of htop with my own header layouts.. I'm fine with only doing that, instead of making this a real feature request, but I'll leave this Issue here in case others might agree.

**Comment by fasterit** [comment]
What layout option(s) have you added?
Want to share a screenshot?

**Comment by chrishem** [comment]
I added "3 columns - 40/40/20", but I could also see having "20/40/40" or other variations too.

**Comment by fasterit** [comment]
Probably easier to add 40/40/20 and 20/40/40 than making the whole thing more user configurable. @cgzones: What's your take?

**Comment by BenBE** [comment]
IMHO best to keep it to a few selected layouts.

**Comment by chrishem** [comment]
I'm good with this answer. Thank you for the quick responses!
