### ISSUE TITLE
Suggestion: make the "Swp []" entry optional

### ISSUE THREAD

**Issue by rubyFeedback** [htop-dev/htop#1080]
On my recent computer systems I no longer use a swap file.

Thus, the display line used by htop shows an empty "Swp" line. This
is not so useful.

My suggestion here is: for those computers (or rather harddiscs) that
come without swap, omit the display of the swap line.

In other words only show it IF the user has swap and uses it.

It's not a big deal either way, I just ignore it. But it is also not really
useful on those computers that have no swap since it is essentially
a line that does not tell much much useful information.

**Comment by BenBE** [comment]
This can be configured in the settings by pressing <kbd>F2</kbd> and adjusting the meters that should be shown in the header.

Automating this is not sensible as Swap can be configured at runtime.
