### ISSUE TITLE
Column labels

### ISSUE THREAD

**Issue by OlafvdSpek** [htop-dev/htop#1082]
Setup shows `M_TRS` and `M_DRS` labels but the main display shows `CODE` and `DATA` labels. Could the `CODE` and `DATA` also be included in the setup screen, maybe before or after the text description?

**Comment by anindyasen** [comment]
Hi @OlafvdSpek 
Can you give bit more details of what needs to be done? I can work on it as part of hacktoberfest.
Thank you

**Comment by BenBE** [comment]
@anindyasen Basically there's an array with the column labels and their descriptions in the setup screen, that needs to be updated. I already prepared a patch for this issue.
