### ISSUE TITLE
Showing invalid values on startup

### ISSUE THREAD

**Issue by tomasandrle** [htop-dev/htop#1087]
In the disk & network fields there are invalid values when htop is opened. The first periodic update clears them. 

<img width="474" alt="E61F52F4-702C-4503-A206-FF742FE31F10" src="https://user-images.githubusercontent.com/42672549/190078663-82e40cbe-36d7-4b67-bd59-513b21c4acd0.png">

**Comment by eworm-de** [comment]
Are you running an old version? This has been changed in 63fafb4844dd619793ba1d318e2b06518666dd37 and initial display is: `initializing...`

**Comment by tomasandrle** [comment]
That may be it, I'm using something bundled with my linux distro; I'll check the current version, thanks.
