### ISSUE TITLE
Crash on rock pi board

### ISSUE THREAD

**Issue by ZanMax** [htop-dev/htop#1088]
Hello, I received this message when I quit Htop.

htop 2.2.2 aborting. Please report bug at http://hisham.hm/htop

 Please include in your report the following backtrace:
htop(CRT_handleSIGSEGV+0x44)[0x556a60a2b4]
linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0x7f9b5265ac]
/lib/aarch64-linux-gnu/libc.so.6(fclose+0x8)[0x7f9b2b8280]
htop(Platform_getIO_stats+0x208)[0x556a6074d8]
htop(main+0x508)[0x556a5f2f98]
/lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0xe8)[0x7f9b275e10]
htop(+0xe150)[0x556a5f3150]

Additionally, in order to make the above backtrace useful,
please also run the following command to generate a disassembly of your binary:

   objdump -d `which htop` > ~/htop.objdump

and then attach the file ~/htop.objdump to your bug report.

Thank you for helping to improve htop!

Aborted

[htop.objdump.txt](https://github.com/htop-dev/htop/files/9580100/htop.objdump.txt)

**Comment by ZanMax** [comment]
Board: ROCK PI 3A 8Gb
OS: Ubuntu 20.04.5 LTS
HDD: eMMC 128Gb and 1Tb NVMe

**Comment by natoscott** [comment]
@ZanMax hi - 2.2.2 is many years old now - could you try a more recent version of htop?

The stack trace you have reported contains functions like Platform_getIO_stats which no longer exist so it's difficult to help you based on that information.  If there is still a problem, we'd be tackling it in the current version too, so best to update first and see if the problem persists.

**Comment by ZanMax** [comment]
I checked on the latest version 3.2.1 and all works fine.
Thank you.

**Comment by natoscott** [comment]
OK, thanks for checking.
