### ISSUE TITLE
Feature sug: 8 and 16 CPU meters per line

### ISSUE THREAD

**Issue by edrozenberg** [htop-dev/htop#1091]
A feature suggestion:

Some servers have many many cores (100, 200), and with hyperthreads these numbers double.

It would be great to have additional meter options for displaying 8 and 16 CPU cores per line. Currently the max is 4 CPU cores per line. With many cores, displaying all CPU core meters pushes other htop content down, leaving little room for the process info when using a "normal" terminal window size.

For ex, with not so many cores:
<img width="961" alt="Not So Many Cores" src="https://user-images.githubusercontent.com/2648417/191056611-d4a349bd-9bb4-48d2-a9cf-46be7d8b1114.png">

**Comment by BenBE** [comment]
Recent versions of htop already provide these by going into the setup screen and using the appropriately named CPU meters.

Note however that using so many columns only makes sense on really wide screens which is why they won't get auto-detected normally.

**Comment by edrozenberg** [comment]
Thank you, I didn't realize that option was already there.

With 8 across, it works easily on slightly wide terms. 16 across does require quite a wide terminal window or tiny text to be useful. Also some core counts (for ex. 72) don't divide evenly by 16, so the layout is not great, with only the first row being full.

One sug (maybe I will file separately), is to use color-coded values in the CPUs (1-x) [Text] meters. The [Text] meters are very compact but currently all values use the same green color, making them much less useful since visually it's difficult or impossible to tell what is going on, how busy the cores are. For ex. something like 0-20% green, 20-40% yellow, 40-70% brown, 70-100% red, just a quick idea.
