### ISSUE TITLE
Building issues with RHEL 8

### ISSUE THREAD

**Issue by robinfriedrich** [htop-dev/htop#110]
I’m trying to build a working htop 2.2.0 on Red Hat Enterprise Linux 8.2 without luck.
A default configure attempt yields an executable with a dynamic lib dependency lacking:
 
/home/rfriedri/htop-2.2.0]$ ldd ./htop
      linux-vdso.so.1 (0x00007ffc5a5c5000)
      libncursesw.so.6 => /usr/lib64/libncursesw.so.6 (0x00007fd00e9fd000)
      libtinfow.so.6 => not found
      libm.so.6 => /usr/lib64/libm.so.6 (0x00007fd00e67b000)
      libc.so.6 => /usr/lib64/libc.so.6 (0x00007fd00e2b9000)
      libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007fd00e0b5000)
      libtinfo.so.6 => /usr/lib64/libtinfo.so.6 (0x00007fd00de88000)
      /lib64/ld-linux-x86-64.so.2 (0x00007fd00ec3a000)
 
To get around this I attempted to build without Unicode support:
./configure --disable-unicode
And it built cleanly.
 
/home/rfriedri/htop-2.2.0]$ ldd ./htop
      linux-vdso.so.1 (0x00007ffe82977000)
      libncurses.so.6 => /usr/lib64/libncurses.so.6 (0x00007f502f922000)
      libtinfo.so.6 => /usr/lib64/libtinfo.so.6 (0x00007f502f6f5000)
      libm.so.6 => /usr/lib64/libm.so.6 (0x00007f502f373000)
      libc.so.6 => /usr/lib64/libc.so.6 (0x00007f502efb1000)
      libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f502edad000)
      /lib64/ld-linux-x86-64.so.2 (0x00007f502fb4d000)
 
Yet when I run htop it misbehaves. Wish I could attach an image to show what is going wrong visually.

**Comment by cgzones** [comment]
Version 3.0.1 supports a command line argument `--no-unicode`, which disables Unicode support at runtime.

**Comment by robinfriedrich** [comment]
Where is this version 3.0.1?

**Comment by robinfriedrich** [comment]
No difference.  Is there something I can do to verify my nurses installation?

**Comment by BenBE** [comment]
Can you check which of the ncurses libraries other tools (like e.g. mc) are linked to?
Are they linked to the correct paths?

Can you somehow describe the misbehaviour? Crash? Wrong display of characters? Unresponsive UI?

**Comment by robinfriedrich** [comment]
The misbehavior can be seen in this screenshot.
![htop3](https://user-images.githubusercontent.com/8077791/92787600-db55b200-f36e-11ea-8f5c-ffb1665a5076.PNG)
I have checked the alsamixer app (couldn't find mc on the system) and it uses the libcursesw.so.6 while my --disable-unicode version of htop3 uses libncurses.so.6 => /usr/lib64/libncurses.so.6 instead. Doubt that's it though.
ldd /bin/alsamixer
	linux-vdso.so.1 (0x00007ffeed2ea000)
	libformw.so.6 => /usr/lib64/libformw.so.6 (0x00007f9ab88f9000)
	libmenuw.so.6 => /usr/lib64/libmenuw.so.6 (0x00007f9ab86f0000)
	libpanelw.so.6 => /usr/lib64/libpanelw.so.6 (0x00007f9ab84ec000)
	**libncursesw.so.6 => /usr/lib64/libncursesw.so.6** (0x00007f9ab82af000)
	libtinfo.so.6 => /usr/lib64/libtinfo.so.6 (0x00007f9ab8082000)

**Comment by BenBE** [comment]
Okay, given that screenshot makes things a bit clearer and makes a direct linking issue much less likely (basic ncurses API seems to work).

To avoid potential issues with bad terminfo definitions:
Which terminal are you using (TERM-variable)? Does the issue happen with other terminal emulators (lxterminal, urxvt, gnome-terminal, kernel text console) too?

**Comment by cgzones** [comment]
For me this looks like the MemoryMeter does not display the bar-meter correctly (Is this screenshot from v3.0.1 ?).
I am not sure though why.

Relevant code (MemoryMeter.c):
```
static void MemoryMeter_updateValues(Meter* this, char* buffer, int size) {
   int written;
   Platform_setMemoryValues(this);

   written = Meter_humanUnit(buffer, this->values[0], size);
   buffer += written;
   if ((size -= written) > 0) {
      *buffer++ = '/';
      size--;
      Meter_humanUnit(buffer, this->total, size);
   }
}
```

**Comment by robinfriedrich** [comment]
Thanks. I checked running my built htop on xterm and it behaved much better. My problems were with gnome-terminal which also sets $TERM to "xterm" but misbehaves. So I overrode the environment variable to xterm-256color and htop is no longer misbehaving on gnome-terminal. I guess I'm good now. Thanks for all the help. I knew it had to be something in my local config.
