### ISSUE TITLE
Only CPU bars on a high CPU machine

### ISSUE THREAD

**Issue by lucasew** [htop-dev/htop#1108]
I am having a first world problem here.

I have access to a machine with only 256 cores. The problem is that when I run HTOP on it it's only CPU bars.

I can't open the HTOP settings by pressing F2 because it doesn't appear at all.

What can I do in this situation xD

![Captura de tela_2022-10-19_19-17-59](https://user-images.githubusercontent.com/15693688/196815332-91571b3e-e6f5-47e9-8ef7-e490a4b002c6.png)

**Comment by BenBE** [comment]
Recent versions of `htop` (IIRC starting with 3.0.5) automatically detect if there are many CPU cores and default to multiple columns (up to 8) or just one overall CPU meter. To reset to the default settings you can remove `~/.config/htop/htoprc`

If you can't update you can:
1. Reduce your terminal font size
2. Hit <kbd>F2</kbd> to enter the setup screen
3. Select the Meters configuration
4. Remove the CPU meters in the left and right columns
5. Hit <kbd>F10</kbd> to save the configuration
6. Restore your terminal font size.

If you can't go that route, there's also the chance of editing the configuration file by hand (note the remarks at the top of that file). Just adjust the entries for `column_meters_N` and `column_meter_modes_N` (The space-separated items to the right of the `=` are paired: Thus if removing the X<sup>th</sup> item in `column_meters_N` be sure to also remove the X<sup>th</sup> item from `column_meter_modes_N`).

**Comment by OlafvdSpek** [comment]
> Recent versions of `htop` (IIRC starting with 3.0.5) automatically detect if there are many CPU cores and default to multiple columns (up to 8) or just one overall CPU meter.

> What's new in version 3.1.0

> * Improve default display for systems with many CPUs

**Comment by lucasew** [comment]
> > What's new in version 3.1.0
> 
> > * Improve default display for systems with many CPUs

This explains everything. The OS is Ubuntu 20.04.3.

```
$ htop --version
htop 2.2.0 - (C) 2004-2019 Hisham Muhammad
Released under the GNU GPL.
```

**Comment by lucasew** [comment]
![Captura de tela_2022-11-04_10-39-06](https://user-images.githubusercontent.com/15693688/199986266-98f04c65-5e63-4894-b30d-c6b9d975eb46.png)

Tested with the Alpine Linux HTOP using a Docker container. That's the best I can get without hiding all the cores. It hides the "each core block" and only shows the average usage by default.

The issue seems to be solved. Thank you.

**Comment by BenBE** [comment]
> Why are the '%' and some other data missing from that screenshot?

That's because on some systems the terminfo data is broken and thus dark grey is not displayed properly. There's a color scheme in the configuration to work around this.

**Comment by lucasew** [comment]
> Why are the '%' and some other data missing from that screenshot? And where did the first 128 cores go?

I forgot to show the first half of the cores. Just realized that I have to add two blocks to show all the cores.

![Captura de tela_2022-11-04_15-35-54](https://user-images.githubusercontent.com/15693688/200050525-109b47e7-15ff-4a34-b503-dc2e4ba5af7d.png)
