### ISSUE TITLE
Unable to find ncurses lib when building on Centos7.9

### ISSUE THREAD

**Issue by buer19970329** [htop-dev/htop#1119]
Hi,

when i call `./configure`, I'm getting the following error:

> checking build system type... x86_64-pc-linux-gnu
> checking host system type... x86_64-pc-linux-gnu
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether make supports the include directive... yes (GNU style)
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking dependency style of gcc... gcc3
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking minix/config.h usability... no
> checking minix/config.h presence... no
> checking for minix/config.h... no
> checking whether it is safe to define __EXTENSIONS__... yes
> checking for gcc... (cached) gcc
> checking whether we are using the GNU C compiler... (cached) yes
> checking whether gcc accepts -g... (cached) yes
> checking for gcc option to accept ISO C89... (cached) none needed
> checking whether gcc understands -c and -o together... (cached) yes
> checking dependency style of gcc... (cached) gcc3
> checking for gcc option to accept ISO C99... none needed
> checking for dirent.h that defines DIR... yes
> checking for library containing opendir... none required
> checking for ANSI C header files... (cached) yes
> checking for stdlib.h... (cached) yes
> checking for string.h... (cached) yes
> checking for strings.h... (cached) yes
> checking sys/param.h usability... yes
> checking sys/param.h presence... yes
> checking for sys/param.h... yes
> checking sys/time.h usability... yes
> checking sys/time.h presence... yes
> checking for sys/time.h... yes
> checking sys/utsname.h usability... yes
> checking sys/utsname.h presence... yes
> checking for sys/utsname.h... yes
> checking for unistd.h... (cached) yes
> checking whether sys/types.h defines makedev... yes
> checking sys/sysmacros.h usability... yes
> checking sys/sysmacros.h presence... yes
> checking for sys/sysmacros.h... yes
> checking execinfo.h usability... yes
> checking execinfo.h presence... yes
> checking for execinfo.h... yes
> checking for pid_t... yes
> checking for uid_t in sys/types.h... yes
> checking for uint8_t... yes
> checking for uint16_t... yes
> checking for uint32_t... yes
> checking for uint64_t... yes
> checking for alloc_size... yes
> checking for NaN support... yes
> checking for ceil in -lm... yes
> checking for library containing dlopen... -ldl
> checking for library containing clock_gettime... -lrt
> checking for clock_gettime... yes
> checking for dladdr... yes
> checking for faccessat... yes
> checking for fstatat... yes
> checking for host_get_clock_service... no
> checking for memfd_create... no
> checking for openat... yes
> checking for readlinkat... yes
> checking for waddwstr in -lncursesw6... no
> checking for waddwstr in -lncursesw... no
> checking for wadd_wch in -lncursesw... no
> checking for wadd_wch in -lncurses... no
> checking for addnwstr in -lncursesw6... no
> checking for addnwstr in -lncursesw... no
> checking for addnwstr in -lncurses... no
> configure: error: can not find required library libncursesw; you may want to use --disable-unicode
> 

However, I have installed all ncurses package by `yum install *ncurses*`
Please help me with that. Thanks in advance!

**Comment by BenBE** [comment]
Are you sure you have `ncurses-devel` installed?

Based on [this](https://centos.pkgs.org/7/centos-x86_64/ncurses-devel-5.9-14.20130511.el7_4.x86_64.rpm.html) the configure script should be able to pick up all the necessary files. In this case compilation should succeed with including `#include <ncurses/ncurses.h>`, which the normal code does.

Can you please provide the `configure.log` created by the configure script?

**Comment by buer19970329** [comment]
> 

T

**Comment by buer19970329** [comment]
> Are you sure you have `ncurses-devel` installed?
> 
> Based on [this](https://centos.pkgs.org/7/centos-x86_64/ncurses-devel-5.9-14.20130511.el7_4.x86_64.rpm.html) the configure script should be able to pick up all the necessary files. In this case compilation should succeed with including `#include <ncurses/ncurses.h>`, which the normal code does.
> 
> Can you please provide the `configure.log` created by the configure script?

Hi,

Thank you so much for your quick reply!
I pretty sure that I have installed `ncurses-devel`, specifically, `ncurses-devel-5.9-14.20130511.el7_4.x86_64`

Here is the `config.log`:
https://github.com/buer19970329/sdc_isc/blob/c4ead5351cc0efd47705122b8ebba46dbf81e0df/config.log

I really appreciate your help.

**Comment by BenBE** [comment]
Something is strange on your system:

```
configure:7184: checking for waddwstr in -lncursesw
configure:7211: gcc -o conftest -D_GNU_SOURCE -I/home/lxm/anaconda3/envs/mine39/include/ncursesw -I/home/lxm/anaconda3/envs/mine39/include -g -O2   conftest.c -lncursesw
         -L/home/lxm/anaconda3/envs/mine39/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/lxm/anaconda3/envs/mine39/lib -Wl,-rpath-link,/home/lxm/anaconda3/envs/mine39/lib -lncursesw -ltinfow
       -lrt -ldl -lm  >&5
/home/lxm/anaconda3/envs/mine39/bin/../lib/gcc/x86_64-conda-linux-gnu/12.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/lxm/anaconda3/envs/mine39/lib/libtinfow.so: undefined reference to `__poll_chk@GLIBC_2.16'
/home/lxm/anaconda3/envs/mine39/bin/../lib/gcc/x86_64-conda-linux-gnu/12.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/lxm/anaconda3/envs/mine39/lib/libncursesw.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
```

This block normally should be able to link `libncursesw.so`, but it throws up on linking symbols in those libraries to an old version of glibc.

But what I noticed especially is in the command line used for the compiler it's trying to link to libraries in your home directory instead of those from the system.

Please investigate, why it's adding the compiler from `/home/lxm/anaconda3/envs/mine39` (based on line 40 of the log due to your PATH env) instead of using the compiler from the system.

**Comment by buer19970329** [comment]
> 
Hi Ben,

Thank you so much for pointing that. After I added `PATH=$PATH:/usr/local/bin` to the `~/.bash_profile`, everything went well! I feel stupid :( 

Thanks again!
