### ISSUE TITLE
Quiet failure on xSnprintf failure

### ISSUE THREAD

**Issue by cgzones** [htop-dev/htop#112]
If `xSnprintf` fails, htop will exit just with a meesage: `htop: Success`
Maybe we should use `abort` or similar instead or `err(1, NULL);` ?

**Comment by BenBE** [comment]
Maybe reuse the SIGSEGV handler?

**Comment by BenBE** [comment]
This issue should be fixed by #204.

**Comment by cgzones** [comment]
Closed by #204
