### ISSUE TITLE
Field headers not updated when switching between tabs

### ISSUE THREAD

**Issue by Ximalas** [htop-dev/htop#1120]
htop is configured to let me switch between two tabs. The tabs have different composition. Switching between the tabs doesn't redraw the field headers. Hitting the # key does force a redraw. In my opinion the same should happen when hitting the tab key. This is on fairly recent FreeBSD/amd64 14.0-CURRENT. I suspect one or more changes in the September-October timeframe is the culprit. I have just updated my source tree and recompiled htop, and there's no change in behaviour.

**Comment by BenBE** [comment]
@Ximalas Thank you for reporting. Please have a look at the patch in #1121 and report back if this fixes your issue.
