### ISSUE TITLE
Disk IO units missing 'iB/s'

### ISSUE THREAD

**Issue by OlafvdSpek** [htop-dev/htop#1126]
Also, the blue on black is hard to read, at least for me.
Could the number 'fields' be padded, to stop text from moving around on each update?
I'd be nice if disk and network IO data was shown by default.

![image](https://user-images.githubusercontent.com/2218936/200170343-c4f08d1f-e86e-4505-a68c-12123070ddc8.png)

**Comment by eworm-de** [comment]
The hard-to-read color is addressed in #1023

**Comment by eworm-de** [comment]
Are the values per second or per interval?

**Comment by OlafvdSpek** [comment]
I don't know. In either case it should be described.

**Comment by eworm-de** [comment]
Prepared a pull request in #1127... Want to try it?

**Comment by OlafvdSpek** [comment]
Sure, looks good! I'd put a space between the number and the unit though.

**Comment by OlafvdSpek** [comment]
Talking about the network one.. the packet numbers are a bit confusing. Maybe they could be directly after the byte values? And are they already per second or are they per interval?

**Comment by eworm-de** [comment]
Packets are per interval... A change is waiting in #1128...

**Comment by BenBE** [comment]
Best to merge both PRs together; postponing #1128 until #1127 is ready. Both LGTM; just a minor note re error propagation (due to dropping precision in the order of operations).
