### ISSUE TITLE
Incorrect process information for sandboxed applications when "show program path" is disabled

### ISSUE THREAD

**Issue by RalfJung** [htop-dev/htop#1131]
I recently started using flatpak for some applications, and noticed that some of their processes are shown in htop in a strange way:
```
app --no-sandbox --no-zygote --lang=en-US --num-raster-threads=4 [...]
```
It displays the program/binary name as `app`. That's odd; the same process shows up as `Keybase` in `ps -A` and the KDE process manager. If I enable "show program path", htop prints
```
/app/keybase/Keybase --type=renderer --enable-crashpad --enable-crash-reporter=[...]
```
Notice that (a) now one can actually tell this is a Keybase process, and (b) the command-line arguments are different! This is for the same process ID, but somehow htop shows totally different information -- no idea which one is correct, but the `app` basename is definitely bogus.

This is with htop 3.2.1, installed from Debian packages.

**Comment by fasterit** [comment]
The arguments belong to a headless Chrome, `--no-zygote` gives that away.
@BenBE: Any idea what is happening in Ralf's case?

**Comment by RalfJung** [comment]
Yeah these are all electron applications that show this behavior. (Sorry, should have mentioned this.)

**Comment by BenBE** [comment]
Can you provide a copy of your current configuration (file)? In particular the settings for `Custom Thread Names`, `Show Program Path`, `Highlight Basename`, `Highlight Deleted/Change Fiels`, `Merge Exe/Comm in cmdline`, `Try to find Comm in Cmdline` and `Strip Exe from cmdline` are of interest here.

Can you provide a screenshot, where the additional columns `EXE` and `COMM` are visible next to the `Command` column?

I currently can't yet reproduce your issue, but found a bunch of other strange behaviours. Will need to take a closer look.

**Comment by cgzones** [comment]
Helpful would also be the original process details:
```
cat /proc/<pid>/cmdline 
cat /proc/<pid>/stat
readlink /proc/<pid>/exe
```

Is your path of the application somehow special (non-ascii characters, contains spaces, very long...)?

**Comment by RalfJung** [comment]
<details><summary>Config file</summary>

```
# Beware! This file is rewritten by htop when settings are changed in the interface.
# The parser is also very primitive, and not human-friendly.
htop_version=3.2.1
config_reader_min_version=3
fields=0 48 17 18 38 39 40 2 46 47 49 124 123 1
hide_kernel_threads=0
hide_userland_threads=1
shadow_other_users=0
show_thread_names=0
show_program_path=0
highlight_base_name=0
highlight_deleted_exe=1
highlight_megabytes=1
highlight_threads=1
highlight_changes=0
highlight_changes_delay_secs=5
find_comm_in_cmdline=1
strip_exe_from_cmdline=1
show_merged_command=0
header_margin=1
screen_tabs=0
detailed_cpu_time=0
cpu_count_from_one=1
show_cpu_usage=1
show_cpu_frequency=0
show_cpu_temperature=0
degree_fahrenheit=0
update_process_names=0
account_guest_in_cpu_meter=0
color_scheme=0
enable_mouse=1
delay=15
hide_function_bar=0
header_layout=two_50_50
column_meters_0=LeftCPUs Memory Swap
column_meter_modes_0=1 1 1
column_meters_1=RightCPUs Tasks LoadAverage Uptime
column_meter_modes_1=1 2 2 2
tree_view=1
sort_key=46
tree_sort_key=0
sort_direction=-1
tree_sort_direction=1
tree_view_always_by_pid=0
all_branches_collapsed=0
screen:Main=PID USER PRIORITY NICE M_VIRT M_RESIDENT M_SHARE STATE PERCENT_CPU PERCENT_MEM TIME EXE COMM Command
.sort_key=PERCENT_CPU
.tree_sort_key=PID
.tree_view=1
.tree_view_always_by_pid=0
.sort_direction=-1
.tree_sort_direction=1
.all_branches_collapsed=0
screen:I/O=PID USER IO_PRIORITY IO_RATE IO_READ_RATE IO_WRITE_RATE PERCENT_SWAP_DELAY PERCENT_IO_DELAY Command
.sort_key=IO_RATE
.tree_sort_key=PID
.tree_view=0
.tree_view_always_by_pid=0
.sort_direction=-1
.tree_sort_direction=1
.all_branches_collapsed=0
```

</details>

> Can you provide a screenshot, where the additional columns EXE and COMM are visible next to the Command column?

I had to search a bit to figure out how to add additional columns.^^

![image](https://user-images.githubusercontent.com/330628/202737584-409b2b75-0f91-4cb6-9857-bc6fb9d61d94.png)

> Is your path of the application somehow special (non-ascii characters, contains spaces, very long...)?

Not that I know? It's inside a sandbox though as I mentioned, i.e., in a different mount namespace that where htop runs.

> Helpful would also be the original process details:

```
$ cat /proc/668332/cmdline 
/app/keybase/Keybase --type=renderer --enable-crashpad [...]
$ cat /proc/668332/stat
668332 (Keybase) S 668245 50518 50518 0 -1 1077936128 421713 0 212 0 85226 10216 0 0 20 0 13 0 41807638 26137059328 38990 18446744073709551615 93869292149312 93869404277264 140730670228384 0 0 0 0 4098 0 0 0 0 17 7 0 0 0 0 0 93869409733312 93869410190432 93869437202432 140730670232050 140730670232612 140730670232612 140730670235625 0
$ readlink /proc/668332/exe
/app/keybase/Keybase
```

**Comment by cgzones** [comment]
Probably the cmdline contains something that breaks the parsing (could not reproduce yet):

https://github.com/htop-dev/htop/blob/2ca75625ee5c2ac0ef1571e6918d7c94f3aa011c/linux/LinuxProcessList.c#L1296-L1345

**Comment by cgzones** [comment]
@RalfJung what application are you using, I could not find a flatpak version of Keybase?
Do you experience similar name mismatches for other applications? (I tested some (including chromium) with your provided configuration, but all names did match.)

**Comment by RalfJung** [comment]
I built my own flatpak version of Keybase: https://github.com/RalfJung/io.keybase.Keybase.

But I see the same with Signal (there it says `app.asar`) and vscodium.

**Comment by cgzones** [comment]
Thanks, I can reproduce with vscodium.

The issue is */proc/\<pid\>/cmdline* not being separated by NUL bytes (`0x00`) but by a spaces (`0x20`).
So `tokenEnd` does not get set 
https://github.com/htop-dev/htop/blob/1de7a2b6e329cc7a9dde366f73d9f0854733cf4e/linux/LinuxProcessList.c#L1094
and thus `tokenStart` is set to a value way beyond the start (~480)
https://github.com/htop-dev/htop/blob/1de7a2b6e329cc7a9dde366f73d9f0854733cf4e/linux/LinuxProcessList.c#L1100-L1101

```
hexdump -C /proc/169694/cmdline
00000000  2f 61 70 70 2f 73 68 61  72 65 2f 63 6f 64 69 75  |/app/share/codiu|
00000010  6d 2f 63 6f 64 69 75 6d  20 2d 2d 74 79 70 65 3d  |m/codium --type=|
00000020  72 65 6e 64 65 72 65 72  20 2d 2d 65 6e 61 62 6c  |renderer --enabl|
00000030  65 2d 63 72 61 73 68 2d  72 65 70 6f 72 74 65 72  |e-crash-reporter|
...
```

So we could change `tokenEnd` also being set for spaces (which would regress for file paths or names containing spaces).

**Comment by BenBE** [comment]
@cgzones We could somewhat reduce that effect by only allowing spaces when no NUL bytes are found in `cmdline`. We should thoroughly test this change though as there was some related breakage when we last tinkered at that part of the code.

**Comment by RalfJung** [comment]
So, is this caused by a bug somewhere else which doesn't use null bytes as separators when it should?

**Comment by BenBE** [comment]
> So, is this caused by a bug somewhere else which doesn't use null bytes as separators when it should?

Chrome and its sandbox are notorious for messing with the cmdline by replacing all NUL characters by spaces, thus breaking the usual argument parsing and making things ambiguous to parse.

I got an idea to deal with this, but that would need to get tested thoroughly. Basically:
1. Check for any NUL characters in cmdline
2. If none found, match the start of cmdline with the executable path + space\NUL -> executable path if match, else match up to first space (yes, that's different)

**Comment by fasterit** [comment]
The plan is good, @BenBE but is is computationally very expensive.
May be we can shorten it a bit to "Scan `cmdline` from the beginning. If you encounter a blank (0x20) and have not encountered a \0 (0x00) before, check if the string so far is a valid executable. Repeat until next blank. Special case the final \0. That one is non-indicative*". In the yes-case -> Electron / Chrome headless

* Even Chrome / Electron preserve the final \0 of the `cmdline`.

**Comment by BenBE** [comment]
I see a minor issue with the proposed order @fasterit for executable names with a space in the executable name; my slightly different order would catch that case (and thus avoid the regression for that case).

The NUL scan also is not that much of an issue as we already scan the string once anyway; using `strchrnul` we could even utilize an optimized function for this scan, thus no real harm here either.

A real drawback with your "is the string a valid executable" is the quite high load this causes with the filesystem. I'd prefer if we could reserve this fallback to be rare (or completely avoided even).

I'll try to hack something up later today.

**Comment by fasterit** [comment]
> I see a minor issue with the proposed order @fasterit for executable names with a space in the executable name

Only if `/usr/local/bin/app` and `/usr/local/bin/app from electron` are both valid and the latter is running.
I would have accepted that corner case. But any better proposals very welcome.

`htop --my-system-runs-electron-apps-so-burn-cpu` might be an idea.

/DLange

**Comment by cgzones** [comment]
@RalfJung Is this actual still an issue? I re-tested with vscodium and Signal and they work fine.

Otherwise I would agree to split by spaces if no NUL character has been found. Can't we just check the last byte of cmdline for that?

**Comment by fasterit** [comment]
> Otherwise I would agree to split by spaces if no NUL character has been found. Can't we just check the last byte of cmdline for that?

(Un-)fortunately the last NUL is set even from Chrome / Electron. So it is a properly terminated "C-string", just spaces between arguments and not NULs.

**Comment by RalfJung** [comment]
> Is this actual still an issue? I re-tested with vscodium and Signal and they work fine.

I still see these strange processes. For instance
```
1429919 r           20   0 1132G  260M  147M S   0.0  0.8  0:02.21 │  │        │  └─ app.asar --no-sandbox --no-zygote --enable-blink-features=CSSPseudoDir,CSSLogical --disable-blink-features=Accelerated2dCanvas[...]
```
but when I look at that process in `/proc` I get
```
$ cat /proc/1429919/cmdline 
/app/Signal/signal-desktop --type=renderer --enable-crash-reporter=[...]
```

**Comment by BenBE** [comment]
@RalfJung Can you take a look at the patch in #1365 and see if this changes the behaviour for you? TIA.

**Comment by RalfJung** [comment]
Sorry, I won't have time to try building this from source any time soon.

> Edit: Please post the cmdline as a hexdump (e.g. hexdump -C /proc/<pid>/cmdline) to preserve the distinction between NUL and spaces.

I doubt my shell would print NULL bytes as spaces? Not sure how they'd look like though.

**Comment by RalfJung** [comment]
Yes that patch looks great. :) Even with "show program path" and "merge exe, comm, and cmdline" both disabled, it then shows the proper program name.

When I enabled "show program path", the patch also still is a small improvement: the highlighting of the program name doesn't work for the affected processes in the released version; it works with that patch.

With "merge exe, comm, and cmdline", the patch makes no difference. Things look good with and without the patch.
