### ISSUE TITLE
toggle m/p does not take effect until program restart

### ISSUE THREAD

**Issue by RalfJung** [htop-dev/htop#1135]
Steps to reproduce:
- start htop
- hit `m` which is supposed to toggle the 'merged' command display

Observed behavior:
The "command" column gains a " (merged)" after it, but nothing else changes. Only after closing and re-open htop do I actually see the merged commands.

Expected behavior:
The toggle should take effect immediately.

This is with htop 3.2.1, installed from Debian packages.

**Comment by BenBE** [comment]
This problem is already known and addressed as part of #1132.
