### ISSUE TITLE
Show Network Speeds in Kbps / Mbps instead of KBps / MBps

### ISSUE THREAD

**Issue by marcoczen** [htop-dev/htop#1187]
Guys, is there any setting that we can change to show speeds in Kbps / Mbps ?

Thanks.

**Comment by BenBE** [comment]
Currently there isn't any such setting.

**Comment by marcoczen** [comment]
Thank u @BenBE. 

Is there anything that i can edit in the code itself ? Are u one of the developers ?

**Comment by eworm-de** [comment]
To get this right... This issue is about having **bits** as the base, not **bytes**?

**Comment by marcoczen** [comment]
Is this the right file -> https://github.com/htop-dev/htop/blob/main/NetworkIOMeter.c

**Comment by BenBE** [comment]
> Is this the right file -> https://github.com/htop-dev/htop/blob/main/NetworkIOMeter.c Lines 81 , 91 ?

The file is correct, but a better approach would be just adjusting the display, which affects lines [115ff](https://github.com/htop-dev/htop/blob/main/NetworkIOMeter.c#L115-L117), [140ff](https://github.com/htop-dev/htop/blob/main/NetworkIOMeter.c#L140-L142) and [145ff](https://github.com/htop-dev/htop/blob/main/NetworkIOMeter.c#L145-L147) (If I didn't miss any right now).

> Is there anything that i can edit in the code itself ?

Have a look at the three places above. Basically would need to multiply the values passed to `Meter_humanUnit` (2nd argument) by 8 and change the unit string from `i/Bs` to `ibps`.

To have a full setting, there's also some more changes needed in [`Settings.c`](https://github.com/htop-dev/htop/blob/main/Settings.c) and [`DisplayOptionsPanel.c`](https://github.com/htop-dev/htop/blob/main/DisplayOptionsPanel.c), as can be seen in [this recent patch](https://github.com/htop-dev/htop/commit/623ee31cfe3a39c87e6066c3044c7c38ce676e6b) (The stuff in `Process.c`/`Process.h` are the actual implementation details of that feature).

> Are u one of the developers ?

Yes. You can find this [here](https://github.com/orgs/htop-dev/people).

> > To get this right... This issue is about having **bits** as the base, not **bytes**?
> 
> Ahhh ... I havent seen the code yet and i wouldnt know the teams' justification for the Bps ( instead of bps ) approach. But generally the packages we buy from the ISP shows as bps instead of Bps ( bigger numbers are better right ? ) and so when we are benchmarking ( speedtest.net ) , it will be easier to use bps instead of Bps.

Depending on where you come from, both points of view are valid. There's no hard reasoning behind the *bytes* approach vs. showing *bits*, but one aspect is consistency in the UI (all other values are in *bytes* too\*). This is common usage when denoting amounts of memory and many other common quantities of data in a computer's memory.

On the other hand, for storage media and network throughput, the SI prefixes are more commonly used. From an implementation PoV this is easy to support (just scale all values appropriately), but easily leads to confusion, as the SI notation allows for ambiguities for both `b`/`B` (bit vs byte) and the meaning of `k`/`K` (`K` can still mean 1000). This potential for ambiguity does not exist with the IEC notation used by htop. Another plus with the IEC units is a slight performance advantage (arithmetic shift vs. division), although this is negligible with modern CPUs.

\* actually using IEC units, not SI ones.

**Comment by marcoczen** [comment]
Looking at the lines suggested ....

**Comment by marcoczen** [comment]
Oops , i spoke too soon .... I tried

```
sudo find /usr  -name "*NetworkIOMeter*" 2>/dev/null
```
for me to realize that htop is already compiled and already available in binary form in my PopOS 22.04 ( based on Ubuntu 22.04 LTS ) ... So ... This is out of my league ...

**Comment by BenBE** [comment]
Given the little benefit of this feature compared to the continued maintenance cost of additional settings, this is not going to be considered for official releases.

Though if you want to support this feature for your own version of htop, you can do so by adapting the code locations outlined above.

**Comment by marcoczen** [comment]
Thank u.
