### ISSUE TITLE
hwloc on FreeBSD

### ISSUE THREAD

**Issue by grahamperrin** [htop-dev/htop#1192]
With [the port of Portable Hardware Locality (hwloc)](https://www.freshports.org/devel/hwloc2/) installed, I see 

> `  hwloc:                     no`

– when building on FreeBSD. Please, is this an issue?

[context.txt](https://github.com/htop-dev/htop/files/10762507/context.txt)

**Comment by BenBE** [comment]
You do not seem to have `--enable-hwloc` specified on your command line for `./configure`.

Please note, that using hwloc will require `hwloc.h` to be available at build time.

**Comment by grahamperrin** [comment]
Thank you. 

I was blindly following the example at <https://github.com/htop-dev/htop#user-content-compile-from-source> without realising that the command can/should be modified in this situation.

**Comment by BenBE** [comment]
Did you get it to work? If so, you may close this issue.

**Comment by grahamperrin** [comment]
Thanks, it did work, I left it open only because I saw the _enhancement_ label. 

(To be honest, I don't know what differences I might see from getting it to work.)
