### ISSUE TITLE
Occasional questionable measurement of shared memory on FreeBSD

### ISSUE THREAD

**Issue by grahamperrin** [htop-dev/htop#1193]
5th February (3.2.1 to the left, 3.3.0 to the right): 

![2023-02-05 17-11 43 8 G shared](https://user-images.githubusercontent.com/192271/219531651-edae4843-a407-4079-a311-178dfc42c171.png)

* 43.8 G

16th February: 

![2023-02-16 10-54 47 2 G shared](https://user-images.githubusercontent.com/192271/219531786-8d01098c-8b53-4d6f-8265-f754ee1e79e4.png)

* 47.2 G

When the amount of shared memory exceeds the total (15.9 G): is there a logical explanation, or is this a bug?

See also: 

* https://github.com/htop-dev/htop/issues/906
* https://github.com/htop-dev/htop/pull/913
* https://github.com/htop-dev/htop/issues/955

**Comment by grahamperrin** [comment]
If it helps: a leap may most noticeable whenever I open **Code - OSS** ([editors/vscode](https://www.freshports.org/editors/vscode/)) … I have around forty tabs with unsaved data, all of which reopen automatically. 

At the time of writing: 

![image](https://user-images.githubusercontent.com/192271/219696704-a8da2d8b-1f10-40e9-8619-91ee03c26037.png)

* 73.8 G.

**Comment by cgzones** [comment]
Maybe we should use `vmtotal.t_rmshr` (for *shared real memory*, see https://github.com/freebsd/freebsd-src/blob/de1aa3dab23c06fec962a14da3e7b4755c5880cf/sys/sys/vmmeter.h#L44) instead of
https://github.com/htop-dev/htop/blob/37eddcf5cd5129040532d5f9b965006226fdb0c1/freebsd/FreeBSDProcessList.c#L370
?

/cc @er-azh

**Comment by grahamperrin** [comment]
@bsdimp ▲ https://github.com/htop-dev/htop/issues/1193#issuecomment-1435673333 please, who amongst FreeBSD developers might help with this?

**Comment by er-azh** [comment]
Sorry for being late. Can we have someone who can reproduce test it with this patch (using rmshr instead as cgzones suggested)?

```diff
diff --git a/freebsd/FreeBSDProcessList.c b/freebsd/FreeBSDProcessList.c
index 98447df9..331aac61 100644
--- a/freebsd/FreeBSDProcessList.c
+++ b/freebsd/FreeBSDProcessList.c
@@ -367,7 +367,7 @@ static inline void FreeBSDProcessList_scanMemoryInfo(ProcessList* pl) {

    len = sizeof(vmtotal);
    sysctl(MIB_vm_vmtotal, 2, &(vmtotal), &len, NULL, 0);
-   pl->sharedMem = vmtotal.t_vmshr * pageSizeKb;
+   pl->sharedMem = vmtotal.t_rmshr * pageSizeKb;

    pl->usedMem = fpl->memActive + fpl->memWire;

```

**Comment by grahamperrin** [comment]
```text
% pwd
/usr/home/grahamperrin/dev/htop
% git pull --ff-only
Already up to date.
% git apply -v /tmp/1193.diff 
error: corrupt patch at line 13
% cat /tmp/1193.diff
diff --git a/freebsd/FreeBSDProcessList.c b/freebsd/FreeBSDProcessList.c
index 98447df9..331aac61 100644
--- a/freebsd/FreeBSDProcessList.c
+++ b/freebsd/FreeBSDProcessList.c
@@ -367,7 +367,7 @@ static inline void FreeBSDProcessList_scanMemoryInfo(ProcessList* pl) {

    len = sizeof(vmtotal);
    sysctl(MIB_vm_vmtotal, 2, &(vmtotal), &len, NULL, 0);
-   pl->sharedMem = vmtotal.t_vmshr * pageSizeKb;
+   pl->sharedMem = vmtotal.t_rmshr * pageSizeKb;

    pl->usedMem = fpl->memActive + fpl->memWire;
% 
```

**Comment by er-azh** [comment]
@grahamperrin You'll need to add a newline at the end of the file to use it with `git apply`. I did include it but it looks like you didn't copy it. Alternatively you can apply it with `patch --strip 1 < /path/to/the.patch`.

**Comment by grahamperrin** [comment]
> … I did include it but it looks like you didn't copy it. …

Hmm, interesting. I used the copy feature of GitHub: 

![image](https://user-images.githubusercontent.com/192271/227775110-59603921-0263-4516-99ac-01bd38f57e81.png)

I added a line, the patch succeeded. Results to follow.

**Comment by grahamperrin** [comment]
> … Can we have someone who can reproduce test it with this patch …

With: 

![image](https://user-images.githubusercontent.com/192271/227775412-bca49e2a-7214-4dc8-8d03-c59d431c9e60.png)

Without: 

```text
% ~/dev/htop/htop
% git reset HEAD
Unstaged changes after reset:
M       freebsd/FreeBSDProcessList.c
hint: It took 3.47 seconds to refresh the index after reset.  You can use
hint: '--no-refresh' to avoid this.
% git stash
Saved working directory and index state WIP on main: e207c8ae Improve CPU computation code
% git pull --ff-only
Already up to date.
% ./autogen.sh && ./configure --enable-hwloc && make
…
```

![image](https://user-images.githubusercontent.com/192271/227775656-83e16efe-786c-4422-83f0-8ee157a9458e.png)

**Comment by grahamperrin** [comment]
Thanks!
