### ISSUE TITLE
[Regression in 3.2.1] Wrong CPU threads are shown when running in a container

### ISSUE THREAD

**Issue by C0rn3j** [htop-dev/htop#1195]
I have a host server with 48 threads running a container using LXC 5.0.2 where I am executing htop.

This container has the following LXC config set: `limits.cpu: "16"`, meaning it gets assigned 16 random threads.

htop 3.0.5 shows the threads and their usage correctly:
![image](https://user-images.githubusercontent.com/1641362/221320992-7ef133ef-6f14-43bd-9ff1-eb9d2cb9c31e.png)

htop 3.1.0 to 3.2.0 show things correctly while showing the unused host CPU threads too:
![image](https://user-images.githubusercontent.com/1641362/221321043-83e77964-1685-42c1-bd3d-51a428523da0.png)

htop 3.2.1 to 3.2.2 however seem to show completely wrong threads by simply showing threads 1 to 16 as they go in order, irrelevant of the actual assignment. This is obvious when comparing against the previous screenshot.
![image](https://user-images.githubusercontent.com/1641362/221321095-f1164000-e71b-43ca-aa8e-ccc4e7a20635.png)

**Comment by fasterit** [comment]
Can you please provide a `cat /proc/cpuinfo` from inside the LXC container?
Probably /linux/LinuxProcessList.c:scanAvailableCPUsFromCPUinfo needs to be tinkered with a bit more to accommodate (more) LXC oddities.

**Comment by C0rn3j** [comment]
[cpuinfo.txt](https://github.com/htop-dev/htop/files/10829821/cpuinfo.txt)

**Comment by fasterit** [comment]
ok, that cpuinfo only has 16 "processors" so we need to find a way to identify which real cores are the active ones. Can you please upload a `tar -czf LXC_cpus.tar.gz /sys/devices/system/cpu/` ?

**Comment by C0rn3j** [comment]
Sure thing
[LXC_cpus.tar.gz](https://github.com/htop-dev/htop/files/10830573/LXC_cpus.tar.gz)

**Comment by fasterit** [comment]
`/sys/devices/system/cpu/online` seems useful:
4,7,12,15-16,18-19,24,26-27,32,39,42-43,45,47

Ofc, the individual /cpu*/online are all "1" despite LXC configured to not use them

**Comment by fasterit** [comment]
@C0rn3j / @BenBE*: If you add the "PROCESSOR" column to `htop` list view (Setup -> Screens -> Add "PROCESSOR" somewhere), do these go 1-16 or  4,7,12,15-16,18-19,24,26-27,32,39,42-43,45,47 as per the above list?

Trying to find out what LXC munges and what not.

*BenBE said on IRC they run LXC somewhere in production as well

**Comment by C0rn3j** [comment]
The PROCESSOR column in 3.2.2 works correctly
![image](https://user-images.githubusercontent.com/1641362/221358154-a4e76934-b0b6-48b0-8357-fae4f179d8de.png)

**Comment by BenBE** [comment]
Couldn't test myself yet, but from the screenshot this looks like the physical core id, not some logical re-ordering.

**Comment by fasterit** [comment]
Thanks @C0rn3j. So LXC sees the "true" CPU IDs from the host. Which means we should probably revert the hack from 0d53245c. Which means 2 core LXC containers on a 128 core host system, see 126 offline CPUs. Not nice but more correct.

May be as a second step we should extend the CPUMeter with an option to hide non-active CPUs?!?

**Comment by BenBE** [comment]
> May be as a second step we should extend the CPUMeter with an option to hide non-active CPUs?!?

Possibly with the extension I remarked in IRC to "remember" which notes have been seen, so systems with their full 128 cores would still see all the nodes while some go offline in idle. Otherwise this might cause quite some flicker on systems with many CPUs/nodes that have energy saving active.

**Comment by fasterit** [comment]
Please try the PR from #1197. This should revert to LXC showing all CPU meters.
