### ISSUE TITLE
Increase filter string length

### ISSUE THREAD

**Issue by gabrieljones** [htop-dev/htop#1201]
Looks like filter string is limited to 40 characters. Can it be increased to something like 255 characters?

**Comment by BenBE** [comment]
That buffer length is defined here:
https://github.com/htop-dev/htop/blob/11318b5ef6de6b2f80186a888cd5477e0ff167bb/IncSet.h#L18

It's possible to increase that size, but I don't think that makes too much sense for most use-cases, as it's often easier to just use a different string from somewhere else in the command line that's unique and much shorter to type instead.

**Comment by gabrieljones** [comment]
I tried`alpha|beta|gamma|delta`and it worked as expected. I have a rather long list like this that I was hoping to be able to use.

**Comment by BenBE** [comment]
While #1202 is a quick short-term fix, a proper fix for this issue would mean to implement a proper line editor with cursor movement, inline scrolling and dynamic allocation of the text buffer.

Also while looking at the code in `IncSet.h` I noticed that from a Defense-in-Depth PoV the `buffer` should be put at the end of the structure, or better even put outside the structure altogether (just pointed to from the structure).

**Comment by gabrieljones** [comment]
> proper line editor

Ah, didn't think of that I was using the --filter switch.

**Comment by gabrieljones** [comment]
Would it be possible to accept #1202 for now and then do the proper fix at a later date?

**Comment by BenBE** [comment]
> Would it be possible to accept #1202 for now and then do the proper fix at a later date?

If someone agrees to write that follow-up I see no objections.

**Comment by gabrieljones** [comment]
I would volunteer but Arduino programming for [Blinks](https://github.com/Move38/Thalassophobia/blob/master/Thalassophobia.ino) is the closest I get to C programming these days.

**Comment by fasterit** [comment]
We can actually make that (somewhat) longer, say 80 or 100 chars as editing such a long string is not completely breaking the screen in <kbd>F4</kbd> mode.

I wouldn't hold my breath for the proper line editor, that's quite an undertaking. We didn't want `readline` so re-implementing the good parts of it is still some work.
/DLange

**Comment by BenBE** [comment]
> We can actually make that (somewhat) longer, say 80 or 100 chars as editing such a long string is not completely breaking the screen in F4 mode.

128 is fine by me. Given that default terminal fonts on full HD give about 200 chars of width (in fullscreen), this should be a good compromise.

> I wouldn't hold my breath for the proper line editor, that's quite an undertaking. We didn't want `readline` so re-implementing the good parts of it is still some work. /DLange

No need to wait for it. Just someone feeling responsible to work on it. ;-)
