### ISSUE TITLE
one cpu full, but show 200% ?

### ISSUE THREAD

**Issue by baiwfg2** [htop-dev/htop#1204]
OS: Linux fedora 5.15.16-100.fc34.x86_64 #1 SMP , running on virtualbox with 2 CPUs
htop version : 3.2

I have a simple program:
```c
#include<stdio.h>
int globalv;
void dosth()
{
  globalv++;
}
int main()
{
  globalv = 0;
  for(;;)
    dosth();
  return 0;
}
```

When I run it, it definitely consume one core , but why htop show 200% usage ?

![image](https://user-images.githubusercontent.com/5157680/222954347-237d2a34-0cc4-4a49-9737-663f49efb9a7.png)

**Comment by fasterit** [comment]
Fedora 34 is long out of support
htop 3.2.2 on Fedora 37 does not show that behavior
Neither does git tip, so cannot reproduce

**Comment by baiwfg2** [comment]
Ok. I also verify it in kernel 4.19, it's ok.

On fedora 36, kernel 5.17.7, it shows 120% CPU usage instead of 200%, which is also not correct.

**Comment by baiwfg2** [comment]
verified fedora 37 is ok.
