### ISSUE TITLE
Htop show usage memory more than expected

### ISSUE THREAD

**Issue by EliaTolin** [htop-dev/htop#1219]
Hi, 

I use htop version 3.0.5 but i saw that it is not represented graphically correctly the used memory and free memory.

![image](https://user-images.githubusercontent.com/60351315/229785552-6068a1a0-b99f-4b92-ac1b-4aea9ed00c3b.png)

![image](https://user-images.githubusercontent.com/60351315/229785568-7ea41ccb-66cc-41b8-a0e1-c4e6e0284e12.png)

This is the result of the command of 
`free --mega`

```
               total        used        free      shared  buff/cache   available
Mem:             835         640          64          31         130          58
Swap:              0           0           0
```

The value "642M" is from 

`used_memory + buffered + cached`

For me the length of the colors is not correct in the images, in the chart missing the cache value of 130M (brown color and blue), the length of the brown bar is not represented correctly.

PS: Sorry for the quality of images, i haven't SSH.

@cagnulein

**Comment by cgzones** [comment]
I think there is nothing wrong: the 642M is the used memory, the single blue bar is for the 31M shared and the 4 yellow bars are for the 130M shared memory.

See https://github.com/htop-dev/htop/blob/3.0.5/MemoryMeter.c for details.

**Comment by grahamperrin** [comment]
> … 4 yellow bars …

I don't see these, is my eyesight bad?

**Comment by BenBE** [comment]
If there's text to be shown on a meter, the text inherits the color of what the bar would have at that place instead …
And yellow == orange …
