### ISSUE TITLE
regression: when first toggling tree view with t, it doesn't update right away and waits for a full screen refresh

### ISSUE THREAD

**Issue by russelltg** [htop-dev/htop#1225]
It seems like upon first startup, the `t` key doesn't force a refresh of the screen. Even more frustratingly, if you press it an even number of times it seems like it doesn't do anything at all because you've toggled it back, with little indication other than the default sort changing. 

I've renamed my ~/.config/htop/htoprc so it should be a fresh install, and I've tested on alacritty, gnome-terminal, and kitty and they all have the same behavior. This is on htop 3.2.2

EDIT: htop 3.2.1 works, so this must have regressed as of 3.2.2

https://user-images.githubusercontent.com/7105082/231788731-9ae6e592-b6f7-4e3b-b0b7-fd7e3a360fa4.mp4

**Comment by BenBE** [comment]
Based on your video, what you are doing is

1. Start htop
2. Hit <kbd>t</kbd> twice
3. Notice that the tree view sort order looks strange (tree lines are all over the place)

Yes, that should ideally just revert back on the second press as if nothing happened.

Regarding the other point: htop has a sort order for list view and the tree view, which happen independently. The default for the list view is CPU%, while the default for the tree view is the process's PID. The default is list view.

It seems like when activating the tree view, it's missing the sort and level building step.

**Comment by russelltg** [comment]
Not quite, let me explain a bit clearer:

Old behavior:
1. Press `t`
2. Screen immediately refreshes with tree view

New behavior:
1. Press `t`
2. Processes aren't redrawn as a tree view until the next full refresh (I believe this is by default 2 seconds)

**Comment by BenBE** [comment]
Can you have a look at `git bisect` between those two tags to see if you can find when this regression was introduced?

```bash
git clone <URL>
git bisect start
git bisect good v3.2.1
git bisect bad v3.2.2
# Build the version: ./configure && make clean && make
# Test for the regression and mark bad if present, good if not
# Repeat until git bisect shows some result
git bisect reset
```

I'll also take a look later, if I can find something.

TIA.

**Comment by BenBE** [comment]
It seems like this was introduced in d83948ed09039864cdaf6066a1bd64476211ecaa.

The fix should consist of adding some missing flags when handling the switch to the tree view. I'll take a look.

**Comment by BenBE** [comment]
Please give the following patch a quick test and report back if this resolves the issue:

```diff
$ git diff
diff --git a/Action.c b/Action.c
index a67233cc..fb0ea9b7 100644
--- a/Action.c
+++ b/Action.c
@@ -253,6 +253,10 @@ static Htop_Reaction actionToggleTreeView(State* st) {
 
    if (!ss->allBranchesCollapsed)
       ProcessList_expandTree(st->pl);
+
+   st->pl->needsSort = true;
+   ProcessList_updateDisplayList(st->pl);
+
    return HTOP_REFRESH | HTOP_SAVE_SETTINGS | HTOP_KEEP_FOLLOWING | HTOP_REDRAW_BAR | HTOP_UPDATE_PANELHDR;
 }
 
```

**Comment by eworm-de** [comment]
As discussed on irc... Setting `st->pl->needsSort = true` is sufficient.
