### ISSUE TITLE
Is it possible to hide the column name/header?

### ISSUE THREAD

**Issue by shirotech** [htop-dev/htop#1227]
Hi, thanks for providing this amazing tool, it's really useful.

Was wondering if we can hide the column name? I'm trying to have a minimal view without showing the process list, I managed that with `htop -u nobody` and tweaked a bunch of options, but only thing remaining is the green bar which shows the column names. Since I am hiding the process list, showing it does not make sense.

Here is what I have so far, goal is to also remove the green bar thing (process header)

<img width="948" alt="Screenshot 2023-04-16 at 4 45 11 pm" src="https://user-images.githubusercontent.com/1149825/232278116-d3c6cc73-3421-4b48-a2d5-e5b4f8459f23.png">

The use-case is keeping a simple dashboard within a splitted screen terminal, since there is limited height, would like to keep it short as possible not wasting any height space.

**Comment by Explorer09** [comment]
Are you aiming for hiding the entire process list or just hiding the header row of the list? The two goals are different, but your use case seems to suggest a UI for the former, not the latter.

**Comment by shirotech** [comment]
> Are you aiming for hiding the entire process list or just hiding the header row of the list? The two goals are different, but your use case seems to suggest a UI for the former, not the latter.

I am trying to hide both, the process list can be hidden with a hack, `htop -u nobody` but would be good to have a proper way so it doesn't need to do the extra work etc.

The green bar thing (header) remains, can't find a way to do it.

**Comment by BenBE** [comment]
No, that's not possible and there is likely little actual incentive to implement this.

**Comment by Explorer09** [comment]
@shirotech 

> > Are you aiming for hiding the entire process list or just hiding the header row of the list? The two goals are different, but your use case seems to suggest a UI for the former, not the latter.
> 
> I am trying to hide both, the process list can be hidden with a hack, `htop -u nobody` but would be good to have a proper way so it doesn't need to do the extra work etc.
>

Hiding the entire process list includes hiding the header row as well. Please make sure if we get your feature request right. When you said "hiding both" it has been unclear on what you really want.

**Comment by shirotech** [comment]
> No, that's not possible and there is likely little actual incentive to implement this.

Okay I hope a PR is welcome? I thought a more modular design would benefit users. i.e. everything is removable. So there's less situation where someone has to do decide if something should be there or not. Less burden on the team as well. Just my 2 cents.

**Comment by shirotech** [comment]
> Hiding the entire process list includes hiding the header row as well.

No, as you can see that is not the case in the screenshot.

**Comment by Explorer09** [comment]
@shirotech Your screenshot showed actual result, but I was asking what result did you _expect_.
 Your feature request looks like #335 .

**Comment by shirotech** [comment]
> @shirotech Your screenshot showed actual result, but I was asking what result did you _expect_.
> Your feature request looks like #335 .

Okay so I'm confused why this one is wont fix and that one is accepted as a feature request. Like I said just make it modular and there will be less inconsistency. Closing as a duplicate of #335
