### ISSUE TITLE
Empty header in configuration not understood

### ISSUE THREAD

**Issue by mizlan** [htop-dev/htop#1248]
I would like to have no header entries. Using <kbd>F2</kbd> (setup), I deleted every entry under my two columns in `Meters`, which displays live properly, and when I exit with <kbd>F10</kbd>, the following lines are set in my `~/.config/htop/htoprc`:

```
column_meters_0=
column_meter_modes_0=
column_meters_1=
column_meter_modes_1=
```

However, even though `htop` writes these lines to its configuration file, I don't believe it knows how to parse this, because when I reopen `htop`, the header is back. I think this is a bug.

**Comment by BenBE** [comment]
Cf. #1227 #168 #445 for previous discussion of this.
