### ISSUE TITLE
Rebuild of dependent objects not working

### ISSUE THREAD

**Issue by BenBE** [htop-dev/htop#126]
I had a build of htop in my local git, updated `CRT.c` and `CRT.h` to add another color attribute (cf. #125) and just ran `make` this did not rebuild all required objects, as starting the resulting binary had a somewhat broken color scheme.

To work around this the Makefile generated by configure should include [dependency information](http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/) (including dependent header files). Currently editing e.g. `CRT.h` only does not trigger a re-compile of the necessary objects.

**Comment by fasterit** [comment]
Works here.
git clone ; autogen.sh ; configure ; make
Editing CRT.c
make
results in:
$ make
make  all-am
[..]
depbase=`echo CRT.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
**gcc -DHAVE_CONFIG_H -I.  -DNDEBUG  -pedantic -Wall -Wextra -std=c99 -D_XOPEN_SOURCE_EXTENDED -DSYSCONFDIR=\"/usr/local/etc\" -I"./linux" -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -g -O2 -MT CRT.o -MD -MP -MF $depbase.Tpo -c -o CRT.o CRT.c** &&\
mv -f $depbase.Tpo $depbase.Po
gcc -pedantic -Wall -Wextra -std=c99 -D_XOPEN_SOURCE_EXTENDED -DSYSCONFDIR=\"/usr/local/etc\" -I"./linux" -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -g -O2 -rdynamic    -o htop   AvailableMetersPanel.o CategoriesPanel.o CheckItem.o ClockMeter.o ColorsPanel.o ColumnsPanel.o CPUMeter.o CRT.o MainPanel.o DisplayOptionsPanel.o FunctionBar.o Hashtable.o Header.o htop.o ListItem.o LoadAverageMeter.o MemoryMeter.o Meter.o MetersPanel.o Object.o Panel.o BatteryMeter.o Process.o ProcessList.o RichString.o ScreenManager.o Settings.o SignalsPanel.o StringUtils.o SwapMeter.o TasksMeter.o UptimeMeter.o TraceScreen.o UsersTable.o Vector.o AvailableColumnsPanel.o AffinityPanel.o HostnameMeter.o OpenFilesScreen.o Affinity.o IncSet.o Action.o EnvScreen.o InfoScreen.o XAlloc.o linux/Platform.o linux/IOPriorityPanel.o linux/LinuxProcess.o linux/LinuxProcessList.o linux/LinuxCRT.o linux/Battery.o linux/PressureStallMeter.o zfs/ZfsArcMeter.o zfs/ZfsCompressedArcMeter.o zfs/ZfsArcStats.o   -Wl,-Bsymbolic-functions -lncursesw -ltinfo -lm
[..]

Just editing a header files does not make much sense, workflow-wise. But even just editing CRT.h and re-running make works here.

**Comment by BenBE** [comment]
Just editing CRT.h can make sense, when adding some color definition (just checking declarations).

Modifying CRT.c properly recompiles here.

Will recheck the header file case with steps to reproduce later today.

**Comment by cgzones** [comment]
```
make -j
touch CRT.h
make -j
```

Re-compiles everything for me; this looks like an autotools issue on your end.

**Comment by BenBE** [comment]
Noticed, that dpkg-buildpackage reconfigures with `--disable-dependency-tracking`, thus creating makefiles without the tracking. If this is custom AM code in `configure.ac` we might discuss if we might want to drop/deprecate this switch (making it do nothing).

**Comment by fasterit** [comment]
dpkg-buildpackage (you can even use gbp buildpackage if you use the Debian packaging anyways) - like all Debian packaging tools - is meant for building once from a clean slate. So there is no need for its makefile to be able to detect manual changes in between. Hence the option.
So you seem to have just been caught in the side effects (or collateral damage) of Debian packaging tools.
I guess we can close this issue?
