### ISSUE TITLE
Settings are not saved after Ctrl+C, but they are saved after Quit is pressed

### ISSUE THREAD

**Issue by russelltg** [htop-dev/htop#1268]
Title pretty much says it all--I've found it annoying that Ctrl+C doesn't save htop settings as this is my typical way of closing htop, so often end up with losing settings that I set because I forget to close it in the other way.

Would a merge request be welcome?

https://github.com/htop-dev/htop/assets/7105082/80a76309-aa3d-4ef5-88b8-a6cfdd57ced2

**Comment by BenBE** [comment]
That's intentional behaviour. cf. #949 …

**Comment by russelltg** [comment]
I see--good to know.
