### ISSUE TITLE
How does HTOP determine IO Wait?

### ISSUE THREAD

**Issue by donateur** [htop-dev/htop#1278]
**Thanks so much for htop!  It's an amazing utility which I use daily at work.**

This is probably not a bug in htop, but are you able to let me know how I might diagnose a problem please?  My media PC at home shows high I/O Wait constantly when a containerised application runs, however there's no apparent cause.

![photoprism-iowait](https://github.com/htop-dev/htop/assets/12554885/596899f5-97f6-44b1-9d0e-cd5cdb7ca3e7)

Note that the image is sorted by DISK R/W, there's very little Disk IO at all, almost no network IO, plenty of RAM and the load average is low.  I have waited a long time to see if it would clear, but it only does when I stop the containerised application running in docker.  When I start the application again the same results occur.

* There are no processes in "D" state (I checked with `while true; do ps aux | awk '{if($8=="D") print $0;}'; sleep 0.25; done`)
* There is very little disk and network I/O going on
* I'm not able to find any OS or application logs indicating a problem.
* iotop showed nothing
* although `top` does match htop, in that it shows 25% wait (corresponding to 1 of 4 cores)

This from a fully patched Fedora 37 Linux machine which has no errors in SMART on the various storage drives.

Thank you!

**Comment by BenBE** [comment]
Hi,

With recent versions of htop (IIRC 3.2+) there's an additional I/O tab available on the main screen. That screen will provide a few more detail on the I/O wait times experienced by each process. Also with recent releases of htop there's a new meter to show the so-called Pressure Stall Information. In your case the PSI for IO are of particular interest. The PSI come in two flavours: "some" and "full". The difference is "some" provides the a measure of how much CPU time is spent with at least _some_ processes stalled on that resource, while the _full_ PSI stall means that all waiting processes are stalling on that resource.

I hope this gives a few first hints on where you can look.

NB: This stalling behaviour sometimes manifests when a container requires more resources than are granted and thus that container repeatedly tries to "swap out" its memory. This is often times not directly visible as I/O though.

**Comment by donateur** [comment]
Thank you so much for that!

I'll investigate that today.

**Comment by donateur** [comment]
> With recent versions of htop (IIRC 3.2+) there's an additional I/O tab available on the main screen. That screen will provide a few more detail on the I/O wait times experienced by each process. Also with recent releases of htop there's a new meter to show the so-called Pressure Stall Information. In your case the PSI for IO are of particular interest. The PSI come in two flavours: "some" and "full". The difference is "some" provides the a measure of how much CPU time is spent with at least _some_ processes stalled on that resource, while the _full_ PSI stall means that all waiting processes are stalling on that resource.
> 
> I hope this gives a few first hints on where you can look.
> 
> NB: This stalling behaviour sometimes manifests when a container requires more resources than are granted and thus that container repeatedly tries to "swap out" its memory. This is often times not directly visible as I/O though.

Thank you so much for this!

I have htop 3.2.2 from my distribution, so I turned on those extra meters.  Unsure how I've hidden the I/O tab, but anyway I added the only missing IO column to the main screen for now.

![htop-media](https://github.com/htop-dev/htop/assets/12554885/e2a2ad8b-2924-4f41-8bf7-f874c4d29801)

Unfortunately I'm still unable to determine much as it's just showing PSI for "some" IO.  I'll do some more reading on PSI when I have a chance, I had heard of it before but had never come across it!

I undid the only change I'd made to the application's docker-compose (reducing number of workers from 4 to 2) and downed and up'ed the containers but the problem appears unchanged.

**Comment by BenBE** [comment]
> Unsure how I've hidden the I/O tab

In the setup screen, section "Display Options" second group, top option: "Show tabs for screens". In the "Screens section" you can configure the various tabs as you need them. For the I/O tab, the default columns are: PID, USER, IO_PRIORITY, IO_RATE, IO_READ_RATE, IO_WRITE_RATE, PERCENT_SWAP_DELAY, PERCENT_IO_DELAY, Command.

**Comment by eworm-de** [comment]
I guess it is this one:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7b72d661f1f2f950ab8c12de7e2bc48bdac8ed69

**Comment by donateur** [comment]
> I guess it is this one: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7b72d661f1f2f950ab8c12de7e2bc48bdac8ed69

Thanks, but that's above my head!  It could be cosmetic.

**Comment by eworm-de** [comment]
It is cosmetic and will be fixed with a kernel update. So nothing to worry about, and nothing to fix in `htop`.

**Comment by donateur** [comment]
> It is cosmetic and will be fixed with a kernel update. So nothing to worry about, and nothing to fix in `htop`.

How are you certain of that please?

**Comment by eworm-de** [comment]
I am "suffering" the same for programs using `io_uring`. Does your application use that?

I can not be perfectly sure, but the actual time frame matches. 😜 What version of Linux are use running at the moment?

**Comment by donateur** [comment]
> I am "suffering" the same for programs using `io_uring`. Does your application use that?
I'm unsure, I only get about a half hour a day to investigate this, but hopefully the developer will let me know!

It does feel like a good match.  The system affected by this is running Fedora 37 with kernel 6.4.7-100
Do you know how to track kernel commits in to the various versions of the kernel please?

**Comment by donateur** [comment]
> I am "suffering" the same for programs using `io_uring`. Does your application use that?

Ouch, sound like using that system call isn't a good security move! See: https://en.wikipedia.org/wiki/Io_uring

**Comment by eworm-de** [comment]
The fix is backported to Linux 6.4.8, so the issue should go away once you update to that or a later version.

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.4.y

**Comment by donateur** [comment]
Just checked and a new kernel was available: 6.4.9 and the problem is resolved!  It was most likely that cosmetic issue you found.

Thank you very much @eworm-de and @BenBE !  I really appreciate it.

**Comment by eworm-de** [comment]
Now also backported to let release 6.1.45.

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.1.y
