### ISSUE TITLE
Crash when amount of CPU-cores change (i.e. toggling SMT)

### ISSUE THREAD

**Issue by jgabor** [htop-dev/htop#128]
If you are running `htop` while SMT is disabled, and then enable SMT again, `htop` crashes with an out-of-range error:

```/proc/cpuinfo contains out-of-range CPU number 8: No such file or directory```

`htop` keeps running if you start with SMT enabled and then disable it, but the amount of CPUs remain at e.g. 16 instead of dropping to 8.

Instructions (with `htop` not running):

1. disable SMT: `echo off | sudo tee /sys/devices/system/cpu/smt/control` 
2. Run `htop`
3. Enable SMT: `echo on | sudo tee /sys/devices/system/cpu/smt/control` while `htop` running

And vice-versa for the CPU-cores not updating to the lower amount when starting with SMT enabled.

**Comment by cgzones** [comment]
Could you take a look at #172 ?

(When staring with SMT disabled and then enable at runtime, the number of CPU meters does not yet get updated.)

**Comment by jgabor** [comment]
No crashing! :+1: 

* If started with SMT enabled, and then disabling during runtime, cores are marked "absent". Re-enabling removes the absent status and the cores are once again updated reguarly.
* If started with SMT disabled, then enabled during runtime, cores remain at 8 instead of going to 16. But no crash, and I'm guessing the status is updated correctly, just not visually.

I'm using the `CPUs (1&2/2)` meter, displayed as a bar, if that helps.
