### ISSUE TITLE
htop emits BEL on focus events

### ISSUE THREAD

**Issue by rpigott** [htop-dev/htop#1283]
```
$ pacman -Q htop foot ncurses
htop 3.2.2-1
foot 1.15.3-1
ncurses 6.4_20230520-1
```
As stated in the title, htop emits a terminal bell on every focus event (DECSET 1004), and I wasn't able to find a way to disable this behavior. Depending on the terminal program, the bell might cause notifications, switch focus, play a noise, etc. It can be really obnoxious and I don't see any real reason htop would ever have to emit the bell, since the information is not generally urgent and especially not for every focus event.

Please can we disable this behavior or even remove it entirely?

EDIT: add ncurses version, since it is related.

**Comment by BenBE** [comment]
There is no place in `htop` that emits a BEL intentionally.

Please check with your terminfo file if there is any issue from that side that might cause this behavior. Can you `tee` the output of `htop`, e.g. like this:

```console
htop | tee output.bin
hexdump -C output.bin | grep ' 07 '
```

For me this results in empty output from `grep`.

**Comment by rpigott** [comment]
Sure. I focus out then focus in exactly once here, hence the two BELs:

```
$ htop | tee output.bin
$ hexdump -C output.bin | grep ' 07 '
00002700  34 3b 38 32 48 07 1b 5b  31 31 3b 36 48 1b 5b 33  |4;82H..[11;6H.[3|
00002bc0  33 1b 5b 4b 1b 5b 38 34  3b 38 32 48 07 1b 5b 31  |3.[K.[84;82H..[1|
```

Seems like it is emitted between two cursor moves.

**Comment by rpigott** [comment]
Maybe this is a little clearer:

```
$ strace -e trace=write -e write=2 -v -s 8192 -o trace.txt htop
$ grep -C1 '\\7' trace.txt
write(1, "1 \33(B\33[0;1m\33[90mroot       \33[39m\33(B\33[m 20    1 \33(B\33[0;1m\33[90m  0   0 \33(B\33[0m\33[36m23\33[39m\33(B\33[m560 \33[36m14\33[39m\33(B\33[m812 \33[36m10\33[39m\33(B\33[m548 \33(B\33[0;1m\33[90mS   0.0  0.0 \33[39m\33(B\33[m 0:01.59 /usr/lib/systemd/systemd --switched-root --system --deserialize=33\33[K\33[84;82H", 266) = 266
write(1, "\7", 1)                       = 1
write(1, "\33[11;6H", 7)                = 7
--
write(1, "1 \33(B\33[0;1m\33[90mroot       \33[39m\33(B\33[m 20    1 \33(B\33[0;1m\33[90m  0   0 \33(B\33[0m\33[36m23\33[39m\33(B\33[m560 \33[36m14\33[39m\33(B\33[m812 \33[36m10\33[39m\33(B\33[m548 \33(B\33[0;1m\33[90mS   0.0  0.0 \33[39m\33(B\33[m 0:01.59 /usr/lib/systemd/systemd --switched-root --system --deserialize=33\33[K\33[84;82H", 266) = 266
write(1, "\7", 1)                       = 1
write(1, "\33[11;6H", 7)                = 7
```
The BEL character is emitted in it's own write.

**Comment by rpigott** [comment]
> There is no place in htop that emits a BEL intentionally.

Seems like there are: https://github.com/search?q=repo%3Ahtop-dev%2Fhtop%20beep&type=code

By manual inspection, it's this one:

https://github.com/htop-dev/htop/blob/076b913c7f876ba0489b9751043eeb61aa34680f/Action.c#L102-L104

Though I'd recommend you purge all `beep()`s from the codebase if you don't actually intend to beep. I can send that patch if you'd like.

**Comment by BenBE** [comment]
That code location is triggered, when you try to change the priority of a process and this operation fails. Thus the code location is somewhat intentional in that there should be some feedback if an operation failed to execute (i.e. changing the priority of some process.

I wonder why that code path is reached for the `focusOut`/`focusIn` events …

Can you fetch the reads on fd 0 too? Interleaved with those writes.

**Comment by rpigott** [comment]
That appears to be a ncurses/terminfo bug: https://codeberg.org/dnkl/foot/issues/1367

Indeed, I have:

```
$ infocmp -x | grep 1004
	XM=\E[?1006;1004;1000%?%p1%{1}%=%th%el%;, XR=\E[>0q,
```
I hadn't noticed it before, but htop is attempting to lower the priority of the selected process, but as I do not move the cursor that process is pid1/init and it fails.

It sounds like htop never intended to receive focus events at all and they are only incidentally enabled by this error in ncurses and then misinterpreted by htop.

**Comment by BenBE** [comment]
Given this is an upstream bug there's no real need to change anything.

The most I can see is handling those events, but I don't see a real need right now.

**Comment by rpigott** [comment]
Yep, that's fine. Thanks for the assistance.

I'll close this and if I can reproduce with the updated ncurses then I will re-open.
