### ISSUE TITLE
Amount of ram no longer appears

### ISSUE THREAD

**Issue by loomcaux** [htop-dev/htop#1299]
I don't know if the BUG has already been reported. Amount of ram no longer appears . See screenshot. I find the same problem in several linux distributions.

![image](https://github.com/htop-dev/htop/assets/134882811/4e9b3b71-db22-41d2-9233-7567a4f9d83d)

**Comment by BenBE** [comment]
Your terminal seems to have a broken display for dark grey. Please go to Setup and in the Colors screen select the color scheme called `Broken Grey`.
