### ISSUE TITLE
feature request: key for rescan/recalculate

### ISSUE THREAD

**Issue by UnkwUsr** [htop-dev/htop#1304]
## Problem

Sometimes I need making rescan manually, for example when seeking for random popping processes, or when I know that some process currently doing really heavy job and I want to see how it's going more closely.

Previously I was abusing the fact that pressing `P` (sort by CPU usage) was doing rescan and I also feel comfortable with sorting by CPU usage. But starting from d83948ed09039864cdaf6066a1bd64476211ecaa this key stopped making full rescan.

(To be honest, I'm not sure this feature is really need. I mean, maybe I'm just got addicted to previous behavior. Hope someone will respond and we can discuss)

## Possible solutions

1. There is already key `Ctrl-L` which does force redraw (only). I suggest to make it full recalculate instead.
2. Add new key for recalculate, separate from `Ctrl-L`

**Comment by BenBE** [comment]
You can change the refresh speed in the setup screen in the `Display Options` section by decreasing the `Update interval`.

**Comment by UnkwUsr** [comment]
Currently I have `Update interval` set to 1.5 seconds. I don't want to set this value to lower value because then it will always "shake": some processes pop ups, hides or moves around. This is annoying (for me) when it is ALWAYS behavior, but I was okay with it when it was happening only on pressing key "force rescan/recalculate"

**Comment by fasterit** [comment]
Consider doing it the other way around and press <kbd>Z</kbd> when you want to have the display paused

**Comment by fasterit** [comment]
Check out the above PR, too
