### ISSUE TITLE
bug: no colors when using a modern terminal $TERM values

### ISSUE THREAD

**Issue by aymanbagabas** [htop-dev/htop#1316]
Using modern terminals with their respective $TERM values break colors. For example, I'm using Alacritty with `$TERM=alacritty` and even though Alacritty supports 256 and 24-bit colors, Htop doesn't display any. The same case goes for KiTTY with `$TERM=kitty` and iTerm2 with `$TERM=iterm2`. The [terminfo.src](https://invisible-island.net/ncurses/terminfo.ti.html#toc-_Alacritty) database defines color support for these terminals.

**Comment by BenBE** [comment]
CNR.
![image](https://github.com/htop-dev/htop/assets/111196/9d32fdb8-95e6-4d5f-b8d4-ca4c513a2b55)

What's your config? Which OS/distro? Which versions?

**Comment by aymanbagabas** [comment]
I'm using macOS, default config, version 3.2.2.

Everything works fine if `TERM` contains `xterm` as a prefix. Kitty for instance has it's own terminfo database under `TERM=kitty` and `TERM=kitty-direct`, using those break colors. The same thing happens with other terminal values such as alacritty and iterm2. I'm using the latest terminfo database from https://invisible-island.net/datafiles/current/terminfo.src.gz

**Comment by kovidgoyal** [comment]
The correct TERM value for kitty is xterm-kitty not either kitty or kitty-direct.  And htop works fine with it. The ncurses database contains random out of date out of sync kitty databases. Please *do not* use them.
