### ISSUE TITLE
Feature request: (mostly ARM) Read CPU frequency from add/alt sysfs source

### ISSUE THREAD

**Issue by MichaIng** [htop-dev/htop#132]
Currently the CPU frequency is only read from `/proc/cpuinfo`. While this works for some devices, e.g. x86 with standard Debian kernel, on others it does not, namely:
- Raspberry Pi (all models) with official kernel
- All ARM boards I tested with Armbian 5.X kernel

Usually I read CPU frequencies from `/sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq`. I know not all devices make use of CPUfreq, but the vast majority of Linux systems does. I suggest to read CPU frequencies from the above /sys location by default, which as well safes line parsing, and use `/proc/cpuinfo` as fallback only.

Relevant code: https://github.com/htop-dev/htop/blob/459733295954ec0d5958f9a8d955d0c164876c84/linux/LinuxProcessList.c#L1120-L1164
___________
Additionally the sysfs content is clearly defined: https://www.kernel.org/doc/html/latest/admin-guide/pm/cpufreq.html#policy-interface-in-sysfs
`/proc/cpuinfo` is mentioned but its content is not defined any closer: https://www.kernel.org/doc/html/latest/filesystems/proc.html?highlight=cpuinfo#kernel-data

**Comment by fasterit** [comment]
It is `/sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq` with intel_pstate.
I think the ARM case is a seldom one (many more people use Intel/AMD CPUs), so that should not be a default case.

**Comment by MichaIng** [comment]
> It is `/sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq` with intel_pstate.

Indeed `intel_pstate` uses the same sysfs infrastructure (additionally to its own control files), other than the "cpufreq" part in the path might suggest: https://www.kernel.org/doc/html/latest/admin-guide/pm/intel_pstate.html

However `scaling_cur_freq` is the frequency that is requested by the scaling driver, regardless if it is really applied or not, while `cpuinfo_cur_freq` is (should be) the actual frequency. Those two should usually match, however if the firmware applies some turbo or thermal throttling or similar, they don't. I think it makes sense to show the actual CPU frequency instead of the one requested by the scaling driver.

Reading a bid further: https://unix.stackexchange.com/questions/87522
And: https://bugzilla.kernel.org/show_bug.cgi?id=197009
- There seem to have been a back and forth whether `/proc/cpuinfo` shows the max or current frequency on x86.
- `scaling_cur_freq` indeed seems to depend on how well it is implemented and not always matches the specification of the Linux docs. `scaling_cur_freq` seems to be more reliable, though still not exactly the actual current frequency in every case.

> I think the ARM case is a seldom one (many more people use Intel/AMD CPUs),

Likely, although I lack current statistics in numbers. However ARM might growing now that Apple switches to ARM and not sure what effect Nvidia take-over will have. Generally would be nice to use a generic/most-compatible source instead of one that seems x86-exclusive 🙂.

**Comment by cgzones** [comment]
@MichaIng can you take a look at #170

**Comment by MichaIng** [comment]
LGTM, many thanks for the quick implementation and generally the intense work on htop now :+1:. Keep in mind to take enough time for yourself to get on a sustainable level of htop development speed :).

About the jumping text when due to different frequency length:
- Generally I prefer when frequencies are positioned with same decimal orders below each others, else one might on first quick view mix up 900,0 MHz with 9000 MHz when its below 1000 MHz with 9 below 1. Ah and what about the comma character actually, probably I misunderstand the command and simply need to test a build ;).
- To avoid repositioning, instead each field (temps, clocks, usage) could get a fixed width that is just enough to hold the largest assumed possible values like 4 digits clocks, 3 digit temps and 3 digit usage. But that is likely more difficult to implement than the current float format conversion, so maybe not worth it ;).
