### ISSUE TITLE
ScreenTabsPanel_eventHandler() compiler warning

### ISSUE THREAD

**Issue by Explorer09** [htop-dev/htop#1320]
A potential null pointer dereference warning in ScreenTabsPanel_eventHandler() function.
Detected by `gcc -O2 -flto` from a CI server.
Interestingly with `-O3 -flto` this warning would be gone.

```
gcc -Wall -Wcast-align -Wcast-qual -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Wmissing-format-attribute -Wmissing-noreturn -Wmissing-prototypes -Wpointer-arith -Wshadow -Wstrict-prototypes -Wundef -Wunused -Wwrite-strings -Wnull-dereference -Werror -pedantic -std=c99 -D_XOPEN_SOURCE_EXTENDED -DSYSCONFDIR="\"/usr/local/etc\"" -I"./linux" -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -O2 -g -flto -I/usr/include/libunwind  -I/usr/include/libnl3 -I/usr/include/libnl3 -rdynamic  -O2 -g -flto -Wl,--as-needed -o htop htop.o   Action.o Affinity.o AffinityPanel.o AvailableColumnsPanel.o AvailableMetersPanel.o BatteryMeter.o CategoriesPanel.o ClockMeter.o ColorsPanel.o ColumnsPanel.o CommandLine.o CommandScreen.o Compat.o CPUMeter.o CRT.o DateMeter.o DateTimeMeter.o DiskIOMeter.o DisplayOptionsPanel.o DynamicColumn.o DynamicMeter.o DynamicScreen.o EnvScreen.o FileDescriptorMeter.o FunctionBar.o Hashtable.o Header.o HeaderOptionsPanel.o HostnameMeter.o IncSet.o InfoScreen.o ListItem.o LoadAverageMeter.o Machine.o MainPanel.o MemoryMeter.o MemorySwapMeter.o Meter.o MetersPanel.o NetworkIOMeter.o Object.o OpenFilesScreen.o OptionItem.o Panel.o Process.o ProcessLocksScreen.o ProcessTable.o Row.o RichString.o Scheduling.o ScreenManager.o ScreensPanel.o ScreenTabsPanel.o Settings.o SignalsPanel.o SwapMeter.o SysArchMeter.o Table.o TasksMeter.o TraceScreen.o UptimeMeter.o UsersTable.o Vector.o XUtils.o generic/gettime.o generic/hostname.o generic/uname.o linux/CGroupUtils.o linux/HugePageMeter.o linux/IOPriorityPanel.o linux/LibSensors.o linux/LinuxMachine.o linux/LinuxProcess.o linux/LinuxProcessTable.o linux/Platform.o linux/PressureStallMeter.o linux/SELinuxMeter.o linux/SystemdMeter.o linux/ZramMeter.o zfs/ZfsArcMeter.o zfs/ZfsCompressedArcMeter.o   -lcap -lunwind -lncursesw -ltinfo -lm   -lhwloc -lnl-3 -lnl-genl-3 -lnl-3
lto-wrapper: warning: using serial compilation of 4 LTRANS jobs
ScreenTabsPanel.c: In function ‘ScreenTabsPanel_eventHandler’:
ScreenTabsPanel.c:102:7: error: potential null pointer dereference [-Werror=null-dereference]
  102 |       ScreenNamesPanel_fill(this->names, focus->ds);
      |       ^
lto1: all warnings being treated as errors
lto-wrapper: fatal error: gcc returned 1 exit status
compilation terminated.
```
The full build log is available here: https://github.com/Explorer09/htop-1/actions/runs/6666276390/job/18117491044

This can be reproduced with a modified `.github/workflows/ci.yml` in this repository. In the job `build-ubuntu-latest-full-featured-gcc`, replace `-O3` in CFLAGS and LDFLAGS to `-O2`.

**Comment by Explorer09** [comment]
The warning is gone with the new commit? I as hesitant to propose the patch as I'm not sure if the warning is a real one or a compiler confusion (false positive). Anyway thanks for the fix.

**Comment by BenBE** [comment]
The warning was a real one (the function there could have returned NULL), even though in practice I'm certain this should never happen. Nonetheless it does not hurt to have this extra check in there.

The bigger question for me was if I could just place an `assert` there, but that didn't quite feel right either.

On the topic of "fixing bugs" there's been a rant recently by fefe, who ranted that with most projects today people only ever fix the "security issues". And I agree: A bug is a bug is a bug. Currently I'm trying to get a new Coverity build running (to check for similar issues), but their queue is more like an RNG and the "View Defects" page errors out saying they are configuring the project (for more than 6 hours).
