### ISSUE TITLE
Bug sort process - ssh server Debian.

### ISSUE THREAD

**Issue by TERMUX-GOD** [htop-dev/htop#1324]
https://github.com/htop-dev/htop/assets/150255659/34e93141-1c60-475f-83ac-26da8b5f50d4

Config htop.
[htoprc.zip](https://github.com/htop-dev/htop/files/13297007/htoprc.zip)

Connect ssh - termux.

**Comment by evrial** [comment]
I don't understand why tree mode can't be sorted
