### ISSUE TITLE
Compress cgroup for podman/libpod containers

### ISSUE THREAD

**Issue by chutzimir** [htop-dev/htop#1328]
Similar to what was done for #849 and #216, this is a request to compress cgroup names for podman containers.

Here is an example on Rocky 9

```
$ podman run --rm ubuntu sleep 100 &
[1] 1389515

$ cat /proc/$(pgrep sleep)/cgroup
0::/user.slice/user-1001.slice/user@1001.service/user.slice/libpod-6e341326175b101ba7ed53a8dd6654dd25398ece17cb61b1d151e123e7e479e1.scope/container
 
$ podman ps
CONTAINER ID  IMAGE                            COMMAND     CREATED        STATUS       PORTS   NAMES
6e341326175b  docker.io/library/ubuntu:latest  sleep 100   5 seconds ago  Up 6 seconds         elegant_hypatia

$ cat /etc/system-release
Rocky Linux release 9.2 (Blue Onyx)

$ rpm -q podman
podman-4.4.1-13.el9_2.x86_64
```

This long hash after libpod is the same as the container id printed by `podman ps`, and it can benefit from being shortened to, say 12 characters to match the output of podman ps.

**Comment by BenBE** [comment]
Can you take a look at PR #1329 and report back if this works for you?

**Comment by chutzimir** [comment]
> Can you take a look at PR #1329 and report back if this works for you?

It looks great! Thank you so much!

<img  alt="image" src="https://github.com/htop-dev/htop/assets/310867/5355c30b-2e14-4cff-a87b-0d94f81c143b">
