### ISSUE TITLE
htop 3.2.2 wrong cpu count in LXC container with cgroup limits

### ISSUE THREAD

**Issue by Napsty** [htop-dev/htop#1332]
First of all thanks for `htop`. Been using it for years and it's an enormous helper!

Today I've used `htop` the first time in a Debian 12 (Bookworm) running as a LXC container. I was surprised to see the full amount of physical cores in the htop output:

![image](https://github.com/htop-dev/htop/assets/3702203/c5670972-990d-435c-a7a2-e0cc7910a4ea)

At first I suspected a problem in LXC, that the cgroup limits don't work anymore in a Bookworm container (see https://discuss.linuxcontainers.org/t/cgroup2-cpu-limit-no-longer-working-after-lxc-container-upgraded-to-debian-12) but then realized that it might be a htop problem.

After manually compiling htop 3.2.1, I can actually confirm this. Here's the htop 3.2.1 output on the very same LXC container:

![image](https://github.com/htop-dev/htop/assets/3702203/12f0ccfb-5dd0-4e7d-8deb-a7ef8f4b92a5)

Here we get to see two CPUs in the output, which represents the cgroup limit defined on the host. 

(Available memory is correctly shown in both htop versions by the way). 

I noticed the following line in the changelog:

https://github.com/htop-dev/htop/blob/main/ChangeLog#L22C3-L22C64

> On Linux, improvements to cgroup and container identification

Maybe that's where this comes from?

**Comment by BenBE** [comment]
I think there was a change regarding CPU handling between 3.2.1 and 3.2.2 that @fasterit can shed some more light onto.

May be something related to: #993, #995, #1004, #1197, #1004 …

**Comment by Napsty** [comment]
Maybe duplicate of or at least related to https://github.com/htop-dev/htop/issues/1020

**Comment by Napsty** [comment]
Actually I'm mistaken! htop 3.2.2 compiled from source looks similar to the output of 3.2.1.
This is with htop 3.2.2 compiled from the release htop-3.2.2.tar.xz:

```
root@bookworm:~/htop-3.2.2# ./htop --version
htop 3.2.2
```

![image](https://github.com/htop-dev/htop/assets/3702203/943c32c1-982a-4789-bd00-8761487587d7)

The problem with the wrong cpu count seems to come from the htop package in the Debian repositories. There was a manual patch added in the package:

![image](https://github.com/htop-dev/htop/assets/3702203/194b3033-4e54-487c-af5a-4969f7e55cea)

The patch in question:

![image](https://github.com/htop-dev/htop/assets/3702203/4ea5b96d-fc81-43b0-b315-80d4b80c5363)

I really don't know why this patch was applied (or therefore reverted compared to this upstream code) in the deb package.

**Comment by AVSISP** [comment]
Yeah, I'm not sure what you guys did to make it show all that host info - but it's kind of ridiculous you've went back and forth on it. This IS AN HTOP ISSUE - not an LXC issue. LXC provides the correct info for HTOP to get from (/proc/cpuinfo). The developers of HTOP for some reason think it's a good idea to re-invent the wheel and use tricks to bypass already provided system information and probe deeper - which doesn't make any sense.

Version 3.2.2 UNPATCHED - WORKS CORRECTLY. So why was it changed? Why so much back and forth? Why revert something YOU ALREADY FIXED?

This is intended to be constructive criticism btw.  As a host - LXC has become completely unacceptable as a container solution for clients due to one thing and one thing only --- they can open HTOP and see all the host resources. Which they shouldn't be able to. I know LXC should really block it out better so you can't use your hacks to get to it - but you should also just use the info provided for that purpose on every single linux system on the planet in a single standard location just for you.

**Comment by fasterit** [comment]
The version you are using is just wrong differently. While it has the benefit of just showing your customers the assigned number of CPU cores, it can easily show the wrong ones. See #1195. So we chose "correct but ugly" over "nice but wrong".

We need to "probe deeper" as htop is a system analysis tool used to debug lots of error cases. Its primary purpose is far beyond showing a colorful CPU graph to people that rent LXC containers and help their hoster to hide the leaking host info.

We are happy to accept patches that replicate the LXC logic enough to be correct and nice.

**Comment by AVSISP** [comment]
> The version you are using is just wrong differently. While it has the benefit of just showing your customers the assigned number of CPU cores, it can easily show the wrong ones. See [#1195](https://github.com/htop-dev/htop/issues/1195). So we chose "correct but ugly" over "nice but wrong".
> 
> We need to "probe deeper" as htop is a system analysis tool used to debug lots of error cases. Its primary purpose is far beyond showing a colorful CPU graph to people that rent LXC containers and help their hoster to hide the leaking host info.
> 
> We are happy to accept patches that replicate the LXC logic enough to be correct and nice.

All you need to do is read from /proc/cpuinfo -> Core numbers are listed -> pull them only

That is both correct and functional at that point.

EDIT: TO CLARIFY PROCESS:
cat /sys/fs/cgroup/cpuset/cpuset.cpus
```
0-3,8-11
```
lscpu -e=CPU,CORE,SOCKET
```
CPU  CORE  SOCKET
0    0     0
1    1     0
2    2     0
3    3     0
8    0     1
9    1     1
10   2     1
11   3     1
```
grep -E 'processor|physical id|core id' /proc/cpuinfo = another option

For the above, the answer is:
Physical cores 0–3 on socket 0
Physical cores 0–3 on socket 1
