### ISSUE TITLE
Missing parts in rendering the CMDLINE

### ISSUE THREAD

**Issue by fasterit** [htop-dev/htop#1346]
bug 2/2 from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057714

Reproducer from @BenBE:
```
   const char foo[] = "test\0arg1 \\\x0a\t arg2\x0aarg3\0";
   memcpy(command, foo, sizeof(foo));
   amtRead = sizeof(foo);
```

**Comment by BenBE** [comment]
NB: That reproducer goes into `LinuxProcessTable_readCmdlineFile` after `xReadfileat` was called successfully to simulate a process with that exact `cmdline` file.
