### ISSUE TITLE
Running option is 0

### ISSUE THREAD

**Issue by FerranLlobetC** [htop-dev/htop#1369]
Hi, 
In the standard htop version that can be installed via apt in Ubuntu (2.2.0) you have the "running" counter that counts the number of threads that are active, however it is quite old and I was interested in keeping an eye on Temperatures.

Therefore, I builded it from source and it functions properly, however this "running" counter does not work anymore.

I would appreicate any light in how to makre the "running" counter to work again. Do I have to enable other libraries for it to work? Is it an option that I need to toggle on?

Best,
Ferran.

**Comment by BenBE** [comment]
A quick bisect showed this to be a regression introduced in 72235d8e098d9d79029dca65122605741e1aafad by @natoscott.
