### ISSUE TITLE
Sorting key and direction change nothing in tree mode

### ISSUE THREAD

**Issue by mexanoz** [htop-dev/htop#1378]
Processes seem to always be sorted by PID in ascending order while in tree mode.

![Screenshot_2024-01-16-225441](https://github.com/htop-dev/htop/assets/96656876/7df88aed-728b-489a-9071-9931f8460716)
![Screenshot_2024-01-16-225250](https://github.com/htop-dev/htop/assets/96656876/5c5db107-68ce-4e11-93e6-30d3815c253e)

The sorting direction is changed in the screenshots, but the order of the processes is the same. Selecting other sorting keys also changes nothing.

The issue wasn't present in 3.2.2 and appeared in 3.3.0. I've bisected it down to 0f751e991d399769fb8d7800f7c4bccec2ca7f60. However, I couldn't figure out the exact reason since it seems to be a huge commit.

**Comment by BenBE** [comment]
Thank you for bisecting the issue. Interestingly this commit (and related changes) already lead to another regression in 3.3.0.

@natoscott Do you want to take a look at this issue?
