### ISSUE TITLE
[Termux] Fatal Program Error

### ISSUE THREAD

**Issue by naonymous** [htop-dev/htop#1384]
FATAL PROGRAM ERROR DETECTED
============================
  - htop version: `3.2.2`
  - OS and kernel version: `Linux localhost 4.9.227-26302074 #1 SMP PREEMPT Tue May 16 17:54:32 +07 2023 armv8l Android`
  - steps to reproduce: just click the I/O tab menu

Error information:
------------------
A signal 31 (Bad system call) was received.

Setting information:
--------------------
htop_version=3.2.2;config_reader_min_version=3;fields=0 48 17 18 38 39 40 2 46 47 49 1;hide_kernel_threads=1;hide_userland_threads=0;hide_running_in_container=0;shadow_other_users=0;show_thread_names=0;show_program_path=1;highlight_base_name=0;highlight_deleted_exe=1;shadow_distribution_path_prefix=0;highlight_megabytes=1;highlight_threads=1;highlight_changes=0;highlight_changes_delay_secs=5;find_comm_in_cmdline=1;strip_exe_from_cmdline=1;show_merged_command=0;header_margin=1;screen_tabs=1;detailed_cpu_time=0;cpu_count_from_one=0;show_cpu_usage=1;show_cpu_frequency=0;update_process_names=0;account_guest_in_cpu_meter=0;color_scheme=0;enable_mouse=1;delay=15;hide_function_bar=0;header_layout=two_50_50;column_meters_0=LeftCPUs Memory Swap;column_meter_modes_0=1 1 1;column_meters_1=RightCPUs Tasks LoadAverage Uptime;column_meter_modes_1=1 2 2 2;tree_view=0;sort_key=46;tree_sort_key=0;sort_direction=-1;tree_sort_direction=1;tree_view_always_by_pid=0;all_branches_collapsed=0;screen:Main=PID USER PRIORITY NICE M_VIRT M_RESIDENT M_SHARE STATE PERCENT_CPU PERCENT_MEM TIME Command;.sort_key=PERCENT_CPU;.tree_sort_key=PID;.tree_view=0;.tree_view_always_by_pid=0;.sort_direction=-1;.tree_sort_direction=1;.all_branches_collapsed=0;screen:I/O=PID USER IO_PRIORITY IO_RATE IO_READ_RATE IO_WRITE_RATE Command;.sort_key=IO_RATE;.tree_sort_key=PID;.tree_view=0;.tree_view_always_by_pid=0;.sort_direction=-1;.tree_sort_direction=1;.all_branches_collapsed=0;

**Comment by BenBE** [comment]
Given this is Android … Do you by chance have an `objdump` for the `htop` executable AND a stacktrace of the crash?

**Comment by naonymous** [comment]
yes!
![2024_01_27_08.15.47.jpg](https://github.com/htop-dev/htop/assets/123049337/522f1c57-6719-4e12-8764-ec95ffe9ee65)

**Comment by BenBE** [comment]
My crystal ball is currently sent in for repair, service, and calibration. Could you please provide an object dump of the htop executable AND a stacktrace of the crash?
