### ISSUE TITLE
--mouse/--no-mouse inverted in short option

### ISSUE THREAD

**Issue by BenBE** [htop-dev/htop#139]
The `--no-mouse` option that was introduced in https://github.com/htop-dev/htop/commit/b0e24cd5a577a8eca5590683ae6aca4df61be6bb should have `-M` for its short option, instead of `-m` as it is now. Using uppercase for disable-style options is common and would also follow the `--no-unicode`/`-U` option already present.

Found while reviewing #138.

**Comment by cgzones** [comment]
Resolved with 1061bd719aa2e6762958c59bdf88aa3ee961999c
