### ISSUE TITLE
Network IO meter stops updating after some days

### ISSUE THREAD

**Issue by paulo-serrao** [htop-dev/htop#1398]
Hi!

I'm running htop 3.0.5 on Raspberry PI OS (Debian 11.7) kernel 6.1.21+

Network IO meter works fine at the beginning, displaying both RX/TX bytes and packets, but after some days (and some GB's of data transferred), the bytes info stops displaying accurate data, always staying at 0KiB/s (on both RX/TX), while packet data keeps updating properly.

The only thing I can think of is that the number of bytes gets too big and it can no longer do the math between current and previous.

my ifconfig

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.x  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 xxxx::xxxxx:xxxx:xxxx:xxxx  prefixlen 64  scopeid 0x20<link>
        ether xx:xx:xx:xx:xx:xx  txqueuelen 1000  (Ethernet)
        RX packets 82366078  bytes 43636944527 (40.6 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 86374708  bytes 47418056411 (44.1 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by BenBE** [comment]
Does this only happen after htop has been running for a few days or does this also happen if the system has been running for a few days and you start/restart htop in that situation (i.e. does restarting htop "resolve" the issue temporarily)?

**Comment by BenBE** [comment]
NP. Could have been both ways. Thus the question.

Also, did you check with the latest version of htop (3.3.0 or main branch) if this still exists there?

**Comment by paulo-serrao** [comment]
3.0.5 is the latest for my linux distro. I guess I would need to clone and compile myself...

**Comment by paulo-serrao** [comment]
I compiled 3.3.0 and that version works fine. I guess this has already been detected and fixed :)

Thanks @BenBE for the suggestion
