### ISSUE TITLE
[Documentation] Small update (sorry for nit-picking here)

### ISSUE THREAD

**Issue by rubyFeedback** [htop-dev/htop#140]
Hello folks,

First, it is great that htop is now more active. I hope momentum can be re-gained/maintained in this regard.

Now to this tiny issue:

The main README states:

"htop was invented, developed and maintained by Hisham Muhammad from 2006 to 2019. His legacy repository has been archived to preserve the history."

When I read 2006 this confused me, because if my memory was correct, I was already using GoboLinux in 2005, and I always associated Hisham with htop, since that was available. So I checked wikipedia and wikipedia states that htop was created in 2004 (I did not edit/modify that wikipedia page). So that matches my own memory in this regard. I think 2006 should simply be replaced with 2004.

Hope that issue is ok to report, since it is so minor - but simple to change too. I just wanted for attribution to be correct; Hisham being busy has been seen in GoboLinux too, for instance.

**Comment by natoscott** [comment]
Hmm - where does it state that exactly?  I can't see that in the README of this repo.  You're right though - the git history goes back to 2006, but several source files contain 2004 copyright annotations.

**Comment by fasterit** [comment]
git pull @natoscott :-)
And I'll fix to 2004, I got the 2006 from the git log but I'm fine to believe Wikipedia. What could ever be wrong on there? :-)
