### ISSUE TITLE
add a new column as output of "pwdx <pid>"  to get information about the directory from which command was executed.

### ISSUE THREAD

**Issue by patilabhay679** [htop-dev/htop#1402]
HTOP doesn't have built-in support for running commands like pwdx directly within its interface. 
e.g. ~/test1/app.py  vs ~/test2/app.py
htop won't show which app.py it is referencing to.

please add this column would be great help.

**Comment by BenBE** [comment]
You are looking for the `CWD` (current working directory) column …
