### ISSUE TITLE
Wrong memory info in Linux

### ISSUE THREAD

**Issue by neochine** [htop-dev/htop#1406]
In my VPS,
```
Linux 5.19.0-42-generic #43~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 21 16:51:08 UTC 2 x86_64 GNU/Linux
```
htop result is : (htop 3.0.5)
![image](https://github.com/htop-dev/htop/assets/150173528/ccb75b66-2a68-4307-81d6-0499b15db50b)

It shows full and 16.0Z but it should be showing 3.56GB. psutil shows correct
```
>>> import psutil
>>> psutil.virtual_memory().used/(1024*1024*1024)
3.5608177185058594
>>> psutil.virtual_memory().available/(1024*1024*1024)
1.0938796997070312
>>> psutil.virtual_memory().total/(1024*1024*1024)
4.656612396240234
>>>
```

**Comment by BenBE** [comment]
Which version/release of htop is this?

**Comment by fasterit** [comment]
customer says 3.0.5 above the screenshot

**Comment by fasterit** [comment]
cf. #863

**Comment by neochine** [comment]
![image](https://github.com/htop-dev/htop/assets/150173528/3d6be998-30cd-4c69-893f-baf80621700c)
Compiling latest htop right now from source code fixes it. Though its displaying CPUs weirdly. Either way I guess I will wait till updated htop is available through apt
