### ISSUE TITLE
HTOPRC handling too aggressive?

### ISSUE THREAD

**Issue by ossimoi** [htop-dev/htop#1426]
Wanted to run htop with default settings. `HTOPRC=/dev/null htop` as root was a bad idea since htop replaced /dev/null char device with default config. This obviously caused problems. Should there be an extra check to not touch the file if it exists but does not contain actual config?

**Comment by BenBE** [comment]
At least things should not be touched, if the original file is not a regular file (or symlink).

**Comment by Explorer09** [comment]
Surely is was a bad idea. But keep in mind the root user is already able to break the system with `HTOPRC=/etc/passwd htop` (/etc/passwd is surely a regular file).

We've handled the symlinks already in #1412. Maybe we can add exception that any file type that's not regular file should not be touched. This would skip not just device files but also directories, FIFOs, and sockets.
