### ISSUE TITLE
not showing accurate memory usage (MacOS Ventura)

### ISSUE THREAD

**Issue by k2662** [htop-dev/htop#1477]
it shows 7gb when its actually 9gb of ram use.

**Comment by BenBE** [comment]
Please provide full memory statistics alongside the values shown in htop.
We are programmers, not fortune tellers …

**Comment by k2662** [comment]
> Please provide full memory statistics alongside the values shown in htop. We are programmers, not fortune tellers …


![image](https://github.com/htop-dev/htop/assets/120774884/9f209950-ee4e-44a1-bd4a-89b038566481)

![image](https://github.com/htop-dev/htop/assets/120774884/9f41513d-d628-4717-a3d9-1c0c331c96d7)

**Comment by Explorer09** [comment]
We have pull request #1439 awaiting for review. Would you guys help test out the new memory counting algorithm to see if the bug exists?
It seems like these are related.
