### ISSUE TITLE
HTOP "free mem" value differs from value reported by TOP and FREE

### ISSUE THREAD

**Issue by CloisteredNeuron** [htop-dev/htop#1487]
I've found there is a disconnect between Mem (720) reported by HTOP and used (935.5) reported by TOP.  Also, I've found used Mem is (935) in FREE which matches TOP.  The odd app out is HTOP.  I'm running these apps on Debian Stable 12.5 (bookworm) with plasma-desktop. 

Is HTOP designed to not to match these fields in TOP and FREE?

If HTOP by design does not match these fields is there a way to configure HTOP to display the "free mem" value displayed by TOP/FREE?

If this is by design what does Mem in HTOP mean vs the "free mem" value displayed by TOP/FREE?

Thanks!

HTOP
    0[|||                                                                      3.0%] Tasks: 51, 86 thr, 62 kthr; 1 running
    1[||||                                                                     2.9%] Load average: 0.06 0.07 0.02 
  **Mem**[|||||||||||||||||||||||||||||                                      **720M**/3.82G] Uptime: 03:17:19
  Swp[                                                                      0K/975M]

TOP
top - 22:49:53 up  3:09,  1 user,  load average: 0.10, 0.09, 0.02
Tasks: 112 total,   1 running, 111 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st 
MiB Mem :   3915.3 total,   2571.7 free,    **935.5 used**,    656.7 buff/cache     
MiB Swap:    975.0 total,    975.0 free,      0.0 used.   2979.8 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                            
   2213 cloy      20   0  585060 143348 118372 S   0.0   3.6   0:03.70 konsole

FREE

$ free -ght
               total        **used**        free      shared  buff/cache   available
Mem:           3.8Gi       **935Mi**       2.5Gi        29Mi       656Mi       2.9Gi
Swap:          974Mi          0B       974Mi
Total:         4.8Gi       935Mi       3.5Gi

**Comment by CloisteredNeuron** [comment]
Hi BenBE,

Do you know the issue # that this one duplicates so I can track it there?  Thanks!

**Comment by BenBE** [comment]
Have a look at #281, #821, #838, #1307, et. al.

**Comment by CloisteredNeuron** [comment]
Thank you BenBE!
