### ISSUE TITLE
Distinguish in which disk IO is high

### ISSUE THREAD

**Issue by ChillarAnand** [htop-dev/htop#1497]
When servers have multiple disks, in addition to showing disk %, it should also show individual disk IOs.

For example atop shows individual lines for each disk which is quite help in pin pointing the disk at a glance.

<img width="1280" alt="Screenshot 2024-07-15 at 10 31 37" src="https://github.com/user-attachments/assets/defe49fe-02c7-45e7-a26f-376b94cd2cda">

**Comment by BenBE** [comment]
Have a look at #952 …

**Comment by ChillarAnand** [comment]
Closing this.

Follow up at https://github.com/htop-dev/htop/issues/952
