### ISSUE TITLE
CPU meter is named Avg

### ISSUE THREAD

**Issue by OlafvdSpek** [htop-dev/htop#1502]
"Avg" isn't very descriptive, shouldn't it be named CPU?

![image](https://github.com/user-attachments/assets/c2b05b23-65e7-44d7-89f6-49e967c05ac9)

**Comment by fasterit** [comment]
It is the Average (Avg) of your CPU usage, hence that's why it is named like this. The individual bars are CPU 0 or 1 ... N

**Comment by OlafvdSpek** [comment]
I know it's the average of the CPU usage, but that's not clear from the name is it? It could quite well be the average of something else.

**Comment by fasterit** [comment]
It has been like this > 10 years and seems to not confuse users. Space in TUI applications is usually quite limited so their authors have to make compromises.
I am closing this issue as it has been labeled "won't fix" already a week ago by a fellow developer. I.e. we will keep the label as is.

**Comment by OlafvdSpek** [comment]
> It has been like this > 10 years and seems to not confuse users.

The meter wasn't enabled by default until recently was it?

**Comment by BenBE** [comment]
> > It has been like this > 10 years and seems to not confuse users.
> 
> The meter wasn't enabled by default until recently was it?

I'd be hard-pressed to ask a paleontologist to find any version where it wasn't enabled …

**Comment by OlafvdSpek** [comment]
![image](https://github.com/user-attachments/assets/acc7cfad-680d-4493-9546-4df5ae218beb)
