### ISSUE TITLE
autofreeze idle timer

### ISSUE THREAD

**Issue by eMPee584** [htop-dev/htop#1514]
In my tmux sessions I regularly forget / ignore to close htop instances and some keep long running for a reason. An idle timer to freeze would be awesome. The PAUSED indicator should be made much more visible in that case though:
![Screenshot_2024-08-09_20-55-50](https://github.com/user-attachments/assets/fa622b24-282b-40bf-bcc4-c46eb3d25b4b)

Maybe additionally, an option to auto-unfreeze on key or mouse input.

**Comment by fasterit** [comment]
htop cannot differentiate whether it runs for days on a public screen in some "war room" or in a tmux session of a forgetful admin, so this is technically not possible.
Also it does not really make sense, htop typically takes a few % of one core, so not really worth the hassle of implementing such a function.
/DLange

**Comment by eMPee584** [comment]
Well it just would check time difference to last input event, not really much of an algorithm as much as a time stamp set on user input..

**Comment by BenBE** [comment]
Let's explain this visually …
![image](https://github.com/user-attachments/assets/53b6921a-1629-4112-aeb5-43150206e33b)

**Comment by eMPee584** [comment]
- => Better visible marker of PAUSED status
- => option disabled by default

**Comment by BenBE** [comment]
You could flash the pause indicator full-screen and I'm sure people would still complain they missed the hint.

Furthermore it's already off by default; it just doesn't give you an option to enable it too …

**Comment by eMPee584** [comment]
Ok i see noone in favor of this.. maybe I'm going to implement and fill a pull request another time :shrug:
