### ISSUE TITLE
"Unknown option" error

### ISSUE THREAD

**Issue by mdziczkowski** [htop-dev/htop#1532]
## OS
- **Type**: Debian (bookworm)

- **htop version**: 3.2.2

- **libcap version**: 2 66

### Tryed to do:

I tryed to use a parameter with is listed in both: manual and htop help: `--drop-capabilities`

### Expected result:

Running htop with the given parameters

### Actual rssult:

`
htop: Invalid option: --drop-capabilities
`

***Note***: State before update

**Comment by fasterit** [comment]
The Debian version is compiled without `--enable-capabilities` . We should make IFDEFs around the help text and amend the man page.

**Comment by BenBE** [comment]
This already seems to be the case on `main`:

Options:
https://github.com/htop-dev/htop/blob/fc54b885ef75b8edacc4a9758f29b51e16025d34/linux/Platform.h#L99-L104

Usage:
https://github.com/htop-dev/htop/blob/fc54b885ef75b8edacc4a9758f29b51e16025d34/linux/Platform.c#L923-L932

Handling:
https://github.com/htop-dev/htop/blob/fc54b885ef75b8edacc4a9758f29b51e16025d34/linux/Platform.c#L942-L962

**Comment by mdziczkowski** [comment]
> The Debian version is compiled without `--enable-capabilities` . We should make IFDEFs around the help text and amend the man page.

Why that? Capabilities are a integral part of a Debian system.

Besides of that, if htop was compiled without it then why does this option appear in the documentation and manual of it if it can't be used? 🤔

In my modest opinion, this option should be enabled as default due compilation 😉

**Comment by fasterit** [comment]
Because it pulls in another library and the whole function - as is - is only useful if you run `htop` as root and what to limit its capabilities at the same time.
