### ISSUE TITLE
Discussion: Replace function-like macros by inline functions?

### ISSUE THREAD

**Issue by BenBE** [htop-dev/htop#154]
While working my way through several headers I noticed quite a few `#define`s that better should be inline functions.

This suggestion does not cover the various cast helpers, but things like e.g. `Settings_cpuId` or `xSnprintf`.

Detecting support for LTO in configure.ac we even could implement all those function outside the header files without loosing any performance.

**Comment by cgzones** [comment]
Me preference is also using type-safe (inline) function than macros (except generic types, like in `MAXIMUM`, are needed or the code location should not change, e.g. `__FILE__` for debugging).
The second point affects `xSnprintf`, when implemented like in #115.

**Comment by BenBE** [comment]
Regarding xSnprintf I just noticed that the macro is duplicated in both `XAlloc.h` and `XAlloc.c`. Patch to remove the duplication incoming.

**Comment by cgzones** [comment]
Considering the function `String_startsWith()` from *StringUtils.h* I see four ways to implement it:

**I (preprocessor macro)**
*StringUtils.h*:
```
#define String_startsWith(s, match) (strncmp((s),(match),strlen(match)) == 0)
```

**II (header inline function)**
*StringUtils.h*:
```
static inline bool String_startsWith(const char *s, const char *match) {
    return strncmp(s, match, strlen(match)) == 0;
}
```

**III (external inline function)**
*StringUtils.h*:
```
bool String_startsWith(const char *s, const char *match);
```
*StringUtils.c*:
```
extern inline bool String_startsWith(const char *s, const char *match) {
    return strncmp(s, match, strlen(match)) == 0;
}
```

**IV (normal function)**
*StringUtils.h*:
```
bool String_startsWith(const char *s, const char *match);
```
*StringUtils.c*:
```
bool String_startsWith(const char *s, const char *match) {
    return strncmp(s, match, strlen(match)) == 0;
}
```

IV probably depends on using LTO/IPO to get inlined.

**Comment by BenBE** [comment]
I'd prefer `IV` or `II`. Not sure about the semantics of `III`* though. And `I` should be avoided due to type safety issues.

*The gist I got from looking it up seems like an invitation to yourself for a hell lot of linking issues …

**Comment by cgzones** [comment]
Mentioned in https://github.com/htop-dev/htop/blob/master/docs/styleguide.md#symbol-exports
