### ISSUE TITLE
Can we add a CMake support for building project?

### ISSUE THREAD

**Issue by AryanGitHub** [htop-dev/htop#1550]
CMake (https://cmake.org/)

> CMake is cross-platform free and open-source software for build automation, testing, packaging and installation of software by using a compiler-independent method. 
Source: [Wikipedia](https://en.wikipedia.org/wiki/CMake)

An additional build support tool CMake for this project would be nice.
I would like to know the maintainers' reaction and decision on this, and hear their thoughts.

Thanks.

**Comment by BenBE** [comment]
No.
