### ISSUE TITLE
Can not save configuration to /Users/username/.config/htop/htoprc: Permission denied

### ISSUE THREAD

**Issue by upupnoah** [htop-dev/htop#1552]

**Comment by BenBE** [comment]
Check if the directory for this file exists and the user you are running htop as has sufficient permissions to read/modify this file.

**Comment by upupnoah** [comment]
`sudo chmod -R 755 /Users/username/.config/htop/`
The problem has been solved. Thx!

**Comment by upupnoah** [comment]
sudo chmod -R 755 /Users/username/.config/htop/
The problem has been solved. Thx!
