### ISSUE TITLE
htop don't sort processes in terminal on Mac OS 15.0.1

### ISSUE THREAD

**Issue by Masorubka1** [htop-dev/htop#1556]
<img width="796" alt="image" src="https://github.com/user-attachments/assets/8c9d17c0-aa1e-410d-ad61-dd4b64440bd0">

**Comment by BenBE** [comment]
Which version of htop?

Also note, that sorting in tree view mode operates per parent when sorting processes.

**Comment by Masorubka1** [comment]
htop --version
htop 3.3.0

**Comment by Masorubka1** [comment]
> Also note, that sorting in tree view mode operates per parent when sorting processes.

I hadn’t made any specific settings changes before. However, I noticed that the tree view mode was somehow enabled in htop. After turning it off, everything started working as expected, including the sorting of processes. In tree view mode, sorting applies only within the context of a parent process, so processes might not appear sorted globally as you’d expect. Disabling the tree view resolved that issue for me.

**Comment by fasterit** [comment]
Closing as this seems sorted
