### ISSUE TITLE
Weird edge case when creating/deleting tab screens

### ISSUE THREAD

**Issue by hishamhm** [htop-dev/htop#1565]
How to reproduce:

* `rm ~/.config/htop/htoprc`
* `F2` - Setup
* go to `Screens`
* move right, to `Main` (the second column)
* `F5` - New, `Enter`.
* go to `I/O`, `F9` - Delete it.
* go to `Main`, `F9` - Delete it. `New` is our only tab now.
* go to `Active Columns` (the third column)
* select `PID`, `F9` - Delete it. `Command` is our only column in our only `New` screen.
* `Esc` to return to the main screen
* process list is empty!

If I quit and restart `htop`, then the process list behaves as expected, and `New` is the only screen with `Command` entries showing as expected.

**Comment by fasterit** [comment]
This does luckily not reproduce with current `main` tip (4102862). It shows the lonesome `Command` column as intended.

**Comment by hishamhm** [comment]
@fasterit great to hear! thanks for giving it a try!
