### ISSUE TITLE
Regression overflow of VIRT if ~100G

### ISSUE THREAD

**Issue by Nudin** [htop-dev/htop#163]
The human readable sizes were displayed in base 1000 up to 3.0.2 and are now (master) displayed in base 1024 – is that right?

If the value of VIRT (vitual memory) is between 100GB and 100GiB it should be displayed as "100G" or "98.5G" but they are now displayed as "100.2G" and in 3.0.2 they were displayed as "98G". The new format results in a visual overflow. -> Picture

Above: htop 3.0.2
Below: master branch
![Bildschirmfoto](https://user-images.githubusercontent.com/509205/93691635-20ed4a00-fae8-11ea-9e77-cb1168e32463.png)

The origin is this line: https://github.com/htop-dev/htop/blob/5ea13e7ea9ca19130d5114a745d337b052cf2199/Process.c#L96

**Comment by BenBE** [comment]
I'll have a look. Likely a missing check introduced while rewriting that code in #125.

**Comment by BenBE** [comment]
Can you test the following patch?

```diff
diff --git a/Process.c b/Process.c
index 343a736..428e121 100644
--- a/Process.c
+++ b/Process.c
@@ -93,7 +93,7 @@ void Process_humanNumber(RichString* str, unsigned long number, bool coloring) {
       number %= 1000;
       len = snprintf(buffer, 10, "%03luM ", number);
       RichString_appendn(str, processMegabytesColor, buffer, len);
-   } else if (number < 100 * ONE_M) {
+   } else if (number < 100000 * ONE_K) {
       //2 digit GB, 1 digit MB
       number /= 100 * ONE_K;
       len = snprintf(buffer, 10, "%2lu", number/10);
```

Proper patch follows later on.

NB: How to get processes to legitly use such an insane amount of virtual memory? Even with Chromium I had trouble testing the 10GiB case …

**Comment by Nudin** [comment]
> Can you test the following patch?

This restores the old behavior. (Which is good but not ideal)

> NB: How to get processes to legitly use such an insane amount of virtual memory? Even with Chromium I had trouble testing the 10GiB case …

I actually had a process that used that much by chance. But you can easily test it the following way:

```
$ echo 1 | sudo tee /proc/sys/vm/overcommit_memory
$ python
>> import numpy
>> x=numpy.empty([1024**3//8, 99]])
>> #del x or exit python to get rid of it
# Restore default setting for overcommitment:
$ echo 0 | sudo tee /proc/sys/vm/overcommit_memory
```

**Comment by BenBE** [comment]
> > Can you test the following patch?
> 
> This restores the old behavior. (Which is good but not ideal)
> 
Actually The patch in #125 did two things:
1. Rewrite of the display routine
2. Introduction of a new coloring between GB and huge (grey>blue>red --> grey>blue>green>red)
3. Introduction of the partial coloring of numbers for GB and TB

What that snippet changed was the boundary when the 100GB case needed to be applied (previously at 102400MiB[buggy], now at 100000MiB). 

> > NB: How to get processes to legitly use such an insane amount of virtual memory? Even with Chromium I had trouble testing the 10GiB case …
> 
> I actually had a process that used that much by chance. But you can easily test it the following way:
> 
Just curious.

But when I take your statement above correctly I can go forward and PR the above patch proper.

**Comment by Nudin** [comment]
Yes, you can submit the patch.

What I meant by not perfect is, that we display 94.3 GiB as `94,3G` while we display 98,3 GiB as `98G`.

**Comment by BenBE** [comment]
If there's a simple way to get to the localized char for the decimal separator, I'll take it. Isn't to hard to include.
