### ISSUE TITLE
Crash when using battery

### ISSUE THREAD

**Issue by LiteracyFanatic** [htop-dev/htop#17]
First of all, I'm really glad to see development happening on this project again!

With `v3.0.0` attempting to add the battery meter crashes `htop` with the following error:

```
htop: No such file or directory
```

I'm running Arch Linux with the `5.8.1` kernel.

**Comment by cgzones** [comment]
Probably a duplicate of #15 .
Can you verify whether https://github.com/htop-dev/htop/commit/b992d52bcf8ff8c51c847cd4bbf33a7db441dbe9 solves your issue?

**Comment by LiteracyFanatic** [comment]
Indeed it does. Sorry for the duplicate.
