### ISSUE TITLE
Enhancement: memory values in human readable format

### ISSUE THREAD

**Issue by hmble** [htop-dev/htop#171]
Seeing big numbers like 4407M in htop makes it annoying to read. Please can you add some sort of option or keybinding to make this numbers in humand readable format

4407M : 4.4G
4407K : 4.4M

**Comment by BenBE** [comment]
What about the recent changes of #125 + #164?

The advantage of this method of highlighting is one significant digit more fitting the same space. Thus the floating point representation is only used for rare cases.

**Comment by hmble** [comment]
Thank you. But it still doesn't work for 4 digit MB.
Also it would be nice to convert bytes like 81588 mentioned in screenshot to 81.5K
![2020-09-23-094819_203x133_scrot](https://user-images.githubusercontent.com/16825207/93966891-76915300-fd83-11ea-923c-8c7c3e41c122.png)

**Comment by BenBE** [comment]
Sure you got a version with the mentioned patches? Looks like this for me (current master):

![image](https://user-images.githubusercontent.com/111196/93980394-db967a00-fd7e-11ea-81df-4d5ff430e56b.png)

Regarding the issue of adding the K suffix for small values: when I rewrote the highlighting routine I though about whether to change this or not but in the end decided against it as for small values (programs that use less than 100MB of memory) this gives you five significant digits, which for these small tools bears some value. Also the routine for highlighting those values is re-used for some other columns, thus you'd have to check for conflicts there.

**Comment by hmble** [comment]
Your decision makes sense to me. Thank you for insight. Waiting for next release :)
