### ISSUE TITLE
OOM does not sort properly

### ISSUE THREAD

**Issue by LiteracyFanatic** [htop-dev/htop#18]
One long-standing bug I'd love to see resolved is the problem with sorting by the `OOM` column. Currently the order seems to jump around at random.

![2020-08-28T04:00:22-05:00](https://user-images.githubusercontent.com/18249574/91542180-0d810180-e8e3-11ea-806a-5f706415f2b0.png)

**Comment by cgzones** [comment]
Can you try out #22?
It should solve this issue.

**Comment by LiteracyFanatic** [comment]
Yup, that fixed it. Thanks.
