### ISSUE TITLE
feature wish: list locks of a process

### ISSUE THREAD

**Issue by ncqgm** [htop-dev/htop#184]
I wonder whether "list locks for a process" functionality
can be integrated into htop. See lslocks --pid

Thanks,
Karsten

**Comment by BenBE** [comment]
`lslocks` is part of `util-linux` which upstreams from http://www.kernel.org/pub/linux/utils/util-linux/ (Licence: GPL, unknown version).

Unfortunately I couldn't find any authoritive description of /proc/locks in the kernel docs. :(

**Comment by ncqgm** [comment]
On Sat, Sep 26, 2020 at 01:13:10PM -0700, BenBE wrote:

> `lslocks` is part of `util-linux` which upstreams from http://www.kernel.org/pub/linux/utils/util-linux/ (Licence: GPL, unknown version).
>
> Unfortunately I couldn't find any authoritive description of /proc/locks in the kernel docs. :(

This won't count, will it ?

	https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s2-proc-locks

Karsten
--
GPG  40BE 5B0E C98E 1713 AFA6  5BC0 3BEA AC80 7D4F C89B

**Comment by BenBE** [comment]
> On Sat, Sep 26, 2020 at 01:13:10PM -0700, BenBE wrote: `lslocks` is part of `util-linux` which upstreams from http://www.kernel.org/pub/linux/utils/util-linux/ (Licence: GPL, unknown version). Unfortunately I couldn't find any authoritive description of /proc/locks in the kernel docs. :(
> This won't count, will it ? https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s2-proc-locks

I saw that link, but this is barely the minimum to read most of the columns, but for some information I'm not sure if this is all, or if it just represents some "reverse engineered" write-up. But based on that information at least 5 columns (`#locks`, `#lock_r`, `#lock_w`, `#aquire_locks`, `#mandatory_locks`) could be made. In addition a special locks view similar to the open files screen could be made.
