### ISSUE TITLE
Inconsistent highlighting

### ISSUE THREAD

**Issue by LiteracyFanatic** [htop-dev/htop#19]
Any column which contains values in both bytes and megabytes has inconsistent highlighting applied to it. I'm actually not sure what the purpose of the column being highlighted is in the first place. Any idea what that is supposed to indicate?

![2020-08-28T04:03:45-05:00](https://user-images.githubusercontent.com/18249574/91542542-a44dbe00-e8e3-11ea-834e-bdad817fd4c4.png)

**Comment by cgzones** [comment]
For me it looks quite sane:
The megabyte part of the value gets highlighted.
So in `100M` all digits get highlighted and in `91092` only the first two megabyte indicating digits.

**Comment by LiteracyFanatic** [comment]
Ah, is that what the highlighting means? Wouldn't it be clearer to display a value such as `91092` as `91M` or `91.1M`. I don't see the benefit of switching to bytes until we reach values under `1M`. Specifically, `91092` takes up more space than `91M` and has more significant figures than `91.1M`. At the very least, I think it would be nice if the meaning of the highlighting was documented somewhere as it wasn't immediately obvious to me.

**Comment by BenBE** [comment]
The un-suffixed values are in KiB. To actually to be consistent, you'd probably should add a K for those columns too.

One thing that IS inconsistent though is highlighting of GiB values:

1500M is marked all in MB color, while 12G is marked in GB color. To be consistent for 1500M IMHO it should be 1 in the GB color and 500M in the MB color.

**Comment by cgzones** [comment]
The overall style is as intended and the issues with inconsistent colouring has been addressed with https://github.com/htop-dev/htop/commit/40441dca8e22f30297b45f78a58013e9face3935.
