### ISSUE TITLE
Looks messy with tmux

### ISSUE THREAD

**Issue by COOLMSF** [htop-dev/htop#198]
Running environment:

```
uname -a
Linux Thinkpad-T480 5.7.19-2-MANJARO #1 SMP PREEMPT Fri Aug 28 20:22:12 UTC 2020 x86_64 GNU/Linux
```

```
htop --version                                                                  
htop 3.0.1
```

```
tmux -V                                                                 
tmux 3.1b
```
![2020-10-01-113336_1366x768_scrot](https://user-images.githubusercontent.com/18681657/94762630-d66aa800-03da-11eb-8f35-525feb197bb1.png)

**Comment by cgzones** [comment]
Is the output still messy with the option `-U --no-unicode             Do not use unicode but plain ASCII` ?

**Comment by BenBE** [comment]
Which value does the `TERM` variable have? Is the value of that `TERM` variable correct and matching your terminal implementation? For me this is `xterm-256color` outside `tmux` and `screen` inside the `tmux` session. Looks fine here (on Lubuntu).

**Comment by COOLMSF** [comment]
> Is the output still messy with the option `-U --no-unicode Do not use unicode but plain ASCII` ?

Works fine now, thank you.

**Comment by COOLMSF** [comment]
> Which value does the `TERM` variable have? Is the value of that `TERM` variable correct and matching your terminal implementation? For me this is `xterm-256color` outside `tmux` and `screen` inside the `tmux` session. Looks fine here (on Lubuntu).

Maybe something wrong with unicode, works fine now, thank you.

**Comment by COOLMSF** [comment]
> > Is the output still messy with the option `-U --no-unicode Do not use unicode but plain ASCII` ?
> 
> Works fine now, thank you.
> Not work now.

**Comment by COOLMSF** [comment]
> > Which value does the `TERM` variable have? Is the value of that `TERM` variable correct and matching your terminal implementation? For me this is `xterm-256color` outside `tmux` and `screen` inside the `tmux` session. Looks fine here (on Lubuntu).
> 
> sh-5.1$ echo $TERM
> screen-256color
