### ISSUE TITLE
STARTTIME is incorrect

### ISSUE THREAD

**Issue by cherio** [htop-dev/htop#202]
I have several up-to-date instances of Ubuntu 20.04 and one of them consistently shows incorrect STARTTIME. The column often shows the same timestamp for most processes with only a handful of top level exceptions like `/sbin/init` and `/lib/systemd/systemd`.

In the same instance the old issue of process name not being completely refreshed is back. This is very noticeable with postrgesql processes that change process name according to the command they execute. E.g. when a process changes state from running a `SELECT` to `idle` the process name changes from `SELECT` to `idleCT` keeping the last 2 characters "CT" of `SELECT`.

As a reference `top` when run with `-o lstart` produces correct process start timestamp.

```
:~# htop -v
htop 2.2.0 - (C) 2004-2019 Hisham Muhammad
Released under the GNU GPL.

```

**Comment by BenBE** [comment]
Can you check the issue using the current master branch (or the latest release version 3.0.2)?

**Comment by cherio** [comment]
I downloaded [3.0.2-1 package from debian testing](http://ftp.us.debian.org/debian/pool/main/h/htop/htop_3.0.2-1_amd64.deb) (bullseye), installed it in Ubuntu 20.04.1 LTS and `STARTTIME` seems to work correctly. I can't do this in production environment though, production requirements are to have everything installed from the standard repositories.

**Comment by BenBE** [comment]
Unfortunately we do not have much influence on when downstream distributions pull newer versions from here. For a list which version is available where have a look at https://github.com/htop-dev/htop/issues/62#issuecomment-685343172. Also as noted in https://github.com/htop-dev/htop/issues/62#issuecomment-685092964 you might be able to use the htop snap as an alternative.

**Comment by fasterit** [comment]
Also note "production requirements" are documents written by people. They can be amended if you care to avoid the small bug enough to warrant that.
