### ISSUE TITLE
Calculate library size of the process by hand [Linux]

### ISSUE THREAD

**Issue by cgzones** [htop-dev/htop#222]
Origin: #189 

On Linux the proc/[pid]/statm field `lib` ("The library size of the process") is unused since Linux 2.6 (always 0).

> BenBe:
Couldn't we "calculate" the lib size based on `/proc/<PID>/maps` by adding up all ranges with `INODE != 0` and at least one segment for that inode marked executable?

**Comment by fasterit** [comment]
May be the calculations of [smem](https://www.selenic.com/smem/) are useful?
Basically their "Proportional Set Size (PSS)" sums up library memory consumption but divides it by the processes having linked to that library.

**Comment by natoscott** [comment]
Just something to be aware of - the smaps file (used in PSS calcs) is relatively expensive to access, compared to maps.  There's a smaps_rollup file in more recent kernels, which offsets some of the costs but its still quite expensive.  Some other tools (e.g. atop) have a command line option to opt-in to accessing the more costly info...

```
$ sudo time cat /proc/*/smaps > /dev/null
0.01user 0.27system 0:00.29elapsed 97%CPU
$ sudo time cat /proc/*/smaps_rollup > /dev/null
0.00user 0.13system 0:00.14elapsed 97%CPU
$ sudo time cat /proc/*/maps > /dev/null
0.00user 0.03system 0:00.03elapsed 94%CPU
```
