### ISSUE TITLE
feature request: Easier toggling of CPU bars at top

### ISSUE THREAD

**Issue by wwood** [htop-dev/htop#225]
Hi,

Thanks for all your efforts on htop, I use it daily.

We recently got some new nodes that have 128 CPUs, and on my laptop (unlike my desktop) this means that the visual at the top takes up almost all the real estate, leaving not much for individual processes. I know I can switch it off in the settings, but this is maybe 5 keystrokes, so I resort to zooming out my terminal.

Is there some command line option that can be set to run htop without the CPU meters?
Thanks, ben

**Comment by fasterit** [comment]
This is quite a duplicate of #168, @wwood do you agree?

**Comment by BenBE** [comment]
@wwood You also might try if the 8-columns option (#179) recently introduced might help you gain some space on your screen.

**Comment by wwood** [comment]
Sorry for the dup. Agree, and thanks @BenBE
