### ISSUE TITLE
Colours don't work when `TERM=tmux-256color`

### ISSUE THREAD

**Issue by carlocab** [htop-dev/htop#251]
`htop` runs with no colours when `TERM=tmux-256color`. I've verified that `htop` runs normally upon changing `TERM` to something else (e.g. `screen` or `xterm`, even without the `-256color` suffix).

For reference, I am running `htop 3.0.2` on macOS 10.15.7 and Zsh 5.8 + oh-my-zsh. htop and Zsh were both installed using Homebrew.

**Comment by cgzones** [comment]
A quick search found related issues:
https://github.com/tmux/tmux/issues/2262
https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95

Seems to be a ncurses issue on macOS.

**Comment by carlocab** [comment]
Thanks for looking into this. Does this mean you're not able to reproduce the problem on another system?

Those posts are about how the macOS built-in ncurses does not have a definition for tmux-256color in terminfo, so one has to add one manually some other way (which I've done, or else it wouldn't just be htop's colours that doesn't work). I don't think they report any remaining problems once one has done that.

Or have I misunderstood something?

**Comment by Frederick888** [comment]
I can confirm this happens under macOS but not Linux. I've also followed the instructions above to generate the terminfo's.

**Comment by carlocab** [comment]
@Frederick888 Thanks for checking. Which terminal emulators did you try it with on Linux?

Would you know how to check if the `terminfo`s generated by the instructions above are identical to the one that comes with your Linux distro?

**Comment by Frederick888** [comment]
@carlocab I'm using iTerm 2 and Kitty.

iTerm and Kitty themselves are using `xterm-256color` and `xterm-kitty` respectively. I didn't touch these files but simply linked `xterm-kitty` from `~/Applications` to `~/.terminfo`. The macOS `xterm-kitty` is exactly the same as the one under Arch Linux.

`tmux-256color` (and `tmux`) though are generated using the instruction above, and they are different from what I've got under Linux.
[terminfo.zip](https://github.com/htop-dev/htop/files/5443404/terminfo.zip)

**Comment by carlocab** [comment]
Aha. It seems the `terminfo` for `tmux-256color` that comes with the latest Homebrew `ncurses`, or even the one downloaded from [invisible-island.net](https://invisible-island.net/datafiles/current/terminfo.src.gz) is not configured to work properly with `htop`. Very strange.

After a bit of looking around, it seems the best one to use is the one provided by the maintainer of tmux, found here: https://gist.github.com/nicm/ea9cf3c93f22e0246ec858122d9abea1

Using that one restores colours in `htop` for me. It can be installed by downloading the gist and running `/usr/bin/tic -x <gist filename>`.

Thanks to @Frederick888 for helping me diagnose the issue.

**Comment by carlocab** [comment]
You shouldn't have any issues with macOS 14 or newer. If you are on an older version of macOS, you can follow the instructions at https://gpanders.com/blog/the-definitive-guide-to-using-tmux-256color-on-macos/.
