### ISSUE TITLE
Use MemTotal: - MemAvailable: for usedMem calculation on Linux 3.14+

### ISSUE THREAD

**Issue by ChrisCheney** [htop-dev/htop#281]
htop currently parses /proc/meminfo and uses the following formula to calculate used memory under Linux:

`usedMem = ((MemTotal:) + (MemFree:)) - ((Buffers:) + ((Cached:) + (SReclaimable:) - (Shmem:))`

However, this does not properly display actual used memory and there is a much simpler and accurate way to do it.

Since Linux 3.14 was released in March 2014 the best way to report this number is to just do the following instead:

`usedMem = ((MemTotal:) - (MemAvailable:))`

[/proc/meminfo: provide estimated available memory git commit for Linux 3.14-rc1](https://github.com/torvalds/linux/commit/34e431b0ae398fc54ea69ff85ec700722c9da773)

> 
> **/proc/meminfo: provide estimated available memory** 
> Many load balancing and workload placing programs check /proc/meminfo to
> estimate how much free memory is available.  They generally do this by
> adding up "free" and "cached", which was fine ten years ago, but is
> pretty much guaranteed to be wrong today.
> 
> It is wrong because Cached includes memory that is not freeable as page
> cache, for example shared memory segments, tmpfs, and ramfs, and it does
> not include reclaimable slab memory, which can take up a large fraction
> of system memory on mostly idle systems with lots of files.
> 
> Currently, the amount of memory that is available for a new workload,
> without pushing the system into swap, can be estimated from MemFree,
> Active(file), Inactive(file), and SReclaimable, as well as the "low"
> watermarks from /proc/zoneinfo.
> 
> However, this may change in the future, and user space really should not
> be expected to know kernel internals to come up with an estimate for the
> amount of free memory.
> 
> It is more convenient to provide such an estimate in /proc/meminfo.  If
> things change in the future, we only have to change it in one place.
> 
> Signed-off-by: Rik van Riel <riel@redhat.com>
> Reported-by: Erik Mouw <erik.mouw_2@nxp.com>
> Acked-by: Johannes Weiner <hannes@cmpxchg.org>
> Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
> Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

**Comment by tWido** [comment]
@ChrisCheney  
Could you please provide information for other memory counters too? Namely buffers and cached memory. Are they currently correct and should be displayed same way?
I implemented counting the proposed way and it shows slightly higher memory consumption (f.e. for me +300MB). Thus i want to avoid situation when used + buffers + cached is higher than total memory.
Thanks.

**Comment by ChrisCheney** [comment]
I have included my /proc/meminfo below.

From the kernel git commit mentioned actual used non-freeable memory isn't easily directly mappable to a subset of memory fields since it changes over time. The kernel git commit mentioned a way to get an estimate back from 2014 but it may have changed since then.

It looks like htop uses the used + buffers + cached to represent the different colors on its graphical output, if so that probably won't match up to total used memory.

At the moment htop is reporting ~ 1GB less than actual usage on my system, but I have seen the difference be a lot more at other times.

At the time the below was collected htop reported 18.0GB while conky (MemTotal - MemAvailable) reported 18.9GB

Current /proc/meminfo shows:
```
$ cat /proc/meminfo 
MemTotal:       65828796 kB
MemFree:        35541848 kB
MemAvailable:   46036636 kB
Buffers:         1700660 kB
Cached:         14893256 kB
SwapCached:           76 kB
Active:          6812048 kB
Inactive:       21684732 kB
Active(anon):     410436 kB
Inactive(anon): 17222424 kB
Active(file):    6401612 kB
Inactive(file):  4462308 kB
Unevictable:          48 kB
Mlocked:              48 kB
SwapTotal:       4194300 kB
SwapFree:        4190204 kB
Dirty:               556 kB
Writeback:             4 kB
AnonPages:      11903080 kB
Mapped:          6291212 kB
Shmem:           5730032 kB
KReclaimable:     565292 kB
Slab:             999460 kB
SReclaimable:     565292 kB
SUnreclaim:       434168 kB
KernelStack:       27600 kB
PageTables:        93252 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    37108696 kB
Committed_AS:   32198636 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       71360 kB
VmallocChunk:          0 kB
Percpu:            56192 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:    39517712 kB
DirectMap2M:    25405440 kB
DirectMap1G:     2097152 kB
```
