### ISSUE TITLE
Source tree structure

### ISSUE THREAD

**Issue by hyiltiz** [htop-dev/htop#304]
Is it practically possible, without breaking backward compatibility, platform compatibility etc., to maybe move all source code files such as `*.c` and `*.h` etc. from the root of the project folder into something like `./src`, so the project root folder has a more typical/common structure, such as `./src`, `./resources` or `./assets`, `./test`, `AUTHORS`, `LICENSE` etc.? Currently, Github makes me scroll a while before reaching to the rendered `Readme.md`. It may also make some packaging work easier.

**Comment by natoscott** [comment]
Good question.  After some discussion from the maintainers, we decided the disadvantages outweigh the advantages and chose to keep it as-is.

**Comment by hyiltiz** [comment]
Care to elaborate a bit so we can learn what are the contributing factors for such a widely cross-platform and popular package? Could be useful for someone trying to design a new package that aims for a similar availability.

**Comment by natoscott** [comment]
> Care to elaborate a bit so we can learn what are the contributing factors [...]

Sure - moving code around (aka code churn) messes with revision tracking - git-log becomes problematic - and it breaks open PRs and work-in-progress other people have in their forks or private repos/branches.  That's just me, I'm sure the other folks had their own reasons too.
