### ISSUE TITLE
Performance with --enable-debug unbearable

### ISSUE THREAD

**Issue by BenBE** [htop-dev/htop#314]
When creating a build with `--enable-debug` active the resulting binary is so slow, that startup already takes several seconds and navigating around in the program is unbearably slow.

A quick look at `cachegrind` suggests the main culprits are the Vector and Hashtable consistency checks.

While I agree that these checks should be available in the code, I'd suggest having them split into a separate `enable-consistency-debug` switch for `configure`.

As it is now, I get 77.3% of all runtime spent in `Vector_isConsistent` and another 21.4% spent in `Object_isA`. One cycle takes about 6m45s, thus making debugging anything borderline impossible (unless you're willing to watch yourself aging in the process).

**Comment by cgzones** [comment]
From my experience this slow-down is happening because of https://github.com/htop-dev/htop/blob/15eab2012d2100e1ddd20c186db23a8172b5858d/ProcessList.c#L176 and https://github.com/htop-dev/htop/blob/15eab2012d2100e1ddd20c186db23a8172b5858d/ProcessList.c#L131 in **tree**-mode. In **sorted**-mode the performance is quite ok.

**Comment by cgzones** [comment]
@BenBE  can this be closed since #315 got merged?

**Comment by BenBE** [comment]
Performance still isn't great overall even with this patch applied since `Vector_isConsistent` and `Hashtable_isConsistent` both are quite slow, but I think, for now we can close this as we are at least down into the "seconds per redraw" range (instead of minutes) …

Having the consistency stuff as a separate debug feature might be worth a thought.
