### ISSUE TITLE
[Request] Checking Hash With VirusTotal

### ISSUE THREAD

**Issue by zero77** [htop-dev/htop#319]
Can you please hash check with VirusTotal and show the result, if there’s no match of the hash can you upload the file to be checked.

Also, if the date they were last checked was more than a weak can you reanalyse and display new results, this should be possible with the api they provide.
Thanks

https://developers.virustotal.com/v2.0/reference

![](https://user-images.githubusercontent.com/16563034/39248831-0d89ad62-4895-11e8-8bb7-696211e69001.png)

**Comment by BenBE** [comment]
This is a feature that has so many external dependencies (HTTP, TLS, external services) which we all do not currently have, that it's quite unlikely this falls into the category of a small feature that keeps a small footprint. Especially when requesting these information for about 2000 processes at once you are likely to get kicked from the VirusTotal API. Additionally it's not quite clear which binary exactly and what hash should be submitted: Blindly submitting the on-disk hash doesn't help, if the malware resides in linked libraries or manipulates the executable in memory. Another good reason for not implementing this is the protection of the privacy of users.

Overall I don't think this feature is viable and of enough use to warrant the inevitable overhead and problems introduced by implementing this.

Also coming from a background of writing IT security related software I don't think anti-virus tools are much more than snake-oil opening up attack surface to your system.

**Comment by fasterit** [comment]
We discussed this in the core team yesterday. We definitely don't want any interface to proprietary web services and for the reasons @BenBE explained there is not much use in submitting on-disk hashes anyways. Closing.
