### ISSUE TITLE
Inconsistent labeling of M_SIZE vs VIRT

### ISSUE THREAD

**Issue by tecknicaltom** [htop-dev/htop#325]
In the main UI, the column for virtual memory size is labeled as "VIRT", however if you use F6 to choose the sort column, the menu choice is labeled "M_SIZE". I understand these to be referring to the same thing, but every time I try to sort, it takes a second to mentally equate the two, when they should really have more similar labeling. All of the other default columns have labels that more closely relate to each other between the column headings and the sort listing.

Note: this is on Linux. I don't know if other platforms have different representations of this data.

**Comment by BenBE** [comment]
I think `M_VIRT` instead of `M_SIZE` might be a better label then …
