### ISSUE TITLE
Alt-h/j/k/l not working when TERM not xterm* or vt220

### ISSUE THREAD

**Issue by ybc37** [htop-dev/htop#348]
Hey there,

first, thanks for the htop-dev initiative. Cool to see this project going :)

After upgrading to htop 3.0.0 I noticed that some of the added vim bindings do not work for me. I think at least all `Alt-` bindings. I finally got some time to look at it to be able to provide at least some information.

In my case `TERM` is set to `tmux-256color` or `alacritty` (if not in tmux). I realized it works when using `xterm*` and was able to pin it down to how the keys are defined in [CRT.c](https://github.com/htop-dev/htop/blob/f704baeb8211815f80a166c6837f421a82e1c515/CRT.c#L687-L706)

https://github.com/htop-dev/htop/blob/f704baeb8211815f80a166c6837f421a82e1c515/CRT.c#L687-L706

When skipping the condition it works for other `TERM` values as well (btw even on VTs; `TERM=linux`).

I'm not an expert, so not sure what's a valid approach to fix it. Adding every possible `TERM` that supports these keys most probably isn't ;) Is it somehow possible to check the "capabilities" of a terminal emulator instead of `TERM`? Or is it safe nowadays to drop this condition without breaking htop for other systems (the condition dates back even before the initial git import 15 years ago (d6231ba). Touched 3 years ago (45f3769) to support for everything that starts with `xterm`)?

**Comment by BenBE** [comment]
To make this fully portable the code would have to check the `termcap` library for the exact mappings.
Cf. https://www.gnu.org/software/termutils/manual/termcap-1.3/html_mono/termcap.html#SEC37
Unfortunately these definitions are regularly broken and thus unreliable …

**Comment by fasterit** [comment]
Just FTR, vim mode has been removed again in c9ecd0fa74a11278afcab063c905325873462dd2. The way it was implemented caused too many issues elsewhere.

**Comment by ybc37** [comment]
I think there's a misunderstanding: AFAIU the bindings I'm talking about are just alternative bindings to the default ones. I didn't use a dedicated "vim mode". I'm using htop 3.0.2 and also tested with current master.

Sorry, I wasn't aware of the difference of the vim key bindings and the vim mode.

**Comment by unrealapex** [comment]
My apologies for creating a duplicate issue for this. https://github.com/htop-dev/htop/commit/2b4feef421c35ee4ec892689585a9b0eb8816319 fixed this issue.
