### ISSUE TITLE
Coding Style Should be more "open" for everyone

### ISSUE THREAD

**Issue by hwpplayer1** [htop-dev/htop#351]
Hi there!

I am running your application on a critical server infrastructure and I want to get involved to the development progression/processes. I just want to add these paragraph to coding style part :

BSDs style, GNU style, Linux style or traditonal UNIX style is acceptable while you can read the whole source and can test it with a running package for your operating system or it's relase and distribution. 

I wanted to mean this application or tool is a cross platform utility so it should be more open for any contributor. 

If you don't agree with that I can say "It's okay" and try to hack some code in our hackerspace, then within the mission critical platform and send you the all code that we have.

https://github.com/htop-dev/htop/blob/master/CONTRIBUTING.md 

Happy Hacking!

**Comment by BenBE** [comment]
The coding style actually is a mixture of a few of the mentioned styles, with the most inspiration drawn from the BSD style. One of the major differences that you may slip over is the uncommon indentation size of 3 spaces - but you get used to this quite easily and your editor will likely help you with this.

Apart from this, there's currently a discussion ongoing regarding some minor tweaks to the coding style (which you can find [here](https://github.com/htop-dev/htop/blob/master/docs/styleguide.md). The discussion on the planned changes can be found in #336.

The current policy on the coding style is also handled quite loosely, thus if you write new code and roughly format it like its surroundings there's normally only minor details to discuss.

Sticking with what the current code is formatted like has been a deliberate decision to avoid major disturbance when maintaining older patchsets. The differences introduced by the (currently quite fast) changing code may cause enough work already. We're in the phase of refactoring that code base after all.

NB: Personally I dislike both GNU style (for its half-indentations) and Linux-style for it's lack of brace of single-line blocks.

**Comment by hwpplayer1** [comment]
I need to write here. Me and the project that I mention will follow mainly OpenBSD approach. So in general we are same at this point but I do not wanted the other hacker groups. 

Okay I agree on you.

See you later
