### ISSUE TITLE
support changing refresh rate in the ui itself

### ISSUE THREAD

**Issue by fawaf** [htop-dev/htop#356]
similar to how `top` does it with the `s` toggle for the "set update interval" command

**Comment by BenBE** [comment]
This has been addressed by #333 …

**Comment by fawaf** [comment]
one can enter a value directly in `top`. it does not look like the option supports directly entering a number?

**Comment by BenBE** [comment]
Currently not. You can use the `+`/`-` keys to change the value though.

**Comment by deric** [comment]
> one can enter a value directly in `top`. it does not look like the option supports directly entering a number?

You can still use e.g. `htop -d 10`. I know it's not in the UI, but at least you know what is the refresh interval.

> Currently not. You can use the `+`/`-` keys to change the value though.

This is nice, but you can't see what the actual value is, right? Btw. this feature isn't mentioned in the help.

**Comment by cgzones** [comment]
> This is nice, but you can't see what the actual value is, right?

It is in `Settings [F2] -> Display options -> Update interval (in seconds)`

**Comment by lUNuXl** [comment]
Hello, sorry for digging up a very old issue, but I found a really infuriating issue with this feature:

How do I lower the refresh rate?
There is no "help" shown on the bottom edge of the terminal, space and enter only increase it.

**Comment by campones** [comment]
actually it doesn't work here. the - key doesn't do anything.,
cannot decrease the value so after so many attempts I am almost at 7s intervalle.

**Comment by fasterit** [comment]
Use the main keyboard <kbd>-</kbd> (minus), not the one on the num pad. Does that work?

**Comment by campones** [comment]
where is that?

**Comment by campones** [comment]
ok found it with the -  from the main keyboard yes.  pretty unintuitive I d say

**Comment by BenBE** [comment]
Closing this as the original feature request was implemented ages ago.
