### ISSUE TITLE
CPU usage incorrect on macOS Big Sur with M1 chip

### ISSUE THREAD

**Issue by sfzhu93** [htop-dev/htop#368]
I wrote a non-stop loop in Python. On the right, `top` correctly shows the cpu usage as 100% but on the left `htop`
<img width="1434" alt="Screen Shot 2020-12-06 at 3 27 04 AM" src="https://user-images.githubusercontent.com/42506672/101275384-37b04e00-3773-11eb-8173-c62c62f46f71.png">
 shows aroung 2.4%.

**Comment by BenBE** [comment]
The screenshots you provided do not provide enough information to exclude the possibility you that you are watching two different instances of Python. Especially as the runtime of the process doesn't match up in the slightest (1.9 seconds vs. 1 minute, 19 seconds). Please provide a better illustration of the issue to avoid the possibility that the issue is just related to oversight on your side.

**Comment by sfzhu93** [comment]
@BenBE  Hello, I double checked that again. Every second htop refreshes, the time of the python command only increases about 0.03-0.04. I guess it is the CPU time, not the time span since the process being created. Because the CPU usage is incorrect, the CPU time is also incorrect.

**Comment by sfzhu93** [comment]
In addition, this is the source code of my deadloop.py
```
while True:
    pass
```
and a more complete screenshot of it on htop
<img width="1370" alt="Screen Shot 2020-12-06 at 4 06 49 PM" src="https://user-images.githubusercontent.com/42506672/101292407-459ab900-37dd-11eb-9b88-c22e3d83e80f.png">

**Comment by BenBE** [comment]
Thank you for reporting this issue.

Can you maybe run some checks with the current master (3.0.3)? Also, when compiling, try to enable debugging symbols and have a look at the data reported for the affected process in `darwin/DarwinProcessList.c` around line 204. The information of interest are the contents of `ps[i]` and `proc` for one process. Depending on your proficiency with `gdb` (tip: [pwndbg](https://github.com/pwndbg/pwndbg)) you can also try to insert some statements like `printf("%d    \r\n", value);` at that location, which will appear in the upper left corner; although a full, consistent dump of the two structures is preferred.

**Comment by cfstras** [comment]
Still happens on master (ded9c5d36332401bb8d5e33b6f72de188a42560d):
The pid matches python, and any process with an infinite loop gets 2.4% CPU for me.

<img width="961" alt="image" src="https://user-images.githubusercontent.com/1156864/101607922-65acc100-3a05-11eb-849c-adea5a088213.png">

Here are dumps of the structures: (had a different pid when I got debugging to work, but I double-checked, and there are no other python processes)
```
(lldb) p *proc
(DarwinProcess) $9 = {
  super = {
    super = {
      klass = 0x000000010048a0b0
    }
    processList = 0x0000000125e07ec0
    settings = 0x0000000125e081a0
    time = 565
    pid = 12196
    ppid = 1339
    tgid = 12196
    comm = 0x0000000125e0bf90 "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python"
    commLen = 0
    indent = 0
    basenameOffset = 128
    updated = true
    state = '?'
    tag = false
    showChildren = true
    show = true
    wasShown = true
    pgrp = 12195
    session = 0
    tty_nr = 4
    tpgid = 1339
    st_uid = 501
    flags = 0
    processor = 0
    percent_cpu = 2.38763595
    percent_mem = 0.0176429749
    user = 0x0000000125e0b0c0 "claus"
    priority = 17
    nice = 0
    nlwp = 1
    starttime_show = "11:28 "
    starttime_ctime = 1607509694
    m_virt = 25504277
    m_resident = 185
    exit_signal = 0
    seenTs = 0
    tombTs = 0
    minflt = 0
    majflt = 877
    tree_left = 0
    tree_right = 0
    tree_depth = 0
    tree_index = 0
  }
  utime = 5642275712
  stime = 15862332
  taskAccess = false
}
(lldb)
```
```
(lldb) p psi
(kinfo_proc) $8 = {
  kp_proc = {
    p_un = {
      p_st1 = (__p_forw = 0x000000005fd0a6be, __p_back = 0x000000000002cf92)
      __p_starttime = (tv_sec = 1607509694, tv_usec = 184210)
    }
    p_vmspace = 0x0000000000000000
    p_sigacts = 0x0000000000000000
    p_flag = 16518
    p_stat = '\x02'
    p_pid = 12196
    p_oppid = 0
    p_dupfd = 0
    user_stack = 0x0000000000000000
    exit_thread = 0x0000000000000000
    p_debugger = 0
    sigwait = 0
    p_estcpu = 0
    p_cpticks = 0
    p_pctcpu = 0
    p_wchan = 0x0000000000000000
    p_wmesg = 0x0000000000000000
    p_swtime = 0
    p_slptime = 0
    p_realtimer = {
      it_interval = (tv_sec = 0, tv_usec = 0)
      it_value = (tv_sec = 0, tv_usec = 0)
    }
    p_rtime = (tv_sec = 0, tv_usec = 0)
    p_uticks = 0
    p_sticks = 0
    p_iticks = 0
    p_traceflag = 0
    p_tracep = 0x0000000000000000
    p_siglist = 0
    p_textvp = 0x0000000000000000
    p_holdcnt = 0
    p_sigmask = 0
    p_sigignore = 424185856
    p_sigcatch = 2
    p_priority = '\x11'
    p_usrpri = '\0'
    p_nice = '\0'
    p_comm = "Python"
    p_pgrp = 0x0000000000000000
    p_addr = 0x0000000000000000
    p_xstat = 19
    p_acflag = 0
    p_ru = 0x0000000000000000
  }
  kp_eproc = {
    e_paddr = 0x0000000000000000
    e_sess = 0x0000000000000000
    e_pcred = (pc_lock = "", pc_ucred = 0x0000000000000000, p_ruid = 501, p_svuid = 501, p_rgid = 20, p_svgid = 20, p_refcnt = 0)
    e_ucred = {
      cr_ref = 29
      cr_uid = 501
      cr_ngroups = 16
      cr_groups = {
        [0] = 20
        [1] = 12
        [2] = 61
        [3] = 79
        [4] = 80
        [5] = 81
        [6] = 98
        [7] = 701
        [8] = 33
        [9] = 100
        [10] = 204
        [11] = 250
        [12] = 395
        [13] = 398
        [14] = 399
        [15] = 400
      }
    }
    e_vm = {
      dummy = 0
      dummy2 = 0x0000000000000000
      dummy3 = ([0] = 0, [1] = 0, [2] = 0, [3] = 0, [4] = 0)
      dummy4 = ([0] = 0x0000000000000000, [1] = 0x0000000000000000, [2] = 0x0000000000000000)
    }
    e_ppid = 1339
    e_pgid = 12195
    e_jobc = 1
    e_tdev = 268435460
    e_tpgid = 12195
    e_tsess = 0x0000000000000000
    e_wmesg = ""
    e_xsize = 0
    e_xrssize = 0
    e_xccount = 0
    e_xswrss = 0
    e_flag = 1
    e_login = ""
    e_spare = (0, 0, 0, 0)
  }
}
(lldb)
```

**Comment by BenBE** [comment]
Okay, It looks as if there are at least some reasonable values for stime/utime set in the process structure.

Could you again dump the following values from `darwin/DarwinProcess.c` lines 248-251:
* `pti`
* `diff`
* `proc->utime`
* `proc->stime`
* `dpl->super.cpuCount`
* `dpl->global_diff`

There's even a comment with a `fprintf` statement prepared. If you surround this by some query for `if(proc->pid == YOUR_PYTHON_PID)` you can get the information without much debugger work … Ideal would be to have the snapshots for several subsequent updates of the `percent_cpu` field.

**Comment by cfstras** [comment]
Okay, I snapshotted the variables and made a recording of a few lines from the printf call

|proc->super.percent_cpu| proc->stime| proc->utime|pti.pti_total_system|pti.pti_total_user| dpl->global_diff|
|---|---|---|---|---|---|
|2.395147 |2572070 |728823024 |2708545 |764733516 |1204
|2.399715 |2708545 |764733516 |2805954 |800841812 |1207
|2.407964 |2805954 |800841812 |2902793 |841409472 |1351
|2.394645 |2902793 |841409472 |3059223 |877382244 |1207
|2.398587 |3059223 |877382244 |3122321 |913447860 |1205
|2.406301 |3122321 |913447860 |3188019 |949627078 |1205
|2.402694 |3188019 |949627078 |3400778 |985574870 |1204
|2.400046 |3400778 |985574870 |3488410 |1021667935 |1206
|2.398098 |3488410 |1021667935 |3588269 |1057749383 |1207
|2.388481 |3588269 |1057749383 |3680302 |1093663703 |1206
|2.411631 |3680302 |1093663703 |3771326 |1129897874 |1205
|2.395917 |3771326 |1129897874 |3830955 |1165926740 |1205
| breakpoint set | see variables below |
| python stopped | with `ctrl+z` |
| first number is probably off because htop was paused? |
|2.585014 |3830955 |1165926740 |3952752 |1225454134 |1846
|2.078436 |3952752 |1225454134 |17532299 |3650477574 |93863
|0.000000 |17532299 |3650477574 |17532299 |3650477574 |1206
|0.000000 |17532299 |3650477574 |17532299 |3650477574 |1214
|0.000000 |17532299 |3650477574 |17532299 |3650477574 |1211
|0.000000 |17532299 |3650477574 |17532299 |3650477574 |1209
|0.000000 |17532299 |3650477574 |17532299 |3650477574 |1210
```

```
(lldb) v
(DarwinProcess *) proc = 0x000000013860b9c0
(DarwinProcessList *) dpl = 0x0000000138607ec0
(proc_taskinfo) pti = {
  pti_virtual_size = 417852637184
  pti_resident_size = 6504448
  pti_total_user = 1225454134
  pti_total_system = 3952752
  pti_threads_user = 1225454134
  pti_threads_system = 3952752
  pti_policy = 1
  pti_faults = 880
  pti_pageins = 3
  pti_cow_faults = 128
  pti_messages_sent = 85
  pti_messages_received = 34
  pti_syscalls_mach = 191
  pti_syscalls_unix = 974
  pti_csw = 692
  pti_threadnum = 1
  pti_numrunning = 1
  pti_priority = 31
}
(uint64_t) diff = 59649191
(lldb) p proc->utime
(uint64_t) $10 = 1165926740
(lldb) p proc->stime
(uint64_t) $11 = 3830955
(lldb) p dpl->super.cpuCount
(int) $12 = 8
(lldb) p dpl->global_diff
(uint64_t) $13 = 1846
(lldb)
```

**Comment by BenBE** [comment]
Now for some somewhat more complicated info from `darwin/DarwinProcessList.c` lines 181ff. The values read from `dpl->curr_load[i].cpu_ticks[j]` (maybe add delta to previous value via `dpl->prev_load[i].cpu_ticks[j]`, but that's bonus). That's a 2D array for each CPU core (should be 8) reporting 4 values each (`CPU_STATE_USER`, `CPU_STATE_NICE`, `CPU_STATE_SYSTEM`, `CPU_STATE_IDLE`).

Code links from Apple kernel source:
* https://opensource.apple.com/source/xnu/xnu-344/osfmk/mach/host_info.h.auto.html
* https://opensource.apple.com/source/xnu/xnu-344.2/osfmk/kern/host.c.auto.html

For these values the sum per core and overall sum would be of interest; possibly in a short time series again.

What I noticed so far is that the values reported by `diff` shouldn't need scaling. So something strange is going on.

**Comment by cfstras** [comment]
okay, that's a lot of data... raw cur values, with the diff in parens.
let me know if I should plot it ;)

| cpu | user | system | idle | nice |
| --- | --- | --- | --- | --- | 
| 0 | 876732 (0) | 359645 (0) | 2348612 (0) | 0 (0) |
| 1 | 841369 (0) | 328608 (0) | 2414875 (0) | 0 (0) |
| 2 | 555564 (0) | 247032 (0) | 2782254 (0) | 0 (0) |
| 3 | 284090 (0) | 204157 (0) | 3096601 (0) | 0 (0) |
| 4 | 770124 (0) | 286285 (0) | 2528442 (0) | 0 (0) |
| 5 | 355918 (0) | 256112 (0) | 2972819 (0) | 0 (0) |
| 6 | 577006 (0) | 383940 (0) | 2623903 (0) | 0 (0) |
| 7 | 453616 (0) | 312696 (0) | 2818536 (0) | 0 (0) |
| 0 | 876733 (1) | 359645 (0) | 2348620 (8) | 0 (0) |
| 1 | 841369 (0) | 328608 (0) | 2414883 (8) | 0 (0) |
| 2 | 555565 (1) | 247032 (0) | 2782263 (9) | 0 (0) |
| 3 | 284092 (2) | 204158 (1) | 3096607 (6) | 0 (0) |
| 4 | 770124 (0) | 286286 (1) | 2528451 (9) | 0 (0) |
| 5 | 355918 (0) | 256112 (0) | 2972828 (9) | 0 (0) |
| 6 | 577012 (6) | 383940 (0) | 2623906 (3) | 0 (0) |
| 7 | 453618 (2) | 312697 (1) | 2818543 (7) | 0 (0) |
| 0 | 876733 (0) | 359645 (0) | 2348620 (0) | 0 (0) |
| 1 | 841370 (1) | 328608 (0) | 2414884 (1) | 0 (0) |
| 2 | 555565 (0) | 247032 (0) | 2782263 (0) | 0 (0) |
| 3 | 284092 (0) | 204158 (0) | 3096607 (0) | 0 (0) |
| 4 | 770124 (0) | 286286 (0) | 2528451 (0) | 0 (0) |
| 5 | 355918 (0) | 256112 (0) | 2972828 (0) | 0 (0) |
| 6 | 577012 (0) | 383940 (0) | 2623906 (0) | 0 (0) |
| 7 | 453618 (0) | 312697 (0) | 2818543 (0) | 0 (0) |
| 0 | 876740 (7) | 359650 (5) | 2348758 (138) | 0 (0) |
| 1 | 841375 (5) | 328612 (4) | 2415025 (141) | 0 (0) |
| 2 | 555568 (3) | 247037 (5) | 2782406 (143) | 0 (0) |
| 3 | 284182 (90) | 204158 (0) | 3096668 (61) | 0 (0) |
| 4 | 770130 (6) | 286289 (3) | 2528592 (141) | 0 (0) |
| 5 | 355968 (50) | 256112 (0) | 2972928 (100) | 0 (0) |
| 6 | 577017 (5) | 383941 (1) | 2624052 (146) | 0 (0) |
| 7 | 453633 (15) | 312697 (0) | 2818679 (136) | 0 (0) |
| 0 | 876745 (5) | 359654 (4) | 2348901 (143) | 0 (0) |
| 1 | 841378 (3) | 328616 (4) | 2415169 (144) | 0 (0) |
| 2 | 555570 (2) | 247040 (3) | 2782551 (145) | 0 (0) |
| 3 | 284184 (2) | 204159 (1) | 3096817 (149) | 0 (0) |
| 4 | 770133 (3) | 286292 (3) | 2528737 (145) | 0 (0) |
| 5 | 356072 (104) | 256113 (1) | 2972974 (46) | 0 (0) |
| 6 | 577067 (50) | 383942 (1) | 2624151 (99) | 0 (0) |
| 7 | 453637 (4) | 312697 (0) | 2818826 (147) | 0 (0) |
| 0 | 876752 (7) | 359674 (20) | 2349024 (123) | 0 (0) |
| 1 | 841384 (6) | 328630 (14) | 2415299 (130) | 0 (0) |
| 2 | 555575 (5) | 247048 (8) | 2782689 (138) | 0 (0) |
| 3 | 284185 (1) | 204159 (0) | 3096966 (149) | 0 (0) |
| 4 | 770139 (6) | 286314 (22) | 2528861 (124) | 0 (0) |
| 5 | 356113 (41) | 256113 (0) | 2973084 (110) | 0 (0) |
| 6 | 577137 (70) | 383944 (2) | 2624229 (78) | 0 (0) |
| 7 | 453677 (40) | 312698 (1) | 2818936 (110) | 0 (0) |
| 0 | 876760 (8) | 359681 (7) | 2349160 (136) | 0 (0) |
| 1 | 841397 (13) | 328637 (7) | 2415430 (131) | 0 (0) |
| 2 | 555582 (7) | 247053 (5) | 2782828 (139) | 0 (0) |
| 3 | 284203 (18) | 204160 (1) | 3097098 (132) | 0 (0) |
| 4 | 770145 (6) | 286318 (4) | 2529000 (139) | 0 (0) |
| 5 | 356113 (0) | 256113 (0) | 2973234 (150) | 0 (0) |
| 6 | 577270 (133) | 383944 (0) | 2624247 (18) | 0 (0) |
| 7 | 453678 (1) | 312698 (0) | 2819085 (149) | 0 (0) |

**Comment by amomchilov** [comment]
M1 mac people: could you please test a hunch of ours and tell us what this prints?

```
#include <stdio.h>
#include <unistd.h>

int main(int argc, char *argv[]) {
	printf("%li", sysconf(_SC_CLK_TCK));
}
```

**Comment by cfstras** [comment]
It prints 100 (MacBookAir10,1)

**Comment by dghost** [comment]
I have no idea if this is the cause or not, but I figure it's worth pointing out that on M1 the mach native timer resolution is not in nanoseconds, as documented on the [arch difference guide](https://developer.apple.com/documentation/apple_silicon/addressing_architectural_differences_in_your_macos_code?language=objc) under the section "Apply Timebase Information to Mach Absolute Time Values".

Putting together [a test based on their sample](https://gist.github.com/dghost/a937f621ff1f5c74c32996867a22a63d) I was able to get the values:
```
sTimebase.numer == 125
sTimebase.denom == 3
```
which would imply that the tick count need to be multiplied by ~41.67x to get nanoseconds.

Changing DarwinProcess.c:252 to:
`         proc->super.percent_cpu = ((double)diff * (double)dpl->super.cpuCount * 125.0f)
                                 / ((double)dpl->global_diff * 100000.0 * 3.0f);`

Seems to give significantly more reasonable results, at least on an M1.

**Comment by BenBE** [comment]
A factor of about 40 also matches with the data given by @cfstras …

@dghost Since when is that API available on MacOS? Or has this newly been introduced recently?

**Comment by dghost** [comment]
Not sure, but anecdotally it seems to have been around on iOS [since at least 2008](https://shiftedbits.org/2008/10/01/mach_absolute_time-on-the-iphone/).

Poking through Apple’s OSS repository, it looks like mach_time.h has always been exposed by the XNU kernel - the [oldest version I could find](https://opensource.apple.com/source/xnu/xnu-123.5/osfmk/mach/mach_time.h.auto.html) was XNU 123.5, which was part of the OS X 10.0 source drop.

If I had to wager, it’s plausible that it is something that was inherited from NextStep or even Mach.

**Comment by BenBE** [comment]
@dghost @sfzhu93 @amomchilov Please test the patch from PR #392.

**Comment by sfzhu93** [comment]
Awesome! Fixed! 👏👏
<img width="1383" alt="Screen Shot 2020-12-12 at 7 49 28 PM" src="https://user-images.githubusercontent.com/42506672/102000230-53f04580-3cb3-11eb-9d96-5d3d883b9fb4.png">

**Comment by dghost** [comment]
Looks good over here, too. Thanks!

**Comment by abarisain** [comment]
Hi

Unfortunately, https://github.com/htop-dev/htop/commit/67ccd6b909d28ab84c77acecdfee927337489cc2#diff-0727e42f7b2afa9bc833822503fccef2634abaa37969a17822bad775fbad1e60 broke the fix.
Building the parent commit gives accurate CPU% on M1, but not this one.

**Comment by fasterit** [comment]
Regression on Apple M1 hardware

**Comment by cgzones** [comment]
According to the math, there should be no change:

Previous:
```
proc->super.percent_cpu = (double)diff * (double)dpl->super.cpuCount * Platform_timebaseToNS / ((double)dpl->global_diff * 100000.0);

with:

diff = (pti.pti_total_system - proc->stime) + (pti.pti_total_user - proc->utime);

simplifies to:

proc->super.percent_cpu = (pti.pti_total_system + pti.pti_total_user - proc->stime - proc->utime) * dpl->super.cpuCount * Platform_timebaseToNS / (dpl->global_diff * 100000.0);

proc->super.percent_cpu = (pti.pti_total_system + pti.pti_total_user - proc->stime - proc->utime) * dpl->super.cpuCount * Platform_timebaseToNS / dpl->global_diff / 100000.0;
```

After:
```
proc->super.percent_cpu = ((double)total_time_diff / time_interval) * 100.0;

with:

total_time_diff = total_current_time - total_existing_time;
total_existing_time = proc->stime + proc->utime;
total_current_time = pti.pti_total_system + pti.pti_total_user;

time_interval = ticksToNanoseconds(dpl->global_diff) / (double) dpl->super.cpuCount;

static double ticksToNanoseconds(const double ticks) {
   const double nanos_per_sec = 1e9;
   return ticks / (double) Platform_clockTicksPerSec * Platform_timebaseToNS * nanos_per_sec;
}

simplifies to:

proc->super.percent_cpu = ((pti.pti_total_system + pti.pti_total_user - proc->stime - proc->utime) / ((dpl->global_diff / Platform_clockTicksPerSec * Platform_timebaseToNS * 1e9) / dpl->super.cpuCount)) * 100.0;

proc->super.percent_cpu = (pti.pti_total_system + pti.pti_total_user - proc->stime - proc->utime) / (dpl->global_diff / Platform_clockTicksPerSec * Platform_timebaseToNS * 1e9 / dpl->super.cpuCount) * 100.0;

proc->super.percent_cpu = (pti.pti_total_system + pti.pti_total_user - proc->stime - proc->utime) / dpl->global_diff * Platform_clockTicksPerSec / Platform_timebaseToNS / 1e9 * dpl->super.cpuCount * 100.0;
```

DIfference:
```
1 / 1e5
vs    
Platform_clockTicksPerSec / 1e7
```


But maybe adjusting the timebase via `Platform_timebaseToNS` and adjusting the ticks via `Platform_clockTicksPerSec` is the same done twice?

Can someone try to replace either `Platform_timebaseToNS` with `1.0` or  `Platform_clockTicksPerSec` with `100` at
https://github.com/htop-dev/htop/blob/0672be7db1ed50fceff0619e1411b510aa11f0f7/darwin/DarwinProcessList.c#L164

**Comment by BenBE** [comment]
@abarisain 
> Unfortunately, [67ccd6b](https://github.com/htop-dev/htop/commit/67ccd6b909d28ab84c77acecdfee927337489cc2#diff-0727e42f7b2afa9bc833822503fccef2634abaa37969a17822bad775fbad1e60) broke the fix.
> Building the parent commit gives accurate CPU% on M1, but not this one.
> 

Can you give a rough factor by which things are off? Do the changes suggested by @cgzones help?

**Comment by abarisain** [comment]
Thanks for the fast answer

Things are way off, almost always around 0. Not pictured: the working htop as it reports ~ the same as Activity monitor

![Screenshot 2020-12-22 at 21 07 13 1](https://user-images.githubusercontent.com/312529/102929309-a0e5d000-449a-11eb-92cf-2cc205ca4dc2.png)


>Can someone try to replace either Platform_timebaseToNS with 1.0 or Platform_clockTicksPerSec with 100 at

So, 
`return ticks / (double) 100 * 1.0 * nanos_per_sec; `
do I need to tweak this elsewhere?

![Screenshot 2020-12-22 at 21 12 06](https://user-images.githubusercontent.com/312529/102929356-beb33500-449a-11eb-8c3e-899a90730760.png)

**Comment by BenBE** [comment]
Okay, that's a factor of 125/3 (~42) to small in htop, which means the Ticks2Nano scaling is applied twice.

NB: The 125/3 is what we previously determined to be the scaling factor returned by the MacOS API for M1).

When replacing the values for testing, its just that one location that @cgzones mentioned; it's quite centralized in the code.
The only other location those values are touched (read) are in `Platform_init`, but they should be good there.

**Comment by cgzones** [comment]
> So,
return ticks / (double) 100 * 1.0 * nanos_per_sec;
do I need to tweak this elsewhere?

Can you test replacing one (not both) values?

**Comment by dghost** [comment]
Not to add noise to the signal, but it looks like the calculated cpu percentage is off by a factor of ~1700-1800. By dumping the values of total_time_diff, time_interval, and calculated percentage for a process stuck in a busy loop:

```
      if (total_existing_time && 1E-6 < time_interval) {
         uint64_t total_time_diff = total_current_time - total_existing_time;
         proc->super.percent_cpu = ((double)total_time_diff / time_interval) * 100.0;
         if (proc->super.pid == XXYYZZ)
         {
            fprintf(stderr, "%llu %f %f\n", total_time_diff, time_interval, proc->super.percent_cpu);
         }
      } else {
```
I got:
`
total_time_diff=36160668 time_interval=62968749999.999992 proc->super.percent_cpu=0.057426
`

Some code on an intel system gives:
`
total_time_diff=2139967964 time_interval=2138214285.714286 proc->super.percent_cpu=100.082016
`

**Comment by dghost** [comment]
I haven't gone through the math so it is probably wrong, but this seems give much more accurate results:
```
static double ticksToNanoseconds(const double ticks) {
   const double nanos_per_sec = 1e9;
   return (ticks / Platform_timebaseToNS) * (nanos_per_sec / (double) Platform_clockTicksPerSec);
}
```

**Comment by abarisain** [comment]
>Can you test replacing one (not both) values?

results aren't great. Replacing Platform_clockTicksPerSec doesn't fix anything. Platform_timebaseToNS improves it a lot but still way wrong

dghost's solution works wonders

**Comment by dghost** [comment]
Just got around to looking at this again (sorry, holidays and all) and I'm pretty sure I see what the problem is. Specifically, during the simplification listed above:

```
proc->super.percent_cpu = (pti.pti_total_system + pti.pti_total_user - proc->stime - proc->utime) / (dpl->global_diff / Platform_clockTicksPerSec * Platform_timebaseToNS * 1e9 / dpl->super.cpuCount) * 100.0;
 
proc->super.percent_cpu = (pti.pti_total_system + pti.pti_total_user - proc->stime - proc->utime) / dpl->global_diff * Platform_clockTicksPerSec / Platform_timebaseToNS / 1e9 * dpl->super.cpuCount * 100.0;
```

This simplification confuses the order of operations of `(dpl->global_diff / Platform_clockTicksPerSec * Platform_timebaseToNS * 1e9 / dpl->super.cpuCount)`, and treats it as if it was a equivalent to `(dpl->global_diff / (Platform_clockTicksPerSec * Platform_timebaseToNS * 1e9) / dpl->super.cpuCount)`. 

A more correct simplification of it would be:

```
proc->super.percent_cpu = (pti.pti_total_system + pti.pti_total_user - proc->stime - proc->utime) / (dpl->global_diff / Platform_clockTicksPerSec * Platform_timebaseToNS * 1e9 / dpl->super.cpuCount) * 100.0;

proc->super.percent_cpu = (pti.pti_total_system + pti.pti_total_user - proc->stime - proc->utime) / ((dpl->global_diff * Platform_timebaseToNS * 1e9) / (Platform_clockTicksPerSec * dpl->super.cpuCount)) * 100.0;

proc->super.percent_cpu = (pti.pti_total_system + pti.pti_total_user - proc->stime - proc->utime) / (dpl->global_diff * Platform_timebaseToNS * 1e9) * (Platform_clockTicksPerSec * dpl->super.cpuCount) * 100.0;
```
Which, when re-ordered to appear like the original source code, shows that it is being divided by Platform_timebaseToNS instead of multiplied:
```
proc->super.percent_cpu = (pti.pti_total_system + pti.pti_total_user - proc->stime - proc->utime) * (Platform_clockTicksPerSec * dpl->super.cpuCount) / (dpl->global_diff * Platform_timebaseToNS * 1e9) * 100.0;
```

This explains the magic number of ~1741 - because it wound up dividing instead of multiplying, the resulting value was `(Platform_timebaseToNS^2)` away from expected - or, in this case, (125/3)^2 ~= 1,736.11111

**Comment by cgzones** [comment]
Oops. :facepalm: 
In my [previous analysis](https://github.com/htop-dev/htop/issues/368#issuecomment-749668716) I came to the correct result:
previous
```
proc->super.percent_cpu = (pti.pti_total_system + pti.pti_total_user - proc->stime - proc->utime) * dpl->super.cpuCount * Platform_timebaseToNS / dpl->global_diff / 100000.0;
```
now
```
proc->super.percent_cpu = (pti.pti_total_system + pti.pti_total_user - proc->stime - proc->utime) / dpl->global_diff * Platform_clockTicksPerSec / Platform_timebaseToNS / 1e9 * dpl->super.cpuCount * 100.0;
```
but I wrongly concluded the difference.

The difference is *obviously* not
```
1 / 1e5
vs    
Platform_clockTicksPerSec / 1e7
```
, but
```
Platform_timebaseToNS / 1e5
vs
Platform_clockTicksPerSec / Platform_timebaseToNS / 1e7
```

**Comment by donalod** [comment]
Seems to be dramatically under-reporting memory also, anyone else? M1, BigSur, brew installed htop 3.0.5. 
![image](https://user-images.githubusercontent.com/4045949/114389195-9c017500-9b8c-11eb-83f7-a6af59be2cb9.png)

**Comment by BenBE** [comment]
> Seems to be dramatically under-reporting memory also, anyone else? M1, BigSur, brew installed htop 3.0.5.

Chrome is one of those programs that heavily fork and share memory across processes. The memory meter is based on the information in `/proc/meminfo`. Simply adding the values from the `RES` or even `VIRT` columns will yield wildly incorrect calculations as part of the usage reported there might be shared or even swapped.

**Comment by donalod** [comment]
> Chrome is one of those programs that heavily fork and share memory across processes. The memory meter is based on the information in `/proc/meminfo`. Simply adding the values from the `RES` or even `VIRT` columns will yield wildly incorrect calculations as part of the usage reported there might be shared or even swapped.

Gotcha but on OSX `file /proc/meminfo` gives `/proc/meminfo: cannot open `/proc/meminfo' (No such file or directory)`
as per `sw_vers` -> `ProductName:	macOS
ProductVersion:	11.2
BuildVersion:	20D64` so even with "Real Mem" column on, the reported values in activity monitor don't change, so am wondering where the `darwin` version of htop grabs its info? 
![image](https://user-images.githubusercontent.com/4045949/114397206-547fe680-9b96-11eb-8249-f269c193f907.png)

**Comment by BenBE** [comment]
> > Chrome is one of those programs that heavily fork and share memory across processes. The memory meter is based on the information in `/proc/meminfo`. Simply adding the values from the `RES` or even `VIRT` columns will yield wildly incorrect calculations as part of the usage reported there might be shared or even swapped.
> 
> Gotcha but on OSX `file /proc/meminfo` gives `/proc/meminfo: cannot open /proc/meminfo (No such file or directory)`
> as per `sw_vers` -> `ProductName: macOS ProductVersion: 11.2 BuildVersion: 20D64` so even with "Real Mem" column on, the reported values in activity monitor don't change, so am wondering where the `darwin` version of htop grabs its info?

https://github.com/htop-dev/htop/blob/f3d9ecaa626f2f9124f5c53b083511572ef47a66/darwin/DarwinProcessList.c#L99-L105

https://github.com/htop-dev/htop/blob/f3d9ecaa626f2f9124f5c53b083511572ef47a66/darwin/Platform.c#L240-L251

Fields `active_count`, `wire_count`, `purgeable_count`, and `inactive_count`.
