### ISSUE TITLE
linux/LinuxProcessList.c:889:16: warning: ‘pathBuffer’ is used uninitialized [-Wuninitialized]

### ISSUE THREAD

**Issue by marxin** [htop-dev/htop#369]
I see the following warning when building htop with `GCC 11.0`:

```
linux/LinuxProcessList.c: In function ‘LinuxProcessList_readCwd’:
linux/LinuxProcessList.c:889:16: warning: ‘pathBuffer’ is used uninitialized [-Wuninitialized]
  889 |    ssize_t r = readlinkat(procFd, "cwd", pathBuffer, sizeof(pathBuffer) - 1);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./Compat.h:14,
                 from ./XUtils.h:17,
                 from ./Object.h:16,
                 from ./ProcessList.h:16,
                 from linux/LinuxProcessList.h:16,
                 from linux/LinuxProcessList.c:10:
/usr/include/unistd.h:832:16: note: in a call to ‘readlinkat’ declared with attribute ‘access (read_only, 3, 4)’ here
  832 | extern ssize_t readlinkat (int __fd, const char *__restrict __path,
      |                ^~~~~~~~~~
linux/LinuxProcessList.c:886:9: note: ‘pathBuffer’ declared here
  886 |    char pathBuffer[PATH_MAX + 1];
      |         ^~~~~~~~~~
```

**Comment by cgzones** [comment]
For me this looks like a bug in the standard C library:
[readlinkat(**2**)](https://manpages.debian.org/unstable/manpages-dev/readlinkat.2.en.html) **writes** to its third argument, but the `access` attribute states `read_only`.

**Comment by BenBE** [comment]
ACK on that. Noticed this issue too.

But as this isn't on a critical path IMHO (we have a few much tighter loops in the code) it's not too much of a problem, to just initialize the buffer.

@cgzones: Do you know if there's an upstream report of this issue somewhere?

**Comment by cgzones** [comment]
I did a quick search in the gcc and glibc bug database, but nothing related found.
@marxin what libc are you using?

**Comment by marxin** [comment]
I'm using the latest Glibc release and yes, it's really a bug in it:
https://sourceware.org/bugzilla/show_bug.cgi?id=27024
