### ISSUE TITLE
Incorrect rendering of tree view

### ISSUE THREAD

**Issue by hishamhm** [htop-dev/htop#375]
Hi there! Having fun poking around and discovering new htop features as an end-user for the first time. :)

I was clicking around playing with the new behavior where tree view can get sorted by different columns, and ended up putting it in a state where the tree gets rendered incorrectly: (note the inverted tree lines)

![image](https://user-images.githubusercontent.com/245621/101530207-5def0d00-3970-11eb-9e40-c9e4e7148c14.png)

This is the `~/.config/htop/htoprc` corresponding to that behavior:

```
# Beware! This file is rewritten by htop when settings are changed in the interface.
# The parser is also very primitive, and not human-friendly.
fields=0 48 17 18 38 39 40 2 46 47 49 1
sort_key=46
sort_direction=-1
hide_kernel_threads=1
hide_userland_threads=0
shadow_other_users=0
show_thread_names=1
show_program_path=1
highlight_base_name=0
highlight_megabytes=0
highlight_threads=1
highlight_changes=0
highlight_changes_delay_secs=5
find_comm_in_cmdline=0
strip_exe_from_cmdline=0
show_merged_command=0
tree_view=1
header_margin=1
detailed_cpu_time=1
cpu_count_from_one=1
show_cpu_usage=1
show_cpu_frequency=1
update_process_names=1
account_guest_in_cpu_meter=0
color_scheme=0
enable_mouse=1
delay=15
left_meters=AllCPUs Memory Swap
left_meter_modes=1 1 1
right_meters=Tasks LoadAverage Uptime Battery
right_meter_modes=2 2 2 2
```

**Comment by fasterit** [comment]
\o/ Hisham
Can nicely be reproduced with your .htoprc, thanks

**Comment by hishamhm** [comment]
Yay, thank you!
