### ISSUE TITLE
How to specify fields for a specific invocation of htop?

### ISSUE THREAD

**Issue by svenha** [htop-dev/htop#380]
I would like to specify special `fields` settings for invocations of `htop` without touching the main `htoprc`. Some ideas how this can be achieved (in order of my preference):

1. a command line option -f (--fields)
1. several (partial) config files (later ones overwriting earlier ones in case of conflicts)
1. combining htoprc parts in a script before invoking htop
1. ...

**Comment by fasterit** [comment]
Configure a `htop` how you would like it to start, copy the resulting `.config/htop/htoprc` somewhere and
run `HTOPRC=some/where/htoprc htop` and it will start as configure in that `htoprc` file

**Comment by svenha** [comment]
Thanks @fasterit I worked with a similar approach, but the problem is that I want to share the `fields` setting; the other settings are host-dependent and I have to manage a pool of >20 diverse servers.

**Comment by fasterit** [comment]
`sed -i "s/^fields=.*/fields=0 48 17 18 38 39 40 2 46 47 49 1/" ~/.config/htop/htoprc && htop`

You can put that in a script or in your systems management (ansible, salt, etc.)

**Comment by svenha** [comment]
Excellent.
