### ISSUE TITLE
3.0.2 -> 3.0.3 bug: Each refresh when using tree view is showing the root elements in different order

### ISSUE THREAD

**Issue by milosivanovic** [htop-dev/htop#382]
Prior to version 3.0.3, tree view would show the process tree in a consistent order after each refresh / interval period. Now what's happening is each time the htop output refreshes, it shows all the root elements of the process tree in a different order. Every 1.5 seconds the output is basically randomised. This is a bug.

Init [1] is always at the top though.

**Comment by BenBE** [comment]
The tree view is sorted by default. This default normally is carried over from the non-tree mode, thus is based on the CPU time. Try pressing <kbd>F6</kbd> and selecting something else like PID as the column to sort by. The tree should then become much more stable.

When sorting by columns that basically show the same value this doesn't help much though, thus additional sorting by PID might be required to get the order of entries stable.

**Comment by fasterit** [comment]
Typically the best way to archive this is to sort by PID first and then use a stable sorting algorithm (so not our plain quick sort) to sort by the desired column.

**Comment by BenBE** [comment]
I already thought of something like modifying our compare function to use the PID as tie-breaker internally. Just didn't manage to write some code for it …

**Comment by BenBE** [comment]
Should be fixed by the tie-breaker patch introduced in #411.
