### ISSUE TITLE
Feature request: Linux: Improving Command display/sort

### ISSUE THREAD

**Issue by gnarendran** [htop-dev/htop#40]
Ref: Issue https://github.com/hishamhm/htop/issues/801 and pull request https://github.com/hishamhm/htop/pull/809

Summary:
I) On Linux a process is able to modify its own command name (/proc/pid/comm) say using prctl, and its own command line (/proc/pid/cmdline) say by writing into its arguments vector. But /proc/pid/exe is set by the kernel and provides the definitive location of the executable image. While htop currently displays cmdline, for the above reason it is desirable to display the executable image path and command name, along with cmdline, merging them where possible.

II) While htop currently sorts/filters the Command based always on cmdline, irrespective of whether it is full path or basename that is displayed, it is desirable to sort/filter based on what is displayed.

**Comment by BenBE** [comment]
Implemented by #305 based on your work in #42.
