### ISSUE TITLE
checkbox: poorly displayed in settings

### ISSUE THREAD

**Issue by Izorkin** [htop-dev/htop#41]
After this commit - https://github.com/htop-dev/htop/commit/d0f31ede5624ed2f35ca25043f6a28adfe3bc171 сheckboxes are poorly displayed in the program settings.

![kitty_2020-08-30_10-10-35](https://user-images.githubusercontent.com/26877687/91653527-6ea70180-eaaa-11ea-93ef-48c0e149dae9.png)

**Comment by rien333** [comment]
Duplicate of https://github.com/htop-dev/htop/issues/29, perhaps?  Also should be fixed with https://github.com/htop-dev/htop/pull/39

**Comment by Izorkin** [comment]
Yes, the patch works.

![kitty_2020-08-30_11-52-12](https://user-images.githubusercontent.com/26877687/91655201-a7010c80-eab7-11ea-9155-7fe4170c4a80.png)
