### ISSUE TITLE
Frequency and temperature in Freebsd

### ISSUE THREAD

**Issue by timsofteng** [htop-dev/htop#419]
Hello. How can I enable frequency and temperature monitor in freebsd?
I set frequency in menu (F2) but it's not displayed.

![image](https://user-images.githubusercontent.com/51912173/102883511-cfdb5200-4458-11eb-9bfa-316d75264267.png)

**Comment by fasterit** [comment]
By providing code on how to get that data on FreeBSD cf. https://github.com/htop-dev/htop/blob/master/freebsd/Platform.c#L208-L209

**Comment by timsofteng** [comment]
> By providing code on how to get that data on FreeBSD cf. https://github.com/htop-dev/htop/blob/master/freebsd/Platform.c#L208-L209

I know how to get it in console. 
`sysctl dev.cpu.0.temperature`
`sysctl dev.cpu.0.freq`

0 is core number.

**Comment by fasterit** [comment]
Apparently available via `sysctlbyname()` as per https://lists.freebsd.org/pipermail/freebsd-questions/2011-May/229614.html . Kelvin times ten.

**Comment by timsofteng** [comment]
@fasterit could It be implemented?

**Comment by cgzones** [comment]
Can you give https://github.com/htop-dev/htop/compare/master...cgzones:freebsd?expand=1 a shot?
Sadly frequency and temperature data is not available inside a vm.

**Comment by fasterit** [comment]
@timsofteng ping ^

**Comment by timsofteng** [comment]
@fasterit Thanks for your efforts. Unfortunately I haven't opportunity to test it on freebsd at this time.
Please keep this issue opened and I'll ping you asap.

**Comment by cgzones** [comment]
You can find the current proposal at #436

**Comment by cgzones** [comment]
Implemented by ee97916fd530c82b8747bd90b7d1b98e92f858ae.
