### ISSUE TITLE
Sort column header not highlighted on macOS

### ISSUE THREAD

**Issue by topcat001** [htop-dev/htop#429]
On macOS Catalina 10.15.7, running Homebrew. I updated htop to 3.0.4 and after the update the sort column header is no longer highlighted. Sorting itself works fine. In the attached screenshot, the sort column is Command.
<img width="894" alt="Screen Shot 2020-12-23 at 12 01 51 PM" src="https://user-images.githubusercontent.com/22438522/103033289-fbbd0d00-4516-11eb-951a-c3a0b892c8d9.png">

**Comment by cgzones** [comment]
Should be fixed via https://github.com/htop-dev/htop/commit/86d293125565a15bbd94683080dbc755c5d7edee

**Comment by topcat001** [comment]
Wow, already fixed! Thanks a lot. I'll wait for the next release.

**Comment by BenBE** [comment]
Fixed by #420 …
