### ISSUE TITLE
Display in bars

### ISSUE THREAD

**Issue by neyuru** [htop-dev/htop#432]
Please label this as a feature request.

Currently, htop displays "bars" with information and "ticks" under square brackets, like so (example from CPU core):

1[|||                        1.2% 1800Mhz]

if the the displayed metric is, let's say 95%, the ticks "invade" the space of the information, like so:
------------------100%---------------->
------------ 95%----------------->
1[|||||||||||||||||||||||||||||1.2|||1800Mhz]

It could be great if either:

1) Depending on the information selected, the square brackets shrink to encapsulate only the ticks:
------100%------>
----- 95%----->
1[|||||||||||||||||||||    ] 1.2%  1800Mhz

2) or, the brackets remains the same, but the ticks do not invade the space intended for the info:

------100%------>
----- 95%----->
1[|||||||||||||||||||||    1.2%  1800Mhz]

**Comment by BenBE** [comment]
I don't think this is a good thing to do as the layout is intentionally done in a way to reduce space usage (for e.g. small displays). Also the "invading" also copies attributes to the text, thus even then there's only little space, the full width of the bar can be used to convey information.

**Comment by cgzones** [comment]
In my opinion the design of the Bar Meters is the characteristic feature of htop.
Also I don't see any reason for a change, since the text will be colourized in case it covers the ticks (also in monochromatic colour mode the text gets bold).

**Comment by fasterit** [comment]
Thank you very much @neyuru.
We discussed this feature in the core team meeting and nobody seems interested in stepping up to implement this.
I'll close this issue for now.
