### ISSUE TITLE
htop not display properly if having too many cpu cores

### ISSUE THREAD

**Issue by kocoten1992** [htop-dev/htop#435]
On system with 256 cpu cores, htop not gonna display properly, as seen in https://youtu.be/9MXhGABtuCA?t=705

:christmas_tree: Merry Christmas and Happy New Year :christmas_tree:

**Comment by cgzones** [comment]
There are CPU Meters, which display 8 CPU bars per Meter.
And there is an CPU Average Meter.
I am not sure what exactly to do for huge CPU count systems.

**Comment by BenBE** [comment]
What about switching to a proper multi-meter variant based on CPU count?

**Comment by fasterit** [comment]
We already do a setup based on initialCpuCount, may be that should be extended for > 48 to be defaulting to *CPUs4Meters.
I would not change what people have configure in their htoprc. But initial setup can be improved.
