### ISSUE TITLE
Menu bar 'overwriting' header lines since 3.0.4

### ISSUE THREAD

**Issue by Chris-1101** [htop-dev/htop#439]
There seems to have been a change to the way the menu bar is drawn. Prior to `3.0.4`, collapsing the terminal's height to only include the header would hide the menu bar, in this latest version the menu bar persists, overwriting the header's lines:

##### 3.0.4
![3.0.4](https://user-images.githubusercontent.com/28808441/103245573-e30e8600-4960-11eb-8acf-a85ed0679487.png)

##### 3.0.3
![3.0.3](https://user-images.githubusercontent.com/28808441/103245575-e3a71c80-4960-11eb-8ce4-9c006a3a43c9.png)

Just wondering if this change is intentional or not.

PS: this is on Arch Linux

**Comment by fasterit** [comment]
Yes, this is intentional, the function bar is now properly part of re-drawing the panel, cf. e3862aa67e37ecef0eb8f82ba1f4a710ffac9c02

**Comment by Chris-1101** [comment]
I see, thanks for the reply. I did notice that mentioned in the change log, but I wasn't sure if function bar was the menu bar or not.

Any chance of a setup option to hide the function bar at some point? :sweat_smile:
