### ISSUE TITLE
ZFS_RATIO isn't actually used

### ISSUE THREAD

**Issue by deviant** [htop-dev/htop#456]
`ZFS_RATIO` isn't referenced anywhere in the code (only assigned)~~, and `ZFS_COMPRESSED` doesn't seem to affect anything either. I think this is because the values are formatted with `METER_VALUE`: https://github.com/htop-dev/htop/blob/613556faebd16325da8c9057c81f39a2410d803f/zfs/ZfsCompressedArcMeter.c#L56-L64~~

I'm not familiar enough with the codebase to propose a fix, so I'm opening an issue instead. Tagging @overhacked as the author.

**Edit**: `ZFS_COMPRESSED` is actually used for the bar view (I had no idea that meters could be put into different modes...), but `ZFS_RATIO` still isn't used anywhere.

**Comment by cgzones** [comment]
Probably `ZFS_RATIO` was intended to be used at https://github.com/htop-dev/htop/blob/bfcb8ca0196eef942e6363e2fd7faa80eddec644/zfs/ZfsCompressedArcMeter.c#L57
