### ISSUE TITLE
3.0.2 -> 3.0.3 bug: slow cpufreq on AMD EPYC 7502P (32 cores + SMT)

### ISSUE THREAD

**Issue by KonstantinPlotnikov** [htop-dev/htop#471]
On Arch Linux server with CPU AMD EPYC 7502P (32 cores + SMT):
Usage of the option "Also show CPU frequency" makes htop very slow to launch and very laggy since version 3.0.3.
Using strace -T shows this:
```
openat(AT_FDCWD, "/sys/devices/system/cpu/cpu8/cpufreq/scaling_cur_freq", O_RDONLY) = 4 <0.000025>
fstat(4, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0 <0.000011>
read(4, "3341788\n", 4096)              = 8 <0.016539>
close(4)                                = 0 <0.000023>
```

Downgrading to 3.0.2 or disabling option "Also show CPU frequency" solves issue.

**Comment by BenBE** [comment]
Can you re-test with the current 3.0.5 release? Cf. also, #451 and #467.

**Comment by KonstantinPlotnikov** [comment]
Re-tested on 3.0.5: bug still present.
#467 looks very much alike.

From brief code lookup the key change is https://github.com/htop-dev/htop/commit/edf1b10d2c3fa94c23a23cfc947490cf1ebf66d1

And the reason is that on this machine reading from /sys/devices/system/cpu/cpufreq/policy....../scaling_cur_freq is slow (14.5 ms per core).
My desktop has intel cpu and there are no such problem. I will test it on Ryzen 1600 later if needed (maybe it is Zen-related problem)

[AMD EPYC 7502P.txt](https://github.com/htop-dev/htop/files/5801599/AMD.EPYC.7502P.txt)
[Intell Core i5 8400.txt](https://github.com/htop-dev/htop/files/5801600/Intell.Core.i5.8400.txt)

**Comment by cgzones** [comment]
Some data:

Intel(R) Core(TM) i7-5500U
```
openat(AT_FDCWD, "/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq", O_RDONLY) = 4 <0.000051>
fstat(4, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0 <0.000026>
read(4, "936367\n", 4096)               = 7 <0.000039>
close(4)                                = 0 <0.000029>
openat(AT_FDCWD, "/sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq", O_RDONLY) = 4 <0.000047>
fstat(4, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0 <0.000026>
read(4, "1014093\n", 4096)              = 8 <0.000036>
close(4)                                = 0 <0.000028>
openat(AT_FDCWD, "/sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq", O_RDONLY) = 4 <0.000048>
fstat(4, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0 <0.000025>
mmap(0x621000060000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x621000060000 <0.000051>
read(4, "977251\n", 4096)               = 7 <0.000034>
close(4)                                = 0 <0.000029>
openat(AT_FDCWD, "/sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq", O_RDONLY) = 4 <0.000047>
fstat(4, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0 <0.000025>
read(4, "1056614\n", 4096)              = 8 <0.000054>
close(4)                                = 0 <0.000029>
```

Raspberry PI 3b
```
openat(AT_FDCWD, "/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq", O_RDONLY) = 3 <0.000163>
fstat(3, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0 <0.000059>
read(3, "600000\n", 4096)               = 7 <0.000084>
close(3)                                = 0 <0.000071>
openat(AT_FDCWD, "/sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq", O_RDONLY) = 3 <0.000144>
fstat(3, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0 <0.000058>
read(3, "600000\n", 4096)               = 7 <0.000082>
close(3)                                = 0 <0.000071>
openat(AT_FDCWD, "/sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq", O_RDONLY) = 3 <0.000130>
fstat(3, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0 <0.000058>
read(3, "600000\n", 4096)               = 7 <0.000075>
close(3)                                = 0 <0.000067>
openat(AT_FDCWD, "/sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq", O_RDONLY) = 3 <0.000129>
fstat(3, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0 <0.000057>
read(3, "600000\n", 4096)               = 7 <0.000075>
close(3)                                = 0 <0.000073>
```

So the slowdown seems to come from the AMD CPU driver.

Should we invert the source priority (`/proc/cpuinfo` over `scaling_cur_freq`)?
We could add an option were to get the CPU frequency from (`Also show CPU frequency:  0 - off, 1 - sysfs (portable), 2 - /proc/cpuinfo (fast)`), but that would require user knowledge on what option when to pick.
Also dynamically checking how long the `read(2)` on the `scaling_cur_freq` inode takes and switching on times over 1ms to `/proc/cpuinfo` seems intransparent towards users.

There seems to be no standardisation of the `/proc/cpuinfo` content, see https://manpages.debian.org/unstable/manpages/proc.5.en.html , but reading https://bugzilla.kernel.org/show_bug.cgi?id=197009 it *should* contain the *current* CPU frequency.

**Comment by KonstantinPlotnikov** [comment]
On AMD Ryzen 1600:
```
openat(AT_FDCWD, "/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq", O_RDONLY) = 4 <0.000017>
fstat(4, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0 <0.000007>
read(4, "2982634\n", 4096)              = 8 <0.000013>
close(4)                                = 0 <0.000008>
```

On AMD EPYC 7401P:
```
openat(AT_FDCWD, "/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq", O_RDONLY) = 3 <0.000027>
fstat(3, {st_mode=S_IFREG|0444, st_size=4096, ...}) = 0 <0.000009>
read(3, "1197546\n", 4096)              = 8 <0.015645>
close(3)                                = 0 <0.000024>
```

Both CPU are Zen microarchitecture (first generation), but Ryzen 1600 does not have this issue.

**Comment by fasterit** [comment]
@KonstantinPlotnikov what is the cpufreq driver on each of these systems?
`LANG=C cpufreq-info  | grep driver` will show.

**Comment by clain-kp** [comment]
Some summary from me:

CPU|freq read time|driver
-|-|-
AMD Ryzen 5 1600|0.000013|acpi-cpufreq
AMD Ryzen 5 3600|0.014631|acpi-cpufreq
AMD Ryzen 9 3900|0.017195|acpi-cpufreq
AMD EPYC 7401P|0.015645|acpi-cpufreq
AMD EPYC 7502P|0.013563|acpi-cpufreq
Intell Core i5 8400|0.000010|intel_pstate
Intel Xeon E3-1271 v3|0.015697|intel_cpufreq
Intel Xeon E3-1275 v6|0.016941|intel_pstate

So time to read does not depend on driver in use.

**Comment by fasterit** [comment]
Thank you @clain-kp. So it is either ~15ms or near 0ms.

It would be interesting to see what causes the difference and whether we can do something about it from htop-side.

Updating the cpufreq only every N updates seem useless as users will want to see the cpufreq governor reacting to load changes.
#469 will separate data acquisition and display, that's probably the best we can do while we have these runtimes without taking out really big hammers (promises ~ queue updates by expected turn-around times).

**Comment by KonstantinPlotnikov** [comment]
It was me, I posted from work account by mistake.
Separate data acquisition and display is not as good solution as it seems.
For example on system with 32 cores with SMT it would be 32*2*0.015 = 0.96 sec for one round to update.
On top AMD CPU with 128 cores (+SMT) it would require ~4(!) seconds. So collected data would be outdated.

I think best decision is to test timeout at runtime and fallback to /proc/cpuinfo (as proposed by @cgzones)

**Comment by BenBE** [comment]
@fasterit Depending how recent the kernel is, it might be worth looking into scheduling IO via io_uring or some other async I/O interface. Just asking the kernel to read that info and react to it, once the information is there. Would still be polling, but would be completely in the background. Might be an approach for #469 to put it even more into the background.

**Comment by cgzones** [comment]
@KonstantinPlotnikov could you take a look at #478 if its solves the issue for you?

**Comment by KonstantinPlotnikov** [comment]
#478 completely solves issue #471 for me. Thank you!

**Comment by hurryman2212** [comment]
With htop v3.0.5 (from ubuntu official apt repository) and 5.18.0 kernel on AMD 5900X, this problem is still persistent when enabling clock rate option. Is it because the binary from apt repo. not configured with above patch, or is it due to #748 or #768?
