### ISSUE TITLE
Memory reporting drastically changed starting with 3.0.3

### ISSUE THREAD

**Issue by lancethepants** [htop-dev/htop#474]
I noticed after compiling htop 3.0.5 that memory usage reporting was way off compared to the system supplied htop (htop 2.2.0 Debian 10). Going back in time compiling older versions I see the change happens in 3.0.3.

For example right now on my machine.
<=3.0.2        7.55G memory
\>=3.0.3        3.00G memory
So with later versions it is reporting less than half of what it did previously

Is this a bug or by design?

**Comment by lancethepants** [comment]
I've seen mention of zfs in some commits,  The difference between the two is about the size of arc that zfs is taking up.  So did 3.0.3 decide to show memory usage excluding zfs arc size?

**Comment by cgzones** [comment]
Since you are using Debian, I assume you are using Linux?
Are the memory amounts of `3.00G` and `7.55G` values for total or used memory?

(For reference: commit dfa40ad0ebdb40a859ea16a264e775ce766bb037 changed the calculation when using zfs)

**Comment by lancethepants** [comment]
Ok, that explains things. I see they have an arc bar that can be added too.
Thanks a bunch!
