### ISSUE TITLE
Architecture + uname + LSB meter

### ISSUE THREAD

**Issue by BenBE** [htop-dev/htop#480]
I find myself regularly in need of knowing the information provided in `uname -a` in particular the running kernel's version and architecture for a system. As we already have similar "static meters" for the current hostname it would be fitting to have a similar meter to show the mentioned information of running kernel type/version, LSB release, and architecture.

An example meter may look like:
`System: GNU/Linux 5.10.7-1-generic [amd64] / Ubuntu 20.04 [focal]`

If the LSB part can't be read, just skip it:
`System: GNU/Linux 5.10.7-1-generic [amd64]`

**Comment by ahgamut** [comment]
I'd like to try this using the [`utsname`](https://man7.org/linux/man-pages/man2/uname.2.html) struct.

Can someone assign this issue to me?

**Comment by fasterit** [comment]
@ahgamut done. Good luck.

**Comment by ahgamut** [comment]
Thanks! I've submitted a PR (#493).
