### ISSUE TITLE
Let Memory [Text] span both columns

### ISSUE THREAD

**Issue by edrozenberg** [htop-dev/htop#484]
Recent changes have caused the `Memory [Text]` meter to no longer be able to span both columns when the second column has empty space. As a result I'm no longer able to see the cache value in a standard 80 column terminal. `Memory [LED]` can span both columns but I prefer to use `Memory [Text]`.

<img width="479" alt="Mem Text Does Not Fit" src="https://user-images.githubusercontent.com/2648417/104857046-b946e000-58ca-11eb-9e86-4798533ba14c.png">

Sug: let the `Memory [Text]` span the entire width when the second column is empty.

**Comment by BenBE** [comment]
This might be addressed by #445 …

**Comment by edrozenberg** [comment]
Thanks will give it a try when 3.0.6 releases.
