### ISSUE TITLE
HTOP keeps resetting "Tree view" setting randomly

### ISSUE THREAD

**Issue by schuelermine** [htop-dev/htop#504]
I have it enabled, but every now and then, it just gets disabled for some reason.

**Comment by fasterit** [comment]
Does that happen when you press the 't' key?
Or when you delete ~/.config/htoprc?

**Comment by schuelermine** [comment]
That's a possibility. I may have accidentally pressed "T". I didn't know the shortcut existed. Thanks.
Will file again if the issue persists.
