### ISSUE TITLE
'Prev' key binding for search doesn't work

### ISSUE THREAD

**Issue by krotera** [htop-dev/htop#508]
Activate search with `F3`. Type in some string to get some matches. 

Hit `F3` ('Next') to go down the process list. 

'Prev' is labeled `S-F3`, which presumably means `Shift+F3`. But hitting `Shift+F3` exits search, even when there were previous matches.

**Comment by fasterit** [comment]
This - of course - works for the terminals we tested on.

Which version of htop do you run, what is your distro, desktop environment and terminal?
What is your `TERM`environment variable?

I suspect your Shift-F3 sends an ESC and then something.

**Comment by krotera** [comment]
`htop 3.0.5`

`Manjaro 20.2.1 Nibia (kernel 5.4.89-1-MANJARO)`

`KDE 5.78.0 / Plasma 5.20.5`

`konsole 20.12.1`

```
$ echo $TERM
xterm-256color
```
