### ISSUE TITLE
please enhance or fix htop to ignore or use the mouse; currently, messes up tree display

### ISSUE THREAD

**Issue by Astara** [htop-dev/htop#509]
I don't know if this is fixed in a newer version -- haven't been able to try one due to missing libraries to build new one last I tried.  This is in htop:2.2.0 from/on opensuse Tumbleweed (rolling release)

Mouse clicks + movements are not ignored when htop switches the screen mode.  I'm too used to interfaces on my desktop where I can click something (even in a text window) and have the cursor positioned or execute an action.

Unfortunately, in htop, randomness happens.

I have an xterm-compat terminal running in xterm-256color or xterm-direct (SecureCRT) which I run on Windows, but use logged-in to Linux (it also runs on Linux).

When I run htop in the window , cursor keys work fine, but *very often* due probably to 'gvim' running
in text mode and looking similar (as well a'vim' running in a text window and also working with the
mouse-cursor), I forget and click -- often on a branch in tree mode to open or close it.

Then htop goes out of tree mode into some other mode and losees my tree.

Please read+use the mouse for pointing or toggling/selecting targets or have htop ignore mouse input.

I think it is enabled by default in xterm and probably is generating keys that confuse htop.

Thanks!

**Comment by fasterit** [comment]
The mouse also works in htop 2.2.0. It is likely your Windows terminal program that does not forward the correct input to your Linux box.
If you get a newer htop you can disable the mouse on the command line with the -m / -M switch.

**Comment by BenBE** [comment]
There have been quite a few changes since htop 2.2.x days and in particular the mouse handling just recently received some work on master. Building htop from source is usually straight forward and except for some essential libraries you can configure htop to work without any external libraries.

Also the tree mode in versions 3.0.4 and beyond got a few major improvements, thus working with the mouse there should really be much more like what you expect according to your description. Please give compiling htop yourself a try and report back with any issues you face.

**Comment by fasterit** [comment]
Tumbleweed seems to have a 3.0.5 package as well: https://software.opensuse.org/package/htop

**Comment by Astara** [comment]
> The mouse also works in htop 2.2.0. It is likely your Windows terminal program that does not forward the correct input to your Linux box.

Could be.  I don't have a ready test program.  I know it works with some and it can be set to emulate a few different terminal types (ANSI, Linux, Xterm, VT100, 102, 220, 320, and others), but I'm usually using an XTERM emulation since they just added 24-bit color to that one.  Anyway, I'll close out this issue until I find out more info and can rebuild htop...  

Thanks for the info and great prog!
