### ISSUE TITLE
Graph meter coloring & dynamic scaling!

### ISSUE THREAD

**Issue by eworm-de** [htop-dev/htop#51]
The old repository by  hishamhm had a pull request about graph meter coloring & dynamic scaling.
This was developed by @Explorer09, but was never merged upstream. Any chance to rework and merge it now?

**Comment by natoscott** [comment]
@eworm-de @Explorer09 sure, please re-send and we'll take a look

**Comment by Explorer09** [comment]
@natoscott I'm not sure I would have the free time to rework the patch to keep it sync to current master.
The old pull request is still available (https://github.com/hishamhm/htop/pull/487). You can try to help yourself out.

**Comment by eworm-de** [comment]
I rebased the commits in https://github.com/eworm-de/htop/tree/graph-color-new-3
@Explorer09, can you have a look? Do you want to open a pull request?

**Comment by Explorer09** [comment]
@eworm-de 
Sorry for late reply.

I think overall the rebase looks okay, but I am personally not motivated to improve on the patch further. If the current code looks okay, then I can let people apply those themselves.

Allow me to recover from my memory about the places where the code can be improved:

* The graph cell colors were determined in the "which item occupies the most in the cell wins" approach, and this might be the best approach of coloring the cells, especially with the rounding errors.

Example: When GRAPH_HEIGHT is 4 and items' percentage is like A=15% B=20% C=15%, B's color would not be shown in the graph.

* GraphData.colors have size of int per cell, it was possible to reduce the memory space needed by using size of unsigned char.

**Comment by eworm-de** [comment]
Let's continue in #129...
