### ISSUE TITLE
Suggestion: display the number of threads next to the command when threads are hidden

### ISSUE THREAD

**Issue by Cochonours** [htop-dev/htop#511]
Similar to https://github.com/htop-dev/htop/issues/99

I understand your desire to show the threads by default, but I was wondering if an alternative would be convenient for htop to have : when the threads are hidden, write the number of threads in green and between parenthesis to the right of the process command (or something similar).

It wouldn't take much horizontal space yet would provide potentially useful information. Especially for people like me who disable the threads display by default, I would still like to know how many were spawned.

**Comment by fasterit** [comment]
A THREADS column sounds like the more logical solution for this.
Adding a number to the Command column (currently as a prefix) will be used for #303 which is in development.

**Comment by Cochonours** [comment]
Nice! This seems great 👍

**Comment by BenBE** [comment]
That information is even already available by adding the `NLWP` (Number of Light-Weight Processes) column, with [LWP](https://en.wikipedia.org/wiki/Light-weight_process) being one technical solution on Unix used for concurrency.

**Comment by fasterit** [comment]
Gee, that needs a doc update so people grep'ing for threads (like me) find something

**Comment by BenBE** [comment]
@fasterit It already says so clearly in the column description in the setup screen:

```
NLWP - Number of threads in the process
```

;-)

**Comment by fasterit** [comment]
#512 for using grep :-)

**Comment by Cochonours** [comment]
> That information is even already available by adding the `NLWP` (Number of Light-Weight Processes) column, with [LWP](https://en.wikipedia.org/wiki/Light-weight_process) being one technical solution on Unix used for concurrency.

Indeed! 😊
