### ISSUE TITLE
SysArchMeter: switch from $(lsb_release) to /etc/os-release ?

### ISSUE THREAD

**Issue by cgzones** [htop-dev/htop#516]
`lsb_release(1)` might not be as portable as thought, e.g. it's not available on FreeBSD by default.
Maybe switch to reading `/etc/os-release`?

```
NAME=FreeBSD
VERSION=12.2-RELEASE-p2
VERSION_ID=12.2
ID=freebsd
ANSI_COLOR="0;31"
PRETTY_NAME="FreeBSD 12.2-RELEASE-p2"
CPE_NAME=cpe:/o:freebsd:freebsd:12.2
HOME_URL=https://FreeBSD.org/
BUG_REPORT_URL=https://bugs.FreeBSD.org/
```

Also if `lsb_release` is not available, `popen()` will print to stderr and clutter the htop screen.
https://github.com/htop-dev/htop/blob/fd4e6b432bcc0d6bac1a15a2ea492b4a540b75a1/SysArchMeter.c#L30

**Comment by BenBE** [comment]
Depending on the OS this seems to be a mess. While `NAME`+`VERSION` gives a sensible string (usually, as `VERSION` is optional) this sticks some noise (I don't want to see LTS, RELEASE or anything like that, when asking for the version) in the fields and is only partially consistent across OSes:
https://manpages.debian.org/buster/systemd/os-release.5.en.html

WHY did they not split the `CODENAME` and `VERSION` strings into two fields? You smell a sh*** API when you're near one … :( And no, `VERSION_CODENAME` is not the full codename part (Focal Fossa for Ubuntu 20.04), but the repository ID (focal) scripts could use when accessing the software sources.

In the case of htop this is not so bad (as we'd likely want to show that concatenation anyway), but it means, we need to implement some fallbacks regarding the version field and fallback to `PRETTY_VERSION` or `VERSION_ID` depending on what is available.

Thanks, I hate it. :)

FWIW: In favour of replacing `lsb_release` with reading `/etc/os-release`.
