### ISSUE TITLE
Discrepancies between ps/top/glances and htop

### ISSUE THREAD

**Issue by mirath** [htop-dev/htop#517]
What does the "Tasks" number means in htop? I though it meant processes, but the process number reported by ps, htop and glances differs from the one reported by htop.

My htop reports around **215** tasks, however top, ps, pgrep and glances all report around **350**:
```
$ ps ax|wc -l
360

$ pgrep -cv -r Tt
358

# Glances reported 362
```
So why is htop the odd one out here? What are the exact semantics of its "Tasks" count?

PS. here are the versions of the Linux/tools that I'm running:
```
$ lsb_release 
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch

$ cat /etc/issue
Ubuntu 20.10 \n \l

$ uname -a
Linux myhost 5.8.0-41-generic #46-Ubuntu SMP Mon Jan 18 16:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ htop -version
htop 3.0.2

$ top -v
  procps-ng 3.3.16 # procps includes `ps`, `pgrep` and `top`

$ glances -V
Glances v3.1.4.1 with PsUtil v5.7.2
```

**Comment by fasterit** [comment]
htop reports the processes as "Tasks" and the threads (LWP) separately. Your `ps ax` command counts processes, kernel and user threads. Press 'H' to show user-level threads ("thr") and 'K' to show kernel threads ("kthr"). Now count all these three together.

**Comment by mirath** [comment]
The ps tool does not output threads unless explicitly requested. I did however determined that the discrepancy comes from the fact that htop does not include kernel threads in that count, while every other tool does.

This makes the semantics of the "Tasks" number clear, thanks.
