### ISSUE TITLE
not working with btime 0 (uninitialized time)

### ISSUE THREAD

**Issue by mndza** [htop-dev/htop#527]
Hello,

Since commit https://github.com/htop-dev/htop/commit/b7836515e8db8ff7a7cb99247472ac10992a4518 `htop` does not work on my embedded system if I did not set the time first (used to work fine). 

The problem is caused by these lines:
https://github.com/htop-dev/htop/blob/b7836515e8db8ff7a7cb99247472ac10992a4518/linux/LinuxProcessList.c#L246-L247

I think the main mistake here is confusing the 0 with an uninitialized value, while the error catching before was done with the return codes of the read calls (`sscanf`, `fgets`, ...).

**Comment by natoscott** [comment]
@mndza so AIUI your /proc/stat file contains a 'btime 0' line, is that correct?  Thanks.

**Comment by mndza** [comment]
Yes, exactly.

**Comment by natoscott** [comment]
OK, thanks, I'll tweak the code to better handle this case.
