### ISSUE TITLE
Provide a way to view very long command lines

### ISSUE THREAD

**Issue by marcin-chwedczuk** [htop-dev/htop#539]
It is not unusual for JVM applications to pass a lot of switches and sometimes even a `classpath` as arguments to `java` command. The end result is a command line that is often more than 4k bytes long. I often encounter such long commands during devops operations at work. Current behaviour of `htop` allows you only to search for a particular command line, and scroll to the left and to the right using arrows or jump at start/end using `Ctrl+A` and `Ctrl+E`. This is often insufficient when you want take a look at say GC flags passed to `java` command.

Alternative design would be to have a key shortcut that would copy the entire command line and open it in a text viewer e.g. `less` or `more` for convenient searching and scrolling. That would help a lot for people working with JVM. 

I am not a C programmer but I am willing to help to implement this. I miss this feature quite often at work and I feel that it would make my work easier.

**Comment by fasterit** [comment]
There is a 'w' hotkey since htop 3.0.3.
It shows the whole command in an infoscreen.

**Comment by marcin-chwedczuk** [comment]
@fasterit Thanks, indeed I did not know that `w` exists and I must admit that I have searched for a while looking for solution. I did some tests and it looks very promising, I am closing the ticket.

**Comment by nh2** [comment]
For long lines longer than ~4000 chars, the `W` screen is cut off:

* https://github.com/htop-dev/htop/issues/1860
