### ISSUE TITLE
Need more columns for CPUs meters

### ISSUE THREAD

**Issue by nbald** [htop-dev/htop#541]
New CPUs have a crazy number of cores. 4 columns is not enough. The screen gets filled with CPUs meters. We do not see the processes anymore.

Here is a screenshot on a dual Epyc 7702 server:
![Capture d’écran du 2021-02-23 23-51-38](https://user-images.githubusercontent.com/1681443/108918718-1d7b6300-7632-11eb-8ea9-bde8b1f055fe.png)

**Comment by BenBE** [comment]
Which version of htop are you running? The most recent release should have 4-columns-per-side CPU meters available. If not you might have a look at master.

**Comment by richliu** [comment]
In F2 Setup, it support 4 columns mode on left and right, it can use this mode.

Probably add 3 columns would be better idea for mass CPUs requirement.  

![image](https://user-images.githubusercontent.com/41711/111989863-49b0d380-8b4d-11eb-8121-12a71af5540c.png)

**Comment by fasterit** [comment]
A choice of 2/3/4 columns in the header are already implemented in #445
