### ISSUE TITLE
Add setting to disable IRIX mode for CPU percents

### ISSUE THREAD

**Issue by hardhub** [htop-dev/htop#552]
On regular top command it happens with keyboard shortcut Shit + I

**Comment by BenBE** [comment]
You mean this?

https://logic.edchen.org/irix-mode-vs-solaris-mode-in-top-command/

**Comment by fasterit** [comment]
@cgzones points out https://github.com/htop-dev/htop/commit/15eab2012d2100e1ddd20c186db23a8172b5858d . Do you need anything beyond the `PERCENT_NORM_CPU` column?

**Comment by hardhub** [comment]
> 
> 
> You mean this?
> 
> https://logic.edchen.org/irix-mode-vs-solaris-mode-in-top-command/

Yes, good reference.

**Comment by hardhub** [comment]
> 
> 
> @cgzones points out [15eab20](https://github.com/htop-dev/htop/commit/15eab2012d2100e1ddd20c186db23a8172b5858d) . Do you need anything beyond the `PERCENT_NORM_CPU` column?

As I understand 2 columns will be available - normalized to 100% and original one. That sounds good.

**Comment by fasterit** [comment]
`PERCENT_NORM_CPU` for Darwin has been merged in 4f9cf14, closing.
