### ISSUE TITLE
Run IWYU to clean up includes

### ISSUE THREAD

**Issue by BenBE** [htop-dev/htop#569]
Since the last major cleanup with IWYU a few unnecessary uses of headers and missing includes (implicitly included anyway) have sneaked into the code and should be cleaned up sometimes.

**Comment by mayurdahibhate** [comment]
@BenBE  I would like to work on this!
Could you please provide little help for me to get started?
Thanks!

**Comment by BenBE** [comment]
There's a script `iwyu/run_iwyu.sh` that you can start. Watching its output you'd normally see things like:

```
  CC       Affinity.o

(Affinity.h has correct #includes/fwd-decls)

(Affinity.c has correct #includes/fwd-decls)
```

if everything if okay for a file. When there's some header missing the script usually remarks this by telling the missing header as `XY.c should add these lines:`. In that case add the proposed lines sorted according to the `STYLEGUIDE` in the docs folder.

You can usually ignore the struct suggestions the script gives: In that case you should instead add the appropriate header providing that structure; unless this leads to recursive inclusion dependencies of headers.

Also, while going through the various files you might have a look at the following two additional issues:
1. Two blank lines after all headers (add a second if it's missing)
2. Platform-dependent files (those in the platform sub-directories) should be included relative to the main source directory. The only exception are places accessing `"Platform.h"`in the main source directory (and `zfs/`), which is included without its path, when not inside platform code. Inside the platform code the relative path, e.g. `"linux/Platform.h"` is used.
