### ISSUE TITLE
Feature Request: Ability to show the alternative keybindings in the Function Bar

### ISSUE THREAD

**Issue by ifohancroft** [htop-dev/htop#576]
Htop allows you to use either the F-keys, or alternative keys such as h, s, /, etc, however the Function Bar always shows the F-keys. Some of us have keyboards that don't have an F-Row and we can't remember the alternative keys. It would be extremely helpful to have the option to make the Function Bar show the alternative keys instead.

**Comment by fasterit** [comment]
Not having function keys is common Chromebooks. Which are not really frequently used to administer Linux or BSD systems.
Is there any other case where function keys are not available?

**Comment by ifohancroft** [comment]
60% keyboards, 65% keyboards, split/ergo keyboards, 40/45% keyboards.
Pretty much 75% of the custom mechanical keyboards community.

For example, I am currently on a 45% keyboard and my work is Linux Servers, writing code for/on Linux Servers, etc :D

**Comment by BenBE** [comment]
The key bindings are also documented when pressing <kbd>F1</kbd> or <kbd>?</kbd> …

**Comment by ifohancroft** [comment]
They are also in the man page, but nothing beats being able to make the function bar show them instead.

**Comment by BenBE** [comment]
Discussing this item in the team we decided to not follow up on this feature. Arguments for this decision were both the lack of (demonstrated) usefulness that also warrants the break in the current look&feel in the UI. Changing this aspect causes a lots of code changes for far too little gain.
