### ISSUE TITLE
Read os-release(5) on FreeBSD

### ISSUE THREAD

**Issue by BenBE** [htop-dev/htop#586]
Starting with FreeBSD 13 the distribution information are available via os-release(5).

Thus on FreeBSD an additional check for reading the information from os-release(5) like is done on Linux should be added.

Maybe also check if it's worth consolidating this in the generic directory.

**Comment by cgzones** [comment]
Isn't the os-release code already platform independent, and when the configure script finds an os-release file it gets read?

**Comment by natoscott** [comment]
@cgzones not strictly speaking, no - some platforms (pcp) may be reading os-release information from elsewhere (historical data in a pcp archive or a remote pcp server - local /etc/os-release is not read by local htop code in these cases).

**Comment by BenBE** [comment]
On FreeBSD currently only uname(2) is considered.

As the code for reading os-release(5) should be identical for all platforms that support it (Linux, FreeBSD, others???) it makes sense to have that part in the generic section and allow platforms call it on demand.

**Comment by michael-o** [comment]
> 
> 
> Starting with FreeBSD 13 the distribution information are available via os-release(5).
> 
> Thus on FreeBSD an additional check for reading the information from os-release(5) like is done on Linux should be added.
> 
> Maybe also check if it's worth consolidating this in the generic directory.

umm, 
```
# cat /etc/os-release
NAME=FreeBSD
VERSION=12.2-STABLE
VERSION_ID=12.2
ID=freebsd
ANSI_COLOR="0;31"
PRETTY_NAME="FreeBSD 12.2-STABLE"
CPE_NAME=cpe:/o:freebsd:freebsd:12.2
HOME_URL=https://FreeBSD.org/
BUG_REPORT_URL=https://bugs.FreeBSD.org/
```

Works on 12 also and in a jail:
```
# less /etc/os-release
NAME=FreeBSD
VERSION=12.2-RELEASE-p3
VERSION_ID=12.2
ID=freebsd
ANSI_COLOR="0;31"
PRETTY_NAME="FreeBSD 12.2-RELEASE-p3"
CPE_NAME=cpe:/o:freebsd:freebsd:12.2
HOME_URL=https://FreeBSD.org/
BUG_REPORT_URL=https://bugs.FreeBSD.org/
```

**Comment by cgzones** [comment]
FreeBSD does read os-release information via

https://github.com/htop-dev/htop/blob/0925c54caadbdf55c34a06590c62dfa1cfa68a93/freebsd/Platform.h#L73-L75 and https://github.com/htop-dev/htop/blob/0925c54caadbdf55c34a06590c62dfa1cfa68a93/generic/uname.c#L84
