### ISSUE TITLE
htop problems with hyper-threading

### ISSUE THREAD

**Issue by simonasmulevicius** [htop-dev/htop#601]
Good evening,

It seems that `htop` still shows that processes are running on the virtual cores even if hyper-threading is turned off.

**With hyper-threading**

To enable Simultaneous Multithreading (SMT also known as hyper-threading) I run the following command:
`echo on > /sys/devices/system/cpu/smt/control`

I check that  hyper-threading is turned **on** by running `lscpu` and here is its output:
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              **2**
```
(as expected, there are 2 threads per core)

Similarly, `lstopo` output also shows that there are two logical cores for every physical core:
![topology_with_hyperthreading](https://user-images.githubusercontent.com/50625590/114942225-1f94bd80-9e3c-11eb-8cc0-8d2e2ce47826.png)

And `htop `works as expected:
![htop_with_hyperthreading](https://user-images.githubusercontent.com/50625590/114942304-3cc98c00-9e3c-11eb-8824-94afdfebec30.png)

**Without hyper-threading**

The problem occur when I try to use `htop` without hyper-threading.

To disable Simultaneous Multithreading I run the following command:
`echo off > /sys/devices/system/cpu/smt/control`
 
I check that  hyper-threading is turned **off** by running `lscpu` and here is its output:
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-3
Off-line CPU(s) list:            4-7
Thread(s) per core:              **1**
```

Now, as shown by `lstopo`, each logical core is running on one physical core:
![topology_no_hyperthreading](https://user-images.githubusercontent.com/50625590/114942524-929e3400-9e3c-11eb-9047-dab2d27782f7.png)

BUT `htop` still shows that there are processes running on the virtual cores (e.g. 8th CPU in the bottom left corner of the image below):
![htop_no_hyperthreading](https://user-images.githubusercontent.com/50625590/114942655-c4af9600-9e3c-11eb-8582-5e3399729b61.png)

**Comment by fasterit** [comment]
That seems correct. These processes have last been executed on processor 8 when they were last scheduled.
Does the `CPU` id update e.g. when you send a DBUS message to the dbus-daemon or just a signal to any of the other processes so they are forced to wake up?

**Comment by simonasmulevicius** [comment]
Nice, that explains a lot. Previously suspended but waken-up processes don't get allocated to the previous/non-existing virtual cores - instead, only smaller set of cores is used.
