### ISSUE TITLE
Disk usage not shown in snap installation

### ISSUE THREAD

**Issue by 80avin** [htop-dev/htop#608]
**DISK R/W** column shows **NA** for many processes, for example kdenlive installed via snap.
version used 3.0.5
OS: Ubuntu 20.04. (also tested on 18.04)

Example: 
![Example](https://user-images.githubusercontent.com/19588421/115387099-d788e880-a1f7-11eb-8ca5-41cf776d373c.png)

**Comment by cgzones** [comment]
Seems to be a permission failure, maybe snap related.
Also all N/A entries are either processes of an other user or threads.

**Comment by 80avin** [comment]
I suspect the same. Maybe using classic confinement could be the best way to avoid all such issues.

**Comment by cgzones** [comment]
Probably some snap sandbox strips of the Linux capability `DAC_READ_SEARCH`.

**Comment by natoscott** [comment]
@80avin @cgzones the procfs files supplying these metrics have tighter-than-most permissions - the case here may simply be that regular users cannot access other regular users IO stats...

```
$ ps aux | grep systemd-resol[v]
systemd+     848  0.0  0.1  43748 20180 ?        Ss   Apr18   1:09 /usr/lib/systemd/systemd-resolved
$ cat /proc/848/io
cat: /proc/848/io: Permission denied
$ ls -ld /proc/848/io /proc/848/stat
-r--------. 1 systemd-resolve systemd-resolve 0 Apr 21 08:05 /proc/848/io
-r--r--r--. 1 systemd-resolve systemd-resolve 0 Apr 21 08:05 /proc/848/stat
```

**Comment by 80avin** [comment]
Did you try `sudo htop` ? That fails in snap version too.

Btw, if it is because of restrictions imposed by snap, then using classic containerization might be better idea since it removes the restrictions imposed by snap's containerization and the program works as it was installed normally via apt

**Comment by Vanav** [comment]
How to reproduce and debug information: https://github.com/maxiberta/htop-snap/issues/20

**Comment by cgzones** [comment]
Commented in https://github.com/maxiberta/htop-snap/issues/20, this is a snap issue not a htop one.
