### ISSUE TITLE
[suggestion] Add the key 'q' in the help menu bellow as another possibility to quit (in addition to "F10" )

### ISSUE THREAD

**Issue by gustavklopp** [htop-dev/htop#609]
A lot of people seem to ask themselves how to quit Htop when F10 is not working (because F10 is linked to a command in Bash for example):

https://askubuntu.com/questions/643088/how-to-kill-htop-if-i-cant-use-f10

I suggest to modify the help menu bellow, from "F10: quit" to "F10 (or 'q'): quit".

**Comment by BenBE** [comment]
That's already in there:
https://github.com/htop-dev/htop/blob/ace5730f89ed6c394154d7ffa4f8f4b4a11dae66/Action.c#L496

**Comment by gustavklopp** [comment]
thanks.
my version is from arch linux: 3.0.5
I know that Htop can already exit with 'q' or F10 : what I mean is **informing the user about it**. 
The ribbon below only shows "F10" as the exit key. A lot of people are confused about the way to exit the program since F10 is very often already used by the terminal for other function and so doesn't work.
![Zaslonska slika 2021-04-21 20-32-29](https://user-images.githubusercontent.com/6438275/115604763-08dde300-a2e2-11eb-84f5-c497e7bfd1d4.png)

**Comment by BenBE** [comment]
Press <kbd>F1</kbd>, <kbd>h</kbd> or <kbd>?</kbd> …
![image](https://user-images.githubusercontent.com/111196/115609793-48a7c900-a2e8-11eb-8a17-b4b993218376.png)

**Comment by gustavklopp** [comment]
I meant it's not a documentation problem.
Here's is my suggestion more or less (with basic mspaint skill...) 
![Zaslonska slika 2021-04-21 20-32-29](https://user-images.githubusercontent.com/6438275/115656661-de1d7a00-a335-11eb-8e5e-f1ddfd07b5b2.png)

but other way could be good also, as long as it's shown how to exit by another way than F10 (which is often used in terminal for another command)

**Comment by BenBE** [comment]
Basically same as #576 then …

We won't work around bugs and glitches in terminal emulators, especially as at least QTerminal has a proper setting to control <kbd>F10</kbd> behavior. That's BTW the first (and usually only) thing I reconfigure with such terminal emulators.
