### ISSUE TITLE
error while loading shared libraries: libtinfow.so.6

### ISSUE THREAD

**Issue by orsenthil** [htop-dev/htop#61]
When I installed master on my computer, it failed with the error message

htop: error while loading shared libraries: libtinfow.so.6: cannot open shared object file: No such file or directory

**Comment by fasterit** [comment]
Your ncurses is probably build without --enable-widec, so compile htop as a non-unicode build (./configure --disable-unicode) or use a better distro.

**Comment by rubyFeedback** [comment]
I also often had that error; always confused me.
