### ISSUE TITLE
Option `Show custom thread names` inconsistent

### ISSUE THREAD

**Issue by cgzones** [htop-dev/htop#615]
Starting with  `Show custom thread names` disabled:
    `sd-resolve|/lib/systemd/systemd-timesyncd`
Enable `Show custom thread names`:
    `sd-resolve`
Disable `Show custom thread names`:
    `sd-resolve`

Might be fixed together with #388?

**Comment by cgzones** [comment]
This issues seems to be not fixed:
When starting with `Show custom thread names` disabled I see `/lib/systemd/systemd-timesyncd`.
Enabling at runtime does not update to `sd-resolve`, only a htop restart.

Also the patch broke highlighting for real processes, as the setting showThreadNames should only affect userland threads.

**Comment by BenBE** [comment]
@cgzones Any proposed patch for this?
