### ISSUE TITLE
feature request: Availability on package managers

### ISSUE THREAD

**Issue by capt-pyro** [htop-dev/htop#62]
Congrats on version 3 and adding new features. 

I was wondering if there were plans to bring this to package managers like the original htop did or would it just be provided through those channels.

Additionally, is providing this tool as a snap or flatpak a possibility?

**Comment by maxiberta** [comment]
Fwiw, as maintainer of the [htop snap](https://snapcraft.io/htop), I plan to [switch its upstream souce to htop-dev](https://github.com/maxiberta/htop-snap/issues/8) soon.

**Comment by fasterit** [comment]
https://repology.org/project/htop/versions
shows you which distros have which latest version

**Comment by magnetophon** [comment]
@capt-pyro Maybe I'm stating the obvious here, so please excuse me if that's the case.
Normally, packages are made by the individual distros, so you should file this request at the distro you are using.
