### ISSUE TITLE
Is bintray support gone for good?

### ISSUE THREAD

**Issue by hartzell** [htop-dev/htop#620]
It appears that [the bintray tarball site](https://bintray.com/htop/source/htop) no longer exists.

Is this a transient problem or should I switch permanently to using the GitHub archive files?

**Thanks!!*

**Comment by fasterit** [comment]
Bintray has been shut down by JFrog as per https://www.jfrog.com/confluence/display/BT/JFrog+Bintray+Migration+Guide
I think @natoscott was looking into migrating our tarballs to their next product.
In any case the Github tarballs seem to be the safer choice at the moment.

**Comment by hartzell** [comment]
Well yes, that does sound kind of permanent.

Have you considered just attaching the tarballs to the GitHub Releases as release artifacts that people can use in preference to the automagically generated tar/zip files of the source tree?  E.g. [the way that tmux does it](https://github.com/tmux/tmux/releases)?

**Comment by fasterit** [comment]
Yes, that was discussed during the last core team meeting. If you provide the github actions magic before @natoscott gets his hands dirty on the JFrog stuff, I'm sure we'd be providing the Github artifacts. Ie. PR welcome :-)

**Comment by hartzell** [comment]
Sadly, I'm prohibited to contribute work to open source projects at the moments (working with the lawyers at a new job).

Whatever works most easily for you is, of course, the best thing to go with, it just seemed to me that keeping it all within one system would be easier.

Thanks for keeping `htop` available!

**Comment by natoscott** [comment]
> [...] before @natoscott gets his hands dirty on the JFrog stuff [...]

IIRC it was decided at that last meeting we'd not be going that, and we'd only be providing the github-auto-generated source tarball (i.e. without generated configure script, etc) from now on - so I've not been looking into any alternatives.

**Comment by hartzell** [comment]
Seems perfectly reasonable.  Thanks for the update!
