### ISSUE TITLE
please add temperature of core to head of monitoring screen

### ISSUE THREAD

**Issue by ip75** [htop-dev/htop#621]
$subj
`sysctl -a| grep temper` or `sysctl -n dev.cpu.0.temperature` etc.

**Comment by BenBE** [comment]
It's in the CPU meters when enabled in the setup (<kbd>F2</kbd>) under `Display Options` -> `Also show CPU temperature (requires libsensors)`. As that option says, `libsensors` has to be available and properly configured (`coretemp` or `acpitz` need to be available). You may also want to check with your distribution if `libsensors` supprot has been enabled at compile time.

**Comment by ip75** [comment]
Thank you. I don't see these options, I'll configure properly while compilation. `coretemp` already in kernel.

**Comment by ip75** [comment]
no `libsensors` in FreeBSD. Unable to compile with `--with-sensors`

**Comment by BenBE** [comment]
Ah, in that case see #419. The patch in #436 is not in any release yet. But if you could test and provide feedback that'd but great.

**Comment by ip75** [comment]
great! i'll wait for new version. Thank you very much.
