### ISSUE TITLE
Solaris: Order `GZONE` and `UZONE` after includes

### ISSUE THREAD

**Issue by BenBE** [htop-dev/htop#624]
While working on IWYU updates it was found that Solaris defines some constants before including its headers. Normally those `#define`s should follow after the headers.

> I am unsure why those constants are above the includes. But I think defining them after includes won't break anything as ```GZONE``` and ```UZONE``` are passed to ```xstrdup()``` .

_Originally posted by @mayurdahibhate in https://github.com/htop-dev/htop/pull/616#discussion_r624036197_

**Comment by mayurdahibhate** [comment]
Also, ```MAXCMDLINE``` is present both in ```solaris/SolarisProcessList.h``` and ```solaris/SolarisProcessList.c```.

**Comment by BenBE** [comment]
Additionally `MAXCMDLINE` seems unused in both files apart from that.
