### ISSUE TITLE
Feature request: option to only show used memory in memory bar

### ISSUE THREAD

**Issue by eviatarbach** [htop-dev/htop#628]
It would be great for there to be an option to only show the "used" memory in the memory bar, as opposed to also showing the cache and buffers. As a user, I only really care about the used portion, and although the others are colored differently, at a quick glance it is hard to see what portion of the memory is used because of the other colors. This seems to also be a major confusion for new users, and I think many would appreciate having the option to disable it.

**Comment by ginggs** [comment]
Closing as 'wontfix' after team discussion.  This change would hide necessary information.
