### ISSUE TITLE
Release URL tarballs?

### ISSUE THREAD

**Issue by rubyFeedback** [htop-dev/htop#63]
Hello,

I read that this is sort of the "htop 3" branch. In the old release schemes we had something
like this:

    https://hisham.hm/htop/releases/2.2.0/htop-2.2.0.tar.gz

Not sure if we had this for htop on github.

Would it be possible to also release a htop-3.0.0.tar.gz or .tar.xz?

Right now we don't have that at https://github.com/htop-dev/htop/releases. It would
simplify a few downstream scripts that I use (and perhaps others too).

**Comment by eworm-de** [comment]
You can always download tarballs from git tag:

**Comment by eworm-de** [comment]
Sadly no signatures there... :(

**Comment by fasterit** [comment]
Yes, we decided against signing sources as you either trust github for packing a zip or you don't. The fact that we have a bot sign the zip does not add much value. We would not do that manually as too much effort for too little value (in our evaluation of things).
If you want to trust a human and their gpg routine, there are signed sources available from Debian, Ubuntu, Fedora etc.

**Comment by eworm-de** [comment]
Well, in the end this is not just about trusting github. Who may be able to gain access to the repository and push malicious commits? Who may be able to manipulate the download?
Of course signed tarballs make sense only if the tarball is generated and signed on the developers machine. Everything else just moves the problem.

But how about signed git tags then? This is just about adding `--sign` to the `git tag` command (and typing the gpg key passphrase).

**Comment by fasterit** [comment]
The tarballs are generated by github hence no developer machine and no manual uploads (and thus signing makes not much sense).

I'm fine if people want to sign their git tags, I won't. Again there is no attack scenario in which that would add reasonable value.
