### ISSUE TITLE
How to lower the numerical values in display options? 

### ISSUE THREAD

**Issue by vishxm** [htop-dev/htop#632]
I accidentally increased the update interval on the setup page under display options. And I can't seem to find a way to lower it. There is also no mention of update_interval or similar parameter in the htoprc. I can pass the desired interval with -d flag but is there a way to decrease those values? (used Enter to increase it btw)

**Comment by natoscott** [comment]
The htoprc parameter you're looking for is 'delay' (see the man page option for details on how to interpret it, same as -d/--delay).

Interactively, you can use + and - to increase and decrease the update interval value.
