### ISSUE TITLE
OmniOS (Solaris): first column empty

### ISSUE THREAD

**Issue by cgzones** [htop-dev/htop#634]
On OmniOS the first screen column is not filled except for the last six rows.
Resizing the window keeps only filling the first column for the last six rows.
Reproducible in tty and ssh/pty.

![omnios](https://user-images.githubusercontent.com/6131885/119002136-e4326500-b98c-11eb-879b-3f139207a01d.jpg)

**Comment by RussianE39** [comment]
![htop_master_sunos](https://user-images.githubusercontent.com/400478/119002506-9cfca200-b995-11eb-8a66-d8be8d3c2b62.png)
Thats how it looks with default setup on S11.4

**Comment by RussianE39** [comment]
![htop_master_sunos2](https://user-images.githubusercontent.com/400478/119036857-ec54c980-b9b9-11eb-98e6-b319b40f336e.png)
This is after patch, LWPID working now
