### ISSUE TITLE
Crash when exit

### ISSUE THREAD

**Issue by RomanAvdeenko** [htop-dev/htop#640]
I attach htop.objdump  file.

/usr/bin/htop:     file format elf64-littleaarch64
Disassembly of section .init:
000000000000d180 <.init>:
    d180:	a9bf7bfd 	stp	x29, x30, [sp, #-16]!
    d184:	910003fd 	mov	x29, sp
......

[htop.objdump.log](https://github.com/htop-dev/htop/files/6537966/htop.objdump.log)

**Comment by BenBE** [comment]
Does `htop` produce an error output? If so, a copy of that error output might be good.
If there's no crash output from `htop` itself, could you a debugger and try to get backtrace of the crash location?

Apart from this: what distro? What kernel? Which `htop` version? Any particular settings in your configuration file or does it happen with default settings?
