### ISSUE TITLE
Update user information on `proc->st_uid` change

### ISSUE THREAD

**Issue by BenBE** [htop-dev/htop#661]
Given commit 9114cf6ea3771c55cdaaa3af8583feaf0514d956 from #649 I did a quick scan on the other platforms and things look like platforms besides Linux are still missing this check:

- [ ] Darwin
- [x] Dragonfly
- [x] FreeBSD
- [x] Linux (as of #649)
- [ ] NetBSD (cf. #603)
- [ ] OpenBSD
- [x] PCP (@natoscott)
- [ ] Solaris (broken: internally updates `proc->st_uid`, but does not refresh `proc->user`)
- [x] Unsupported (consistently refreshes both fields to constant values ;-))

**Comment by natoscott** [comment]
@BenBE no change needed for PCP platform here - this is handled in setUser in pcp/PCPProcessList.c which conditionally refreshes the username if the uid is new (since this info may be coming over the network, we sample uid and name unconditionally once-per-sample).

**Comment by BenBE** [comment]
> @BenBE no change needed for PCP platform here - this is handled in setUser in pcp/PCPProcessList.c which conditionally refreshes the username if the uid is new (since this info may be coming over the network, we sample uid and name unconditionally once-per-sample).

As I noticed in the PCP source the call to `PCPProcessList_updateUsername` is only performed for new processes. Or I've missed one call site …
