### ISSUE TITLE
Feature request: show open files' read/write position

### ISSUE THREAD

**Issue by pjvandehaar** [htop-dev/htop#672]
In the open files view (`l`), I want to see a column of file read positions, like the `OFFSET` column of `lsof -o -p $pid`.  

Currently, htop shows `SIZE` like `lsof -s -p $pid`.  Could htop show both SIZE and OFFSET?

I'm happy to work on this if you would accept a PR.

**Comment by BenBE** [comment]
We're always looking forward to receiving a PR for open issues. If you need any assistance or help with the source feel free to ask.
