### ISSUE TITLE
Make set_escdelay optional

### ISSUE THREAD

**Issue by polluks** [htop-dev/htop#676]
Define this if your curses library has the set_escdelay() function.
`HAVE_SET_ESCDELAY`

**Comment by BenBE** [comment]
Can you elaborate?

**Comment by polluks** [comment]
Not every Curses has this function, therefore the Autoconf macro.

**Comment by BenBE** [comment]
Any OS/platforms in particular that this applies to?

**Comment by polluks** [comment]
for example https://github.com/sabotage-linux/netbsd-curses/releases/tag/v0.1.0
