### ISSUE TITLE
Feature request: Collapse all children in tree view

### ISSUE THREAD

**Issue by eigan** [htop-dev/htop#68]
I would like to get to the following view as soon as possible. Currently that means `f6` `down` `f6` `down` `..`

![image](https://user-images.githubusercontent.com/41789/91933808-0d6d7100-ecea-11ea-8274-2388c91e5e2a.png)

Solutions that I would be happy with:
- A shortcut to toggle all children of selected, for instance `shift` `f6`.
- Tree view have collapsed all by default (recursive). Expand will just expand the selected element, not recursive.

Relevant issues at original htop-repo:
- https://github.com/hishamhm/htop/issues/24 _(latest responses argue that it should be collapsed by default)_
- https://github.com/hishamhm/htop/pull/510 _(pull request for collapse all)_

**Comment by devwatchdog** [comment]
+1  for hishamhm/htop#510

**Comment by wanghankun** [comment]
+1 why it isn't already implemented is beyond me, please dev!

**Comment by BenBE** [comment]
> +1 why it isn't already implemented is beyond me, please dev!

Because nobody had the time to properly review and test a working patch for it yet.

On that note: The patch for https://github.com/hishamhm/htop/pull/510 LGTM and kinda reasonable. Only thing It'd suggest checking is if the collapsed-by-default should exclude PID 1, as having just PID 1 show up when collapsing by default is kinda counterproductive.

**Comment by caramboleyo-no2fa** [comment]
This is supposed to be merged in 2021
Just tried the star keys with ubuntu 24.04 and it does not work.

**Comment by fasterit** [comment]
The Ubuntu release 24.04 has htop 3.3.0-4 and the functionality is included there.

**Comment by caramboleyo-no2fa** [comment]
yes it is! was in an old 22.04 terminal, now in 24.04 it does work.
