### ISSUE TITLE
Press F9 twice to SIGKILL

### ISSUE THREAD

**Issue by Harvie** [htop-dev/htop#690]
Hello,
when i press F9 once, kill dialog is open with SIGTERM highlighted. When i press 9, it highlights SIGKILL. Then i need to press Enter to send the signal.
So to kill process it is rather tedious: F9 -> 9 -> Enter

Can you please add feature that hitting F9 twice will just send the SIGKILL?

**Comment by fasterit** [comment]
That means somebody with shaky fingers would kill the highlighted process accidentally, not a risk we should take.
If you have to kill a process (-9) over terminating it, there is something broken in the software you run. Consider fixing that instead. Sigkill should be an absolute exception and not something you need efficiency gains for.

**Comment by Harvie** [comment]
> there is something broken in the software you run. Consider fixing that instead. 

LOL i am software developer and there is certainly something broken, it is my job to fix it. that is why i need to kill the beast 300 times day. that is obviously why i am annoyed by having to press way too much buttons.

**Comment by BenBE** [comment]
Have you considered `pkill -9 $shiTTYtool` on a programmable shortcut key of your keyboard? IIRC that's what those multimedia keys are for … ;-)

Apart from that I agree with @fasterit that there's not much additional value compared to the risk involved with this function.

**Comment by Harvie** [comment]
> Have you considered pkill -9 $shiTTYtool on a programmable shortcut key of your keyboard? 

Of course i did. Problem is that i am developing a library which is supposed to work with lots of different binaries, so name of the binary is always different.

> Apart from that I agree with @fasterit that there's not much additional value compared to the risk involved with this function.

What if pressing F9 twice would highlight SIGKILL instead of SIGTERM, but you would still need to press ENTER to confirm it?

**Comment by fasterit** [comment]
> What if pressing F9 twice would highlight SIGKILL instead of SIGTERM, but you would still need to press ENTER to confirm it?

Same amount of key presses as your original sequence.

```bash
grep -l libmycrazything.so.0.0.0 /proc/*/maps 2> /dev/null | cut -d / -f 3 | xargs kill -9
```

... bind it to a keyboard shortcut in your desktop environment.

**Comment by Harvie** [comment]
> Same amount of key presses as your original sequence.

But less groping :-)

> grep -l libmycrazything.so.0.8.15 /proc/*/maps 2> /dev/null | cut -d / -f 3 | xargs kill -9

Thank for the tip with /proc/*/maps... But hey. you can do anything that htop does by carefully crafting some commands, no doubt about that. But i am already inspecting the process behaviour through htop, so it makes sense to kill it from htop. Not to mention that there can be multiple instances running.

**Comment by fasterit** [comment]
Some time in the future there will be configurable external commands, see e.g. #638, #686 which you could use to run a script like the above on the selected PID.

We won't change the F9 functionality for all users as there is much downside / inconsistency for your very specific use case and request.

If you have some time, please feel free to work on a generic set of external commands and keybindings, we'd be happy to review a design draft and subsequent PR(s).
