### ISSUE TITLE
Drop margin around header by default

### ISSUE THREAD

**Issue by BenBE** [htop-dev/htop#71]
Although the blank margin around the header can be removed by a configuration setting already I think it's a waste of valueable screen estate to have it enabled by default, as it wastes two rows of your terminal height placing no information. As the density of information of most other parts of htop is quite high this seems a bit counter-intuitive to have this blank area on by default.

**Comment by eworm-de** [comment]
Never understood why the margin is there, so full ack.

**Comment by fasterit** [comment]
In the core team call we have decided to stay with Hisham's design decisions for the time being.
It is easy enough to change for people that want their screen layout as dense as possible.
