### ISSUE TITLE
Autogroup monitoring

### ISSUE THREAD

**Issue by unphased** [htop-dev/htop#720]
Here https://github.com/nlburgin/reallynice is an explanation for the problem related to autogroups in linux. Basically, the nice level of a process only affects that process's priority within its autogroup, and modern linux systems dole out autogroups based on session ID.

What this means is that for example when I run a build with `make -j32` on my terminal it makes not an iota of difference whether or not it has been `nice`d, the OS will schedule this task with the same relative priority as other processes on the system. In effect, the feature of nice itself has been broken for almost all of our command line workflows.

The nice level of a process still has a meaning (and works the same way), it only does so within an autogroup, however.

As such, I would recommend that a new column is added to htop that can show what autogroup each process is in. That way the `nice` readout (a default-enabled column!) could regain a semblance of utility on these systems which have autogroups switched on.

Furthermore, each autogroup itself has a nice level which the system will take into account. If you want to "background" something, previously you may `nice -n19` it, but now we usually need to `cat 19 > /proc/<pid>/autogroup` to achieve some semblance of similar behavior. The behavior isn't the same, though, as at this point all processes in that autogroup would still share CPU equally, and the regular nice level must be used to further manipulate that. 

This is spelled out very clearly under the autogroups section here: https://man7.org/linux/man-pages/man7/sched.7.html

Taking all of this into consideration, then, I'd say the default display of htop ought to be adjusted *for Linux systems to which this applies which have autogroups enabled*:

- remove process nice level column
- add autogroup column
- add autogroup nice level column

**Comment by natoscott** [comment]
Quite surprising but this (CFS nice breakage) seems to be the case from a bit of reading around.

I can implement the metric extraction and display code tomorrow if noone else is super keen, and we can have a discussion about default display changes then once folks have had a chance to try it out.

**Comment by BenBE** [comment]
I think we should add those two autogroup columns to new configurations when we detect them to be available.

Also IMHO we should keep the nice feature in place, but allow for the autogroup priority to be set too. Reprioritizing a whole group of processes when only one is selected may come as a surprise to the user, thus updating the group priority should be explicit (or by config to switch if nicing should apply to single processes/LWP or autogroups vs. default).

**Comment by fasterit** [comment]
We should also make the F7 / F8 keys able to change auto-group niceness (e.g. as Shift-F7 / Shift-F8 and "{" / "}"  (as "[" / "]" are also bound to modify niceness))

**Comment by BenBE** [comment]
Sound good to me with those keybindings …
