### ISSUE TITLE
swap and zram

### ISSUE THREAD

**Issue by xenoterracide** [htop-dev/htop#721]
Maybe this is a question, but the output of zram and swp is confusing. I'd like to see which swap is used at a glance more than total swap, like the output of `swapon` on my system.

Also the 12k/16k isn't making much sense. I assume that has something to do with the compressed size, but I don't know why there are two numbers.

```
swapon                                                                    # ~
NAME           TYPE       SIZE  USED PRIO
/dev/nvme0n1p6 partition 32.2G    0B   -2
/dev/zram0     partition    4G 15.1M  100
```

![Htop showing 16k zram used an 15.1M swap total](https://user-images.githubusercontent.com/5517/128395336-28685f29-e087-46c4-a069-cc18ae48bea5.png)

**Comment by BenBE** [comment]
Dissecting the values that htop shows we have:

Swp: 15.1MB used from the zram swap partition. (0B normal swp + 15.1MB from zram).
ZRAM: The format is used(uncompressed)/total. I#m not fully sure if the 12K are correct in this display, but apart from this the values look sensible.

I'm not sure if splitting the values for normal swap and zram partitions in the display would be any better.

**Comment by xenoterracide** [comment]
> I#m not fully sure if the 12K are correct in this display, but apart from this the values look sensible.

Yeah... does it help for me to give any additional data for that? I would think that it would be 15.1MB (is that MB, or MiB, not tat I care much)

> I'm not sure if splitting the values for normal swap and zram partitions in the display would be any better.

It could be a configuration option.

**Comment by BenBE** [comment]
> > I#m not fully sure if the 12K are correct in this display, but apart from this the values look sensible.
> 
> Yeah... does it help for me to give any additional data for that? I would think that it would be 15.1MB (is that MB, or MiB, not tat I care much)
> 

The function `Meter_humanUnit` used to display those values uses binary prefixes, thus 1024 …

> > I'm not sure if splitting the values for normal swap and zram partitions in the display would be any better.
> 
> It could be a configuration option. The better naming would be total swap and, swap per device? P.S this piece is actually a request for a feature ;)

Could you open up a separat issue for this part and elaborate a bit more what effects the setting should have when enabled and when disabled?

**Comment by xenoterracide** [comment]
> I could, though that's the primary reason for opening this, I'm was about to open a bug for the other thing.


You can see that `/proc/swaps` is saying that there's `21k` of swap used, and `zramctl` is saying `20k` of the original size, where swapon is for some reason saying 20.6M which simply doesn't add up. The difference in 1k is maybe some filesystem overhead?

```
[manjaro ~]# cat /proc/swaps
Filename				Type		Size		Used	Priority
/dev/nvme0n1p6                          partition	33791996	0	-2
/dev/zram0                              partition	4194300		21060	100
[manjaro ~]# numfmt --to iec 21060
21K
[manjaro ~]# zramctl
NAME       ALGORITHM DISKSIZE DATA COMPR TOTAL STREAMS MOUNTPOINT
/dev/zram0 zstd            4G  20K 16.1K   20K       8 [SWAP]
[manjaro ~]# numfmt --to iec-i 21060
21Ki
[manjaro ~]# swapon
NAME           TYPE       SIZE  USED PRIO
/dev/nvme0n1p6 partition 32.2G    0B   -2
/dev/zram0     partition    4G 20.6M  100
[manjaro ~]#
```

**Comment by BenBE** [comment]
Actually `/proc/swaps` is in KiB if you check the units for the 4 GiB reported … Thus it's actually ~21 MiB.
Also: Can you provide matching copy of `/proc/meminfo` (filtering entries starting with `M` and `S` suffices).

Also will need to dig into `zramctl` where it gets those 20K from or if its just a bug there …

**Comment by xenoterracide** [comment]
```
 EMACS  xeno  ~  cat /proc/meminfo
MemTotal:       16138912 kB
MemFree:         2505360 kB
MemAvailable:   10192688 kB
Buffers:            4836 kB
Cached:          9573260 kB
SwapCached:            0 kB
Active:          4968820 kB
Inactive:        6392028 kB
Active(anon):      23376 kB
Inactive(anon):  3485928 kB
Active(file):    4945444 kB
Inactive(file):  2906100 kB
Unevictable:     1472192 kB
Mlocked:              96 kB
SwapTotal:      37986296 kB
SwapFree:       37986296 kB
Dirty:               284 kB
Writeback:           168 kB
AnonPages:       3254780 kB
Mapped:           822020 kB
Shmem:           1736528 kB
KReclaimable:     359040 kB
Slab:             574828 kB
SReclaimable:     359040 kB
SUnreclaim:       215788 kB
KernelStack:       19200 kB
PageTables:        42688 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    46055752 kB
Committed_AS:   12593916 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       93160 kB
VmallocChunk:          0 kB
Percpu:            13632 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:     1413856 kB
DirectMap2M:    11968512 kB
DirectMap1G:     3145728 kB
 EMACS  xeno  ~  zramctl
NAME       ALGORITHM DISKSIZE DATA COMPR TOTAL STREAMS MOUNTPOINT
/dev/zram0 zstd            4G   4K   63B    4K       8 [SWAP]
```

**Comment by ingrinder** [comment]
I left [an answer](https://unix.stackexchange.com/a/699299/522469) on your stackexchange question - this is probably down to zswap. The numbers are technically correct, but if you want to know how much is in the zswap pool I'm not sure if there's a way to find out aside from subtracting to get the difference.
