### ISSUE TITLE
Improve large digit readability by using rounded corners

### ISSUE THREAD

**Issue by rbanffy** [htop-dev/htop#735]
Large digits in `Meter.c` use line drawing characters, but relies on "hard" corners originally present in IBM PC character ROMs. Most current systems, either by direct terminal support, or font support, provide rounded corners that would make the digits more readable:

![image](https://user-images.githubusercontent.com/184714/129236456-0339e465-95a6-445b-8efc-18eed9d10baf.png)

instead of

![image](https://user-images.githubusercontent.com/184714/129236781-f3080fa9-9367-4369-94a8-0c4d04149d74.png)

**Comment by birdie-github** [comment]
I see no logic in the code which detects the presence of these symbols in the console font. What will happen if they are missing? It could have been made optional I guess.

**Comment by BenBE** [comment]
Currently we assume that a locale ending in `.utf8` provides all characters we need.
Cf. `CRT_utf8` at e.g. https://github.com/htop-dev/htop/blob/393330239ebebb66592ded221b47897347c2abee/CRT.c#L918-L932

**Comment by birdie-github** [comment]
This is a bold assumption, let's hope it's always correct. :-)

**Comment by BenBE** [comment]
Closed, cf. https://github.com/htop-dev/htop/pull/736#issuecomment-946412725
