### ISSUE TITLE
Feature Request: Allow for marking of new/old entries

### ISSUE THREAD

**Issue by BenBE** [htop-dev/htop#74]
Repost of https://github.com/hishamhm/htop/issues/837

Short description:
Allow for marking new/old entries in the process view similar to what SysInternals Process Explorer does.

Screenshot:
![](https://messengergeek.files.wordpress.com/2018/02/processesstartandstop.gif)

**Comment by Ckath** [comment]
are these just cleared/added ever redraw? or is there some delay/decay time(either in ms or amount of redraws later)?

**Comment by BenBE** [comment]
A freshly added process entry is marked green for a configurable time (default 5 seconds IIRC, configurable up to 10 seconds). An entry of a process that just died is marked red and kept there for the same time, before it vanishes.

The redraw delay is independent of that highlighting time.
But in the case of htop it could well be just synced to redraws.
