### ISSUE TITLE
htop very slow to start and extremely laggy (~5 second input delay) (Arch linux, threadripper 3990x)

### ISSUE THREAD

**Issue by pdales** [htop-dev/htop#748]
Not sure exactly which update but within the last 7 months, htop started being extremely laggy. When I type htop in terminal it takes a good 5-10 seconds to start. Once running each keystroke has about a 5 second input delay. 

I installed htop with pacman -s htop
(currently version 3.5)

OS: Arch Linux 
Kernel: x86_64 Linux 5.13.10-arch1-1
Shell: bash 5.1.8
CPU: AMD Ryzen Threadripper 3990X 64-Core @ 128x 2.9GHz
GPU: NVIDIA GeForce GTX 1650

Is there any log files or ways I can help to debug this problem? Would really like to run the latest version of htop.

Thanks

**Comment by BenBE** [comment]
Can you try building `htop` with `./configure --enable-debug`. Running the resulting build in `valgrind --tool=callgrind` might provide some hints (analyze with `kcachegrind`) for where to best look to optimize things.

**Comment by BenBE** [comment]
Also have a look at #471 which might be related.

**Comment by pdales** [comment]
Disabling show CPU frequency fixed it (#471), thanks a lot !

**Comment by Herz3h** [comment]
I notice it is slow aswell with verison 3 of htop, version 2.0.2 is fine.

Specs: 

dual cpu 20core/40 threads 2.4Ghz total.

Number of open files: 800000
Number of processes running: 1600

CPU Frequency is disabled, refresh interval is 1.5 sec, and it freezes when using arrow keys, refresh is kinda slow. Unfortunately I cannot install htop 2.0.2 on debian 11.

Compiling with `./configure --enable-debug` makes it even more slow and unusable :/

**Comment by cgzones** [comment]
@Herz3h Please run htop under the valgrind tool callgrind:

Best to use on a htop version with debug information (compiled with `-g`).
```sh
valgrind --tool=callgrind ./htop
callgrind_annotate --tree=both --show-percs=yes callgrind.out.<PID>
```

and share either the raw callgrind output `callgrind.out.<PID>` or the annotated output of `callgrind_annotate`.

**Comment by Herz3h** [comment]
How do I compile with `-g` ?

**Comment by Herz3h** [comment]
[callgrind.out.4084391.txt](https://github.com/htop-dev/htop/files/7149439/callgrind.out.4084391.txt)

**Comment by cgzones** [comment]
> How do I compile with -g flag using autoconf ?

autoconf sets CFLAGS by default to `-g -O2`; so a simple `./configure` is fine (the comment was for the case you using custom CFLAGS).


```
19,021,947,450 (49.12%)  < /tmp/htop/linux/LinuxProcessList.c:LinuxProcessList_readMaps (56,046,660x) [/tmp/htop/htop]
19,021,947,450 (49.12%)  *  /tmp/htop/linux/LinuxProcessList.c:fast_strtoull_hex [/tmp/htop/htop]

 3,875,961,846 (10.01%)  < /tmp/htop/linux/LinuxProcessList.c:LinuxProcessList_readMaps (14,011,665x) [/tmp/htop/htop]
 3,875,961,846 (10.01%)  *  /tmp/htop/linux/LinuxProcessList.c:fast_strtoull_dec [/tmp/htop/htop]

30,600,245,035 (79.03%)  < /tmp/htop/linux/LinuxProcessList.c:LinuxProcessList_recurseProcTree (151,652x) [/tmp/htop/htop]
 2,687,279,315 ( 6.94%)  *  /tmp/htop/linux/LinuxProcessList.c:LinuxProcessList_readMaps [/tmp/htop/htop]
19,021,947,450 (49.12%)  >   /tmp/htop/linux/LinuxProcessList.c:fast_strtoull_hex (56,046,660x) [/tmp/htop/htop]
 3,876,963,827 (10.01%)  >   ./libio/iofgets.c:fgets (17,504,550x) [/usr/lib/x86_64-linux-gnu/libc-2.31.so]
 3,875,961,846 (10.01%)  >   /tmp/htop/linux/LinuxProcessList.c:fast_strtoull_dec (14,011,665x) [/tmp/htop/htop]
   679,950,437 ( 1.76%)  >   ./string/../sysdeps/x86_64/multiarch/strchr-avx2.S:__strchr_avx2 (17,352,898x) [/usr/lib/x86_64-linux-gnu/libc-2.31.so]
   166,136,450 ( 0.43%)  >   ./string/../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:__strstr_sse2_unaligned (2,547,899x) [/usr/lib/x86_64-linux-gnu/libc-2.31.so]
   155,899,800 ( 0.40%)  >   /tmp/htop/./XUtils.h:String_startsWith (2,556,000x) [/tmp/htop/htop]
    75,029,626 ( 0.19%)  >   ./libio/iofclose.c:fclose@@GLIBC_2.2.5 (151,652x) [/usr/lib/x86_64-linux-gnu/libc-2.31.so]
    61,075,400 ( 0.16%)  >   /tmp/htop/linux/LinuxProcessList.c:fopenat (151,652x) [/tmp/htop/htop]
           884 ( 0.00%)  >   ./elf/../sysdeps/x86_64/dl-trampoline.h:_dl_runtime_resolve_xsave (1x) [/usr/lib/x86_64-linux-gnu/ld-2.31.so]
```

The function `fast_strtoull_hex` is probably only up high, as it gets called often and optimization were off.
The *real* cause is `LinuxProcessList_readMaps`, see #768.
You might want to disable the process column `M_LRS` (title: `LIB`) to avoid those expensive reads of `/proc/<PID>/maps`.

**Comment by BenBE** [comment]
ACK. `fast_strtoull_hex` was initially introduced to optimize the call of `strtoull` that would be there otherwise (which was even slower). The problem here really is that there are literally millions of calls to that function due to many lines in the `/proc/<PID>/maps` files needing parsing.

@cgzones Doing some experimentation it seems there's a ~60% increase regarding the time spent in `LinuxProcessList_readMaps` when applying the following patch:

```diff
$ git diff
diff --git a/linux/LinuxProcessList.c b/linux/LinuxProcessList.c
index c4b7ebc7..bf699f58 100644
--- a/linux/LinuxProcessList.c
+++ b/linux/LinuxProcessList.c
@@ -588,6 +588,11 @@ static void LinuxProcessList_readMaps(LinuxProcess* process, openat_arg_t procFd
       unsigned int map_devmin;
       uint64_t map_inode;
 
+      // Short circuit test: Assume .so file extension for modules
+      size_t buflen = strnlen(buffer, sizeof(buffer));
+      if (buflen < 4 || buffer[buflen - 4] != '.' || buffer[buflen - 3] != 's' || buffer[buflen - 2] != 'o')
+         continue;
+
       // Short circuit test: Look for a slash
       if (!strchr(buffer, '/'))
          continue;
```

This works only when assuming all linked libraries have extension `.so` (`buffer[buflen-1]=='\n'` is unchecked here, but implied from `fgets`).
