### ISSUE TITLE
CPU time calculations are wrong under Rosetta 2

### ISSUE THREAD

**Issue by amomchilov** [htop-dev/htop#765]
There's a bug in libproc when running under Rosetta 2 on M1 Macs, that's present in macOS 11.5.1 (build `20G80`), and 11.5.2 (build `20G95`), and perhaps others (I haven't checked it on the developer betas). I've reported it under [`rdar://FB9546856`](https://openradar.appspot.com/radar?id=5055988478509056)

 - `mach_timebase_info` returns a factor of `1/1`, just like on Intel
 - but the values of `pti_total_user` and `pti_total_system` are the same as native M1 execution, which are native mach tick units (each of which is 3/125th’s of a nanosecond)

Thus when you take the values of `pti_total_user` and `pti_total_system`, multiply them by the factor returned by `mach_timebase_info`, you get a value in nanoseconds which is around 41.666x to small (125/3, to be precise).

I've submitted a bug report (I'll edit in the details here later) to Apple.

In principle, you could implement a workaround:

1. add a special case to detect when running an affected macOS version, on M1 mac, under Rosetta 2
2. ignore the result of `mach_timebase_info` completely
3. multiply by the same 125/3 factor as if `mach_timebase_info` was run natively

_Originally posted by @amomchilov in https://github.com/htop-dev/htop/issues/751#issuecomment-903195739_

**Comment by BenBE** [comment]
Has this been resolved with the linked PR or is there anything still open with this issue?

**Comment by amomchilov** [comment]
It's resolved, but I don't have permission to add #751 as a "linked pull request" to this issue.

Could you please do that, and close?

**Comment by amomchilov** [comment]
@BenBE I mixed it up. Could you un-link #751/#752 (it's unrelated), and link #813 instead?

**Comment by fasterit** [comment]
@amomchilov: Changing the links on what has been closed / committed doesn't work anymore (you can reopen but ... lotsa noise for little benefit). This is software development, not the accounting department, so I guess we're good enough.
