### ISSUE TITLE
Tidy up process state handling

### ISSUE THREAD

**Issue by BenBE** [htop-dev/htop#778]
In the long term it'd be better to have a canonical set of state values (an enum), switch all the PROCESS_N_STATE macros to descriptive names (like RUN), have platform-specific code refresh the 'state' enum.  This will keep the htop core code cleaner and more platform-neutral once again.  But at this stage of a release, I think this smaller fix is best.

_Originally posted by @natoscott in https://github.com/htop-dev/htop/pull/769#discussion_r701506570_

**Comment by marcluque** [comment]
Hey there, I would like to work on this. But I'm not quite sure I correctly understand the requirement of this issue. Could you elaborate a little and explain what exactly is meant by
>  platform-specific code refresh the 'state' enum

I suppose that there should be some enum that contains [this](https://github.com/htop-dev/htop/blob/d23627fda9878f0a8640c24d95145d56882ba503/Process.h#L206). A variable of this enum should then be updated? I assume that the variable `this->state` used [here in #769](https://github.com/htop-dev/htop/pull/769#discussion_r701506570) is updated somewhere, right?

Thank you in advance for your time

**Comment by BenBE** [comment]
> Hey there, I would like to work on this. But I'm not quite sure I correctly understand the requirement of this issue. Could you elaborate a little and explain what exactly is meant by
> 
> > platform-specific code refresh the 'state' enum
> 

As it is now the code manages the process state as a single character that only by convention has `R` as running, `D` as defunct and so on. What would be good would be if the available states (in the comment you linked) would be reflected as identifiers of a `typedef enum ProcessState_ { … } ProcessState` that that had those states as fixed identifiers for all platforms to use.

> I suppose that there should be some enum that contains [this](https://github.com/htop-dev/htop/blob/d23627fda9878f0a8640c24d95145d56882ba503/Process.h#L206).

Exactly. Basically replace `char state` by `ProcessState state` and all code managing this field.

> A variable of this enum should then be updated? I assume that the variable `this->state` used [here in #769](https://github.com/htop-dev/htop/pull/769#discussion_r701506570) is updated somewhere, right?

The necessary code updating this field can usually be found in the platform-specific `ProcessList` implementation.

**Comment by marcluque** [comment]
Thank you very much for the indication/explanation. I will look into it.

**Comment by marcluque** [comment]
Hi @BenBE,
I'm basically good to go, but I'm missing some information to rename a few process states. Especially [this](https://github.com/htop-dev/htop/blob/f75a8bc3a1131151181d6794000b10063400221e/dragonflybsd/DragonFlyBSDProcessList.c#L576) and [this](https://github.com/htop-dev/htop/blob/f75a8bc3a1131151181d6794000b10063400221e/dragonflybsd/DragonFlyBSDProcessList.c#L567) state confuse me and I somehow can't really find documentation (neither here, nor in the dragonfly doc) on how these letters are supposed to be understood. Maybe you can give me some advice on how I could figure this out or even propose some descriptive names for those letters.

Similarly, when I was working with pcp I couldn't figure out what the map for the process states looks like (see [this](https://github.com/htop-dev/htop/blob/f75a8bc3a1131151181d6794000b10063400221e/pcp/PCPProcessList.c#L148) line of code).

I also didn't consider any of the macros `PROCESS_N_STATE` [here for example](https://github.com/htop-dev/htop/blob/f75a8bc3a1131151181d6794000b10063400221e/CRT.c#L149) that I think are used for working with colors when printing. I'm not sure if there's something I should do with that.

**Comment by BenBE** [comment]
> Hi @BenBE, I'm basically good to go, but I'm missing some information to rename a few process states. Especially [this](https://github.com/htop-dev/htop/blob/f75a8bc3a1131151181d6794000b10063400221e/dragonflybsd/DragonFlyBSDProcessList.c#L576) and [this](https://github.com/htop-dev/htop/blob/f75a8bc3a1131151181d6794000b10063400221e/dragonflybsd/DragonFlyBSDProcessList.c#L567) state confuse me and I somehow can't really find documentation (neither here, nor in the dragonfly doc) on how these letters are supposed to be understood.

For `'A'` I'm unsure myself, as I'm not too familiar with the overall *BSD stuff. Looking around, `'A'` seems to be a fall-through case for an invalid kernel state (cf. [here](https://github.com/DragonFlyBSD/DragonFlyBSD/blob/c163a4d7ee9c6857ee4e04a3a2cbb50c3de29da1/sys/sys/proc_common.h)).

For `'Q'` I guess this can be understood as "queued for running" vs `'R'` for "actually running right now".

Just a guess based on my experience with various other systems.

> Maybe you can give me some advice on how I could figure this out or even propose some descriptive names for those letters.

You may find looking through the [DragonFlyBSD source](https://github.com/DragonFlyBSD/DragonFlyBSD/) helpful.

> Similarly, when I was working with pcp I couldn't figure out what the map for the process states looks like (see [this](https://github.com/htop-dev/htop/blob/f75a8bc3a1131151181d6794000b10063400221e/pcp/PCPProcessList.c#L148) line of code).

I'll hand off this question to @natoscott and @smalinux who work on that part of the codebase more intensely …

> I also didn't consider any of the macros `PROCESS_N_STATE` [here for example](https://github.com/htop-dev/htop/blob/f75a8bc3a1131151181d6794000b10063400221e/CRT.c#L149) that I think are used for working with colors when printing. I'm not sure if there's something I should do with that.

`PROCESS_RUN_STATE` and `PROCESS_D_STATE` don't need to be change themselves, but the code where they appear should be updated to reference to right process states for the highlighting to still work as expected (so a running process gets marked in `PROCESS_RUN_STATE` as the color). `PROCESS_D_STATE` is the same for defunct processes (AKA those blocked by kernel or zombies).

**Comment by natoscott** [comment]
> > [...]
> > Similarly, when I was working with pcp I couldn't figure out what the map for the process states looks like (see [this](https://github.com/htop-dev/htop/blob/f75a8bc3a1131151181d6794000b10063400221e/pcp/PCPProcessList.c#L148) line of code).
> 
> I'll hand off this question to @natoscott and @smalinux who work on that part of the codebase more intensely …

The states we observe from PCP reflect the states of the underlying platform.  IOW, there are no new process states for PCP, just all the existing ones and these state values will be the same you would see from each of the existing htop platforms.  That particular line of PCPProcessList.c line of code takes a single-character string (e.g. "S", "R", "I", etc - all exactly as supplied by the kernel) and stores it into process->state for htop to display.  The '?' fallback state there is used to handle the situation of "no value available" (which would result from an obscure error during sampling, like a failure to allocate memory or some such thing).

**Comment by marcluque** [comment]
Hi @natoscott, thank you for the insight, that makes it quite clear how PCP is intended to work.

Right now I'm trying to allow for some platform-independent process states. The reason being that I don't want to make a huge enum with all possible platform-specific process states. Instead I have an enum that contains a define that is defined based on the platform. I introduced a function/mapping between process state letters (like you mentioned them) and enum values for the supported OSes. However, that is platform specific. I'm wondering how I could achieve such a mapping for PCP such that all states from the underlying OSes would still work correctly (e.g., dispatching the platform-specific function/mapping in PCP). Maybe I'm overthinking here, I'd be glad if somebody could have a look [what my changes](https://github.com/marcluque/htop/commit/94ae70ee03fd3fe0fdb4dd1cbf5f237873bb2393) look like at the moment and what would be the best way to proceed with the PCP process state representation.

**Comment by natoscott** [comment]
> Right now I'm trying to allow for some platform-independent process states. The reason being that I don't want to make a huge enum with all possible platform-specific process states.

It's not going to be huge FWIW - there is a small, fixed set of states across all platforms.  You may be over-thinking this.

> Instead I have an enum that contains a define that is defined based on the platform. I introduced a function/mapping between process state letters (like you mentioned them) and enum values for the supported OSes. However, that is platform specific. I'm wondering how I could achieve such a mapping for PCP such that all states from the underlying OSes would still work correctly (e.g., dispatching the platform-specific function/mapping in PCP). Maybe I'm overthinking here, I'd be glad if somebody could have a look [what my changes](https://github.com/marcluque/htop/commit/94ae70ee03fd3fe0fdb4dd1cbf5f237873bb2393) look like at the moment and what would be the best way to proceed with the PCP process state representation.

There's two ways I guess - we could take platform-specific action based on the value of the PCP metric kernel.uname.sysname (which has value "Linux" on linux, etc).  Then we'd have to have separate handlers for each supported platform within the PCP code, which is quite inconvenient given the current htop implementation.

I think that's overkill though - let's keep it simple - I recommend you simply go with an enum that handles those states that the htop LinuxProcess.c code groks to start with.  If there are states that have different semantics on different platforms but the same state character (this is not the case AFAICS) we could pass in the platform to differentiate those on a case-by-case basis in the future when that situation arises.
