### ISSUE TITLE
3.1.0 fails to build: No rule to make target `.deps/htop.Po`

### ISSUE THREAD

**Issue by Roguelazer** [htop-dev/htop#803]
Version 3.1.0 fails to build with the following output:

```
+ /usr/bin/make -j4
Makefile:1196: .deps/htop.Po: No such file or directory
make: *** No rule to make target `.deps/htop.Po'.  Stop.
error: Bad exit status from /var/tmp/rpm-tmp.KcAnPo (%build)
```

This is from just downloading the release tarball, running `./autogen.sh`, running `./configure` and running `make`.

I notice that the file `.deps/$(myhtopplatprogram).Po` does exist, and running `mv .deps/$(myhtopplatprogram).Po .deps/htop.Po` after `./configure` fixes the error, so maybe there's some issue where a variable isn't being interpolated correctly?

**Comment by natoscott** [comment]
This seems to be a bug in automake.  I've reproduced it on a machine with version 1.15.1 (this machine last updated ~3years ago) - it's fixed with more modern versions.

I'll see if I can tweak our Makefile.am contents in such a way that it works on these older versions too.
