### ISSUE TITLE
Release tarball for 3.1.0

### ISSUE THREAD

**Issue by rubyFeedback** [htop-dev/htop#811]
I just downloaded the .tar.gz file.

URL was:

https://github.com/htop-dev/htop/archive/refs/tags/3.1.0.tar.gz

However had I can not compile it:

"./configure"

Leads to:

    configure: error: cannot find required auxiliary files: config.guess config.sub

This has been different for past releases. Has something changed? Perhaps if GNU configure makes
problems we could switch to meson or cmake in the long run. The older tarball releases compiled fine
for me by the way (after I get ncurses to work).

**Comment by BenBE** [comment]
Please note the instructions about building from source:
https://github.com/htop-dev/htop#compile-from-source

In particular you need to run `./autogen.sh` before `./configure`.

Which version of `autotools`/`autoconf`/`automake` are you using?
