### ISSUE TITLE
Possible bug? The memory bar isn't displaying the amount of used memory correctly, compared to "free -m".

### ISSUE THREAD

**Issue by fabianofurtado** [htop-dev/htop#812]
Hi... I'm using Arch Linux with HTOP version 3.1.0. The memory bar isn't displaying the amount of used memory correctly, compared to "free -m".

HTOP 3.1.0: 452 Mega
free -m: 153 Mega
                 total        used        free      shared  buff/cache   available
   Mem:           15709         153       15305          18         250       15258

Is this a possible bug? What am I doing wrong?

HTOP version 3.0.5 displays the amount of used memory correctly.

Thanks in advance.

**Comment by fasterit** [comment]
Could you please provide a combined screenshot of `free -h` and `htop` 3.1.0 similar to the one in https://github.com/htop-dev/htop/pull/452 ? (this PR may be related but there have been other changes on the memory meters, too between 3.0.5 and 3.1.0).

**Comment by fabianofurtado** [comment]
Yes...
![screenshot](https://user-images.githubusercontent.com/1511744/134587198-fa0b420c-4ba1-4c79-ba13-fe4668fb2c3a.jpg)

**Comment by fabianofurtado** [comment]
Sorry... I've uploaded the wrong image.

**Comment by fabianofurtado** [comment]
Now it makes sense! Thank you and sorry to bother you. My bad!
![screenshot2](https://user-images.githubusercontent.com/1511744/134588391-a7ea47f2-f27e-48f4-bbc4-76d06ece16dd.jpg)
