### ISSUE TITLE
Does anyone know how to scroll down the whole terminal screen for a server like 128 cores?

### ISSUE THREAD

**Issue by BenjaminChoou** [htop-dev/htop#818]
![image](https://user-images.githubusercontent.com/19500127/134839295-282a21e8-5949-4790-9d63-3cc4412db28a.png)

As you can see in the above screenshot, the CPU usage part basically takes the whole screen with no space for the proccess part. Is there any method to scroll down this screen or show 8 CPUs per line? This case can be worse if there are 256 cores, which is usually the case for a high-performance cluster.

**Comment by BenBE** [comment]
Which version of htop are you using? Judging by the screenshot that's a really old version and thus several of the improvements in recent releases to improve the header for systems with that many cores are missing.

Please recheck with the latest (3.1.x) release and possibly reset your configuration by removing `.config/htop/htoprc` to re-initialize the header area automagically.

**Comment by BenjaminChoou** [comment]
> Which version of htop are you using? Judging by the screenshot that's a really old version and thus several of the improvements in recent releases to improve the header for systems with that many cores are missing.
> 
> Please recheck with the latest (3.1.x) release and possibly reset your configuration by removing `.config/htop/htoprc` to re-initialize the header area automagically.

htop 2.2.0 - (C) 2004-2019 Hisham Muhammad
Released under the GNU GPL.

**Comment by BenjaminChoou** [comment]
> Which version of htop are you using? Judging by the screenshot that's a really old version and thus several of the improvements in recent releases to improve the header for systems with that many cores are missing.
> 
> Please recheck with the latest (3.1.x) release and possibly reset your configuration by removing `.config/htop/htoprc` to re-initialize the header area automagically.

Thanks. I fixed it after updating it to 3.1.0.
