### ISSUE TITLE
[BUG] Cannot scroll up with mouse (3.1.0)

### ISSUE THREAD

**Issue by jnooree** [htop-dev/htop#826]
Cannot scroll **up** with mouse (can scroll down) after updating to htop 3.1.0.
Compiled with `ncurses 6.2` on x86_64-linux (both Ubuntu 20.04 and 16.04 had this bug).

**Comment by BenBE** [comment]
Fixed in #807.

**Comment by jnooree** [comment]
Oops, thank you for information!
