### ISSUE TITLE
comm is not highlighted in other users' processes

### ISSUE THREAD

**Issue by m42a** [htop-dev/htop#839]
When I enable the "Try to find comm in cmdline" option, it is successfully found in processes owned by me, but not processes owned by other users.  For example, if I have a python script run by me the script name is successfully highlighted in the command line, but if the script is run by another user it is displayed separately and not highlighted in the command line:
![sleep-highlight](https://user-images.githubusercontent.com/1335659/136816530-786b681a-5dc9-4965-9131-e0c6534ed5d5.png)

**Comment by BenBE** [comment]
In order for `htop` to read the COMM value it needs to have access to this value.

Also the merged command view is a bit more subtle here: If COMM and EXE basename are equal, the COMM value is not highlighted separately.

Can you activate and post a screenshot with the additional COMM and EXE columns for the situation of the screenshot above?

The third process is marked this way, as EXE cannot be read and COMM and CMDLINE basename differ.

The display order is always EXE|COMM|CMDLINE with the first two fields optionally merged into the CMDLINE field when possible.

**Comment by gnarendran** [comment]
@m42a: quoting the man page:

> EXE  The  abbreviated  basename  of the executable of the process, obtained from /proc/[pid]/exe, if readable. htop is able to read this file on linux for ALL the processes only if it has the capability CAP_SYS_PTRACE or root privileges.

So if one has root privilleges one can workaround either by running htop as root (with all the associated risks), or give htop the required capability permanently (till reinstallation) as follows:
`sudo setcap cap_sys_ptrace=ep /usr/bin/htop`
