### ISSUE TITLE
Fix ncurses detection

### ISSUE THREAD

**Issue by The-King-of-Toasters** [htop-dev/htop#85]
Currently the autoconf script has to go through [extra hoops](https://github.com/htop-dev/htop/blob/master/configure.ac#L155) to figure out where curses is and how to include it. This leads to a pile of ifdef soup in the code and is making me pull my hair out in #80 trying to figure out how to do this on all supported systems. So I suggest we just `#include <curses.h>` by default. Of all the systems I tried, `curses.h` is either a link/include to some ncurses header or is it's own implementation that provides wide-char support. If downstream *really* needs to link against their special snowflake curses library, then they should insert the proper `(C|CPP|LD)FLAGS` themselves. In other words, assume a sane default and make it a compile-time error so it blows up in their faces.

**Comment by fasterit** [comment]
Why would we need to change what works to build with meson that ... is not needed anywhere?
Wondering....

**Comment by The-King-of-Toasters** [comment]
Because I think it sacrifices simplicity in favour of ultimate portability, and even then it seems way too overcomplicated. I did a quick search and it seems that this a solved problem in [autoconf-archive](https://github.com/autoconf-archive/autoconf-archive/blob/master/m4/ax_with_curses.m4), with the benefit of it being easier to integrate.

**Comment by fasterit** [comment]
This is GPLv3+ so won't work for htop (GPLv2).

**Comment by The-King-of-Toasters** [comment]
Scripts in the archive don't influence the licensing of configure script/program. Doesn't matter though, as I tested it and solaris wouldn't build 🤦.

**Comment by cgzones** [comment]
Maybe related: #412

**Comment by cgzones** [comment]
I think there is currently nothing to fix here.
