### ISSUE TITLE
Migrating codebase to C++

### ISSUE THREAD

**Issue by onlined** [htop-dev/htop#855]
Hi all,
I am currently working on #854, it is my first (hopefully not last) PR to this repo. While I was working on it, I realized that there is some convention for namespacing and there is a class hierarchy starting with `Object` struct. To me, it seems like C++ remove most of the boilerplate here. And probably it will remove the need for most of the utility functions in `XUtils.c`.

So, I have some questions to maintainers:

- Was this subject (migrating some part or all of the codebase to C++) discussed before? If yes, what was the conclusion?
- Would you be OK with going to C++? Of course it wouldn't be completed in one single PR, but small by small it can be handled.
- Are there any blockers for C++, other than maintainers' personal preferences (I don't imply they don't prefer C++)?

**Comment by fasterit** [comment]
Thanks to everybody taking part in this! Closing until the next iteration of "favourite-language-of-the-week" comes up.
/DLange
