### ISSUE TITLE
[feature request] the -n <int> option of top

### ISSUE THREAD

**Issue by UnixJunkie** [htop-dev/htop#859]
Hello,
top can be used in batch mode with the -n option:
you specify how many screen refreshes you wan before top exits.
And at the end, you see the last screen top was displaying.
Such behavior would be cool for htop too.
For example, I want to see the htop screen just once (and it should not disappear
once htop has quit).
Regards,
F.

**Comment by vasvolodimir** [comment]
Hello @BenBE,
I'd like to work on it if you don't mind =)

**Comment by BenBE** [comment]
Sure, have a look at the linked issue when working on this so the ideas from there can be included in this new feature.

**Comment by UnixJunkie** [comment]
thanks a lot @vasvolodimir

**Comment by UnixJunkie** [comment]
Thanks a lot for having implemented it!
