### ISSUE TITLE
Pressing Fn+S+F3 causes desktop environment to take a screenshot

### ISSUE THREAD

**Issue by broes5** [htop-dev/htop#866]
I own a Lenovo laptop. Because it's a laptop `Fn` must be pressed to use the function keys. Because it's a Lenovo laptop, pressing `Fn+S` is the same as pressing `Print`, which is the key used to trigger a screenshot.

Whenever I use Htop's search feature, pressing `Fn+S+F3` to go to the previous process or thread causes the desktop environment to take a screenshot.

**Comment by fasterit** [comment]
You can typically set whether the function keys are F1-F12 or some "multi-media keys" in the BIOS.

You can put the screenshot hotkey onto a different key combination in your desktop environment.

This is not an htop issue but one of your reduced keyboard.
