### ISSUE TITLE
How to make the meters smaller

### ISSUE THREAD

**Issue by XsongyangX** [htop-dev/htop#870]
![image](https://user-images.githubusercontent.com/10444460/141342995-8b2ef204-894f-4de4-aef6-c4ca9c6e3d15.png)

**Comment by XsongyangX** [comment]
version 3.0.5

**Comment by BenBE** [comment]
Have a look at the setup screen (<kbd>F2</kbd>), navigate to the Meters page there and exchange those large meters for smaller ones or others that better suite your taste.

**Comment by XsongyangX** [comment]
After cycling through with space, it separated the meters in 4 columns. Not sure why or how, but it worked.
