### ISSUE TITLE
release tarballs without autoconf deps

### ISSUE THREAD

**Issue by rofl0r** [htop-dev/htop#876]
it'd be great if you guys could upload release tarballs including pre-generated configure scripts as in 2.x time, so one doesn't have to install the full autoconf suite to build. (it's perfectly fine to depend on it for build-from-git, not so much for releases).

**Comment by BenBE** [comment]
Cf. #811, #63, #31 …

**Comment by rofl0r** [comment]
any rationale for wontfix ? not having to mess with autoconf makes life a whole lot easier.

**Comment by BenBE** [comment]
Yes, two reasons:

1. The tarballs are auto-generated from the release tags. Including the generated scripts thus would either force them to be included in the repository (where they don't belong) or messing around with the github release actions (which is a beast on its own) and require signing of those tarball to allow proper attribution for those non-versioned files.

2. For all currently supported build platforms there's packaged versions of `autoconf` easily available from the distribution, thus running that additional `./autogen.sh` before doing the usual `./configure` and `make` add's no real challenge to the build: Actually you'll have to install several build dependencies regardless, thus `autoconf` can just be considered another one of those.

Furthermore asking people to generate the `configure` script themselves serves to minimize the attack surface for supply chain attacks as it minimizes the amount of code we provide to the minimum that we have to ship (and all of which is properly tracked in git anyway). Reviewing the `configure.ac` and `Makefile.am` is much more intuitive than checking megabytes of auto-generated code.

Also when you are seriously working with the code you need to regenerate the `configure` script anyways and thus would require `autoconf` anyway …

**Comment by rofl0r** [comment]
thanks for your reply.

> The tarballs are auto-generated from the release tags.

yes, herein lies the issue. i've written an elaborate article on why that's not a good idea: https://github.com/sabotage-linux/sabotage/wiki/Why-github-downloads-suck

> messing around with the github release actions

would you accept a PR implementing this for you ?

> require signing

i don't think that's necessary. for my distro, we use sha512 sums to verify an archive hasn't been tampered with, and i suspect most of the other people that opened an issue in this regard won't require one either.
