### ISSUE TITLE
Battery status no longer available (htop 3.1.2 regression)

### ISSUE THREAD

**Issue by jpalus** [htop-dev/htop#881]
After upgrading htop to 3.1.2 battery status on Pinebook Pro is no longer displayed. It seems to be caused by commit 3e70de6 and more specifically:
https://github.com/htop-dev/htop/blob/43e9be5a8f63b6be614f7a73500ad4e755f38c83/linux/Platform.c#L708-L719
Which my `/sys/class/power_supply/cw2015-battery` strongly disagrees with. Previous condition based on `/sys/class/power_supply/*/type` was much more robust:
https://github.com/htop-dev/htop/blob/04871a2d04361517f2e539810cb11e9e9898f0d0/linux/Platform.c#L757-L779

**Comment by cgzones** [comment]
> https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power

```
What:		/sys/class/power_supply/<supply_name>/type
Date:		May 2010
Contact:	linux-pm@vger.kernel.org
Description:
		Describes the main type of the supply.

		Access: Read
		Valid values: "Battery", "UPS", "Mains", "USB", "Wireless"
```

**Comment by pega2k** [comment]
Hi! the same here my battery system is in /sys/class/power_supply/CMB1.
