### ISSUE TITLE
The interface has problem when there are too many CPUs

### ISSUE THREAD

**Issue by wfly1998** [htop-dev/htop#888]
<img width="1920" alt="截屏2021-12-08 14 46 27" src="https://user-images.githubusercontent.com/37299119/145161883-59056c8a-3954-47b6-b8c2-cbeed31bbeef.png">

As the screenshot shows, when there are too many CPUs, the usage of CPUs will occupy the whole screen.

**Comment by BenBE** [comment]
Which version of htop are you using? Which OS/Distro?

**Comment by fasterit** [comment]
Debian 9 (Stretch) is out of support since 06.07.2020

**Comment by wfly1998** [comment]
> Debian 9 (Stretch) is out of support since 06.07.2020. htop was 2.0.2 on that distro. If you run LTS, you could ask that team to backport a more recent htop. Or, probably better, just upgrade yourself.

Got it, thanks.
