### ISSUE TITLE
libcurses issue

### ISSUE THREAD

**Issue by ardhill** [htop-dev/htop#90]
Error 
`configure: error: You may want to use --disable-unicode or install libncursesw.`

I have some ncurses libraries already installed:

[![libcurses.png](https://i.postimg.cc/Kz8Sbfrg/libcurses.png)](https://postimg.cc/XZmDcwPV)

I already have ncdu - a ncurses based du viewer on my system, so it seems strange that I am getting this error.

Ubuntu based, Linux Mint 19.3

**Comment by ardhill** [comment]
The GitHub entry I found for ncurses is a bit of a nightmare to understand for those of us, not too deeply into programming:

https://github.com/mirror/ncurses/blob/master/INSTALL

If installing ncurses will fix the issues people are having, maybe you could help give some clear guidance on installing ncurses that way it is needed for your package.

Thanks

**Comment by vielmetti** [comment]
Try installing `libncurses5-dev` and see how that turns out.

This is related to #89 .

**Comment by ardhill** [comment]
@vielmetti (libncursesw5-dev) That worked thank you.
