### ISSUE TITLE
htop -u without an argument has stopped working in 3.0.1

### ISSUE THREAD

**Issue by lyu** [htop-dev/htop#91]
I liked this when it was introduced in 3.0.0, but it is gone in 3.0.1. The change log for 3.0.1 didn't mention anything, is this expected?

Thank you!

**Comment by natoscott** [comment]
@lyu - thanks for the report.  This is a regression introduced by commit db5adbeae09b8b80587294e4de125af109b8ecdc - I'll get a fix in shortly.

**Comment by eworm-de** [comment]
Ups... Sorry!
