### ISSUE TITLE
Feature Request: CLI option to tag all processes matching a string

### ISSUE THREAD

**Issue by OddBloke** [htop-dev/htop#911]
I have a set of similarly-named processes that I want to monitor in comparison to the rest of my system using htop. At the moment, I launch `htop` and then go through to manually tag each of them: when new processes start, I have to find them and tag them individually. This is error-prone and time consuming.

I would like to be able to do something like `htop --tag-matching substring-of-process-name` and have `htop` automatically tag any processes (including new ones) including that substring.

**Comment by OddBloke** [comment]
(I have a patch for this locally, which I'll PR up if there's appetite for this feature from the core team. Thanks for everything you do to maintain htop!)

**Comment by BenBE** [comment]
There is an existing feature in `htop` itself: By pressing <kbd>\</kbd> and entering the substring to search for the view is filtered to only contain processes matching this filter.

**Comment by OddBloke** [comment]
> There is an existing feature in `htop` itself: By pressing </kbd> and entering the substring to search for the view is filtered to only contain processes matching this filter.

Thanks for the reply Ben! Filtering does do something slightly different to what I'm looking for: I want to see the processes _alongside_ the other processes on my system, so I can examine how they're behaving together.

**Comment by fasterit** [comment]
I think the Filter function (`htop -F "htop|bash|firefox") is sufficient. I do not think tagging things visually makes much sense as a busy system will have so many processes you need to scroll anyways. And we have following a single process already implemented, too.

So thank you for the proposal but not likely interesting to upstream your patch.

/DLange

**Comment by OddBloke** [comment]
> I do not think tagging things visually makes much sense as a busy system will have so many processes you need to scroll anyways.

This does beg the question of why tagging things visually is supported in `htop` _at all_ if it isn't useful: all I'm proposing is a way of automating the application of the existing visual tagging.

However: I understand, this is a niche use case. Thanks!

**Comment by OddBloke** [comment]
Aha, right! I don't think I've ever issued a signal from `htop` (vs just monitoring processes) so I didn't think of that: thank you!
