### ISSUE TITLE
update the apt package

### ISSUE THREAD

**Issue by weather-tracker** [htop-dev/htop#925]
the apt package is running 2.2.0-2build1
while the snap version is on 3.1.2

**Comment by BenBE** [comment]
While part of the team coincides with the set of package maintainers doing the packaging at some distributions, we're not responsible for the versions packaged in the distributions.

Thus depending on your distribution you might have more luck contacting the packaging people/team directly asking for a newer release to be packaged.

Last remains to say, that apt itself has no package format in and of itself, but is mostly a frontend for interacting with repositories containing files in the .DEB AKA Debian Packaging Format as understood by dpkg. And as mostly all distributions based on Debian and Ubuntu use dpkg to manage the installed software and files on your system, there's a lot of room for distributions that will not have updated their repository to contain one of the newer versions of htop that happened to be released after the further development has been taken over by the community.

For a list of different distributions packaging newer versions of htop or whom to contact for your distribution, please have a look at [this list](https://repology.org/project/htop/versions).

**Comment by weather-tracker** [comment]
thanks
