### ISSUE TITLE
Ubuntu VM, x86_64-linux-gnu, htop aborted, bug report

### ISSUE THREAD

**Issue by mister-fritz** [htop-dev/htop#932]
[[ubuntu shell VM]]:~$ htop

htop 2.2.0 aborting. Please report bug at http://hisham.hm/htop

 Please include in your report the following backtrace: 
htop(CRT_handleSIGSEGV+0x37)[0x55fc26188287]
/lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f3fbf142210]
htop(+0xce06)[0x55fc26174e06]
htop(ScreenManager_run+0x28f)[0x55fc2617dd0f]
htop(+0x1aefd)[0x55fc26182efd]
htop(+0xecba)[0x55fc26176cba]
htop(ScreenManager_run+0x28f)[0x55fc2617dd0f]
htop(main+0x40e)[0x55fc2617446e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f3fbf1230b3]
htop(_start+0x2e)[0x55fc2617468e]

**Comment by BenBE** [comment]
Please check if this error persists with a more recent release of htop.
