### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by eseiler** [htop-dev/htop#935]
Occasionally, `htop` crashes when starting.
This happens (also) on current master (3e1a27a98110d31c42397562490150247dd7dc6a), and only when I/O (read, write, or total) rate for processes are shown.

**Stack**:

```
libc.so.6!__pthread_kill_implementation(int no_tid, int signo, pthread_t threadid) (pthread_kill.c:44)
libc.so.6!__pthread_kill_internal(int signo, pthread_t threadid) (pthread_kill.c:80)
libc.so.6!__GI___pthread_kill(pthread_t threadid, int signo) (pthread_kill.c:91)
libc.so.6!__GI_raise(int sig) (raise.c:26)
CRT_handleSIGSEGV(int signal) (\run\shm\htop\CRT.c:1206)
libc.so.6!<signal handler called> (Unknown Source:0)
LinuxProcessList_readIoFile(LinuxProcess * process, openat_arg_t procFd, unsigned long long realtimeMs) (\run\shm\htop\linux\LinuxProcessList.c:505)
LinuxProcessList_recurseProcTree(LinuxProcessList * this, openat_arg_t parentFd, const char * dirname, const Process * parent, double period) (\run\shm\htop\linux\LinuxProcessList.c:1468)
ProcessList_goThroughEntries(ProcessList * super, _Bool pauseProcessUpdate) (\run\shm\htop\linux\LinuxProcessList.c:2170)
ProcessList_scan(ProcessList * this, _Bool pauseProcessUpdate) (\run\shm\htop\ProcessList.c:635)
checkRecalculation(ScreenManager * this, double * oldTime, int * sortTimeout, _Bool * redraw, _Bool * rescan, _Bool * timedOut, _Bool * force_redraw) (\run\shm\htop\ScreenManager.c:125)
ScreenManager_run(ScreenManager * this, Panel ** lastFocus, int * lastKey, const char * name) (\run\shm\htop\ScreenManager.c:226)
CommandLine_run(const char * name, int argc, char ** argv) (\run\shm\htop\CommandLine.c:376)
main(int argc, char ** argv) (\run\shm\htop\htop.c:15)
```

**Debugger points to**:

https://github.com/htop-dev/htop/blob/3e1a27a98110d31c42397562490150247dd7dc6a/linux/LinuxProcessList.c#L505

```
realtimeMs = 1643902542196
process->io_last_scan_time_ms = 1643902542196
```

My local fix is to just add 1 to the denominator :)

Both here
https://github.com/htop-dev/htop/blob/3e1a27a98110d31c42397562490150247dd7dc6a/linux/LinuxProcessList.c#L505
and here
https://github.com/htop-dev/htop/blob/3e1a27a98110d31c42397562490150247dd7dc6a/linux/LinuxProcessList.c#L513

---

```
$ uname -a
Linux 5.10.81.1-microsoft-standard-WSL2+ #3 SMP Wed Feb 2 14:27:55 CET 2022 x86_64 x86_64 x86_64 GNU/Linux
$ ldd --version
ldd (Ubuntu GLIBC 2.34-0ubuntu3) 2.34
```

The OS is Ubuntu 21.10. I never had the problem with Ubuntu 20.10, which uses glibc 2.31.

**Comment by BenBE** [comment]
Thank you very much for reporting this issue.

Looking into this issue I slightly disagree with your workaround, as it only works around one issue, while introducing an unnecessary inaccuracy.

Instead the proper fix is assigning `NAN` to `process->io_rate_read_bps` and `process->io_rate_write_bps` in the case that `realtimeMs == process->io_last_scan_time_ms` and thus avoiding the division by zero which is the root cause of the reported problem.

**Comment by Wenbyn** [comment]
I installed htop on almalinux 9 and when I type htop I get an error:  **Floating point exception (core dumped)**

![Image](https://github.com/user-attachments/assets/4c1096ca-af04-49de-9f74-61dbcb1baedc)

Almalinux 9 fresh instaled !!!

**Comment by BenBE** [comment]
@Wenbyn Can you run htop under gdb and provide the output of `bt full`, alongside the objdump of the htop binary? Which htop version (`htop -V` or package manager) is this? Does this happen with htop compiled from the main branch too?
