### ISSUE TITLE
Configurations resetting to default frequently

### ISSUE THREAD

**Issue by sfmth** [htop-dev/htop#948]
Hello there dear developers

Htop loses all of my custom configurations quite frequently.

I guess it is because of me using ctrl+c or just closing the terminal to stop htop but I can't change that, I'm too used to it.

My version of htop is 3.1.2, on arch linux 5.16.1

I saw that in version 3.1.1 there were some changes to how the configurations are saved on exit and how they are resetted to default in case of a crash.

Please reconsider this method as I as a user am bothered with it.

**Comment by BenBE** [comment]
The changes that were included in the last release mainly addressed issues with certain configurations that would cause `htop` to reset the configuration in some undesired situations where such a reset was not intended to occur. Also note that `htop` only ever rewrites the configuration on exit [when it was changed during the session](https://github.com/htop-dev/htop/blob/6133cac721f355aec0d6b5581fef90db34305f29/CommandLine.c#L382-L386). When `SIGINC` AKA <kbd>ctrl</kbd>+<kbd>c</kbd> is pressed the [function `CRT_handleSIGTERM` is called](https://github.com/htop-dev/htop/blob/6133cac721f355aec0d6b5581fef90db34305f29/CRT.c#L765-L769), which directly terminates the process and thereby bypassing the code path where the modified configuration is actually written. Thus if you do change your configuration and expect those changes to last it's mandatory to close `htop` properly by pressing <kbd>q</kbd> or <kbd>F10</kbd> (or <kbd>alt</kbd>+<kbd>0</kbd> on some GUI terminals).

To further investigate your issue it's necessary to see the actual configuration that is involved when such resets happen.

**Comment by sfmth** [comment]
[htoprc.csv](https://github.com/htop-dev/htop/files/8103517/htoprc.csv)

Hi thanks for the kind explanation, Here is my configuration.

I also had an instance where I saved my configurations properly but after a while they were all gone, I couldn't reproduce it though.

**Comment by BenBE** [comment]
Another thing to be aware of is mixing of `htop` versions: The configuration is not downgradable, thus when running a newer version from e.g. git and later on an older version by the distribution, the older version will reset your configuration as from its point of view that configuration it read contained features it might not have understood.

**Comment by sfmth** [comment]
Alright I will take these into consideration, and If I had issues I would report it but so far it's been alright
