### ISSUE TITLE
Allow single precision for CPU% greater than 99.9

### ISSUE THREAD

**Issue by etanot** [htop-dev/htop#957]
**Type:** Feature request

Since we're dynamically adjusting column width of `CPU%`, we can also show single precision value if `CPU%` greater than `99%`. 
Having single precision for values greater than `99%` makes `CPU%` column consistent for all values. In past, some users have asked for this, see https://github.com/hishamhm/htop/issues/231.

### Potential solution
In my opinion, it would be a good idea to increase the minimum column width of `CPU%` from `4` to `5` characters, unless there is a very good reason not to do so. Since probability of running a process which requires more than `999.9` percent of CPU is very lower than running a process which requires CPU between `99.9` and `999.9`, so width `5` would be a good choice as it would decrease the frequency of screen refresh/redraw.

**Comment by BenBE** [comment]
Actually given a recent change that allowed this dynamic resize of the `CPU%` and `NCPU%` columns, the mentioned change actually isn't too big to implement; mostly boiling down to adjust the limits at which the display format is changed.
