### ISSUE TITLE
Misaligned columns when number characters more than 5 in CPU% column

### ISSUE THREAD

**Issue by etanot** [htop-dev/htop#958]
**Type:** Bug report

## Description

I think alignment is broken when number characters are more than 5 in `CPU%` column. It is reproducible on main (469ae7a0bdd37204dc8c07286fcd942ce84e9755) branch.

### Steps to reproduce

I don't have enough CPU cores to test this. But to increase number of characters in `CPU%` column, I've increased the precision value and run a CPU intensive process. (I hope my testing method is right and not missing something else.)

  - Apply below patch.
```patch
diff --git i/Process.c w/Process.c
index 77e78f0..f7d25be 100644
--- i/Process.c
+++ w/Process.c
@@ -743,7 +743,7 @@ void Process_printPercentage(float val, char* buffer, int n, uint8_t width, int*
          *attr = CRT_colors[PROCESS_MEGABYTES];
          if (val < 100.0F)
             val = 100.0F; // Don't round down and display "val" as "99".
-         xSnprintf(buffer, n, "%*.0f ", width, val);
+         xSnprintf(buffer, n, "%*.2f ", width, val);
       }
    } else {
       *attr = CRT_colors[PROCESS_SHADOW];
```
  - Compile `htop`.
  - Run a CPU intensive process like `ffmpeg`.
  - Run htop and look for process which we're running.

### Expected output

Since we're [dynamically adjusting](https://github.com/htop-dev/htop/commit/edf319e53d1fb77546505e238d75160a3febe56e) `CPU%` column, all column should also be aligned, properly.

### Actual output

![misalingment](https://user-images.githubusercontent.com/28824347/158734635-75e4a915-bcc1-4321-9988-909331cdc259.png)

For greater precision value misalignment is greater.

**Comment by BenBE** [comment]
This artifact is probably caused by your testing method. The column width is adjusted/updated by `Process_updateCPUFieldWidths` in `Process.c`, which should handle large numbers.

The proper test case would be to seek out the location the CPU usage for each process is calculated and modify that value.

**Comment by etanot** [comment]
> The proper test case would be to seek out the location the CPU usage for each process is calculated and modify that value.

Thanks for the suggestion, dynamic scaling is working as expected. I've tested it by multiplying `percent_cpu` value with a random number and increase maximum limit of `percent_cpu` to some larger value.

```patch
diff --git i/linux/LinuxProcessList.c w/linux/LinuxProcessList.c
index b0e6f03..3fce3fd 100644
--- i/linux/LinuxProcessList.c
+++ w/linux/LinuxProcessList.c
@@ -1544,9 +1544,10 @@ static bool LinuxProcessList_recurseProcTree(LinuxProcessList* this, openat_arg_
          LinuxProcess_updateIOPriority(lp);
       }
 
+      srand(time(0));
       /* period might be 0 after system sleep */
-      float percent_cpu = (period < 1E-6) ? 0.0F : ((lp->utime + lp->stime - lasttimes) / period * 100.0);
-      proc->percent_cpu = CLAMP(percent_cpu, 0.0F, activeCPUs * 100.0F);
+      float percent_cpu = (period < 1E-6) ? 0.0F : (((lp->utime + lp->stime - lasttimes) * ((rand() + 1) / 100001) ) / period * 100.0);
+      proc->percent_cpu = CLAMP(percent_cpu, 0.0F, activeCPUs * 10000000.0F);
       proc->percent_mem = proc->m_resident / (double)(pl->totalMem) * 100.0;
       Process_updateCPUFieldWidths(proc->percent_cpu);
```

![large](https://user-images.githubusercontent.com/28824347/159846235-e5e709b7-00b0-4f2b-b131-2507ed4e56df.png)

<hr>

@BenBE, but title isn't dynamically adjusting itself with respect to values. Title column expands with respect to values, but it never shrinks even number of characters in maximum value is less than width of respective column title.

![title](https://user-images.githubusercontent.com/28824347/159861797-1d5a1fa4-4dcd-4fc4-9202-a09dd7b30ffd.gif)

In above GIF, we can see width of title column never shrinks, even in one instance maximum value reached to `1069`. Is this expected behavior?

**Comment by BenBE** [comment]
That the dynamically scaled columns is currently expected, but not written in stone.

It was somewhat deliberately skipped as shrinking requires some more thought to avoid flickering when the column resizes down just to resize up again next refresh cycle.
