### ISSUE TITLE
Feature Request: Condensed meters

### ISSUE THREAD

**Issue by foundObjects** [htop-dev/htop#96]
It would be nice to have a small number of combo meter options to reduce space used. I can think of two I'd really like off the top of my head: a memory + swap used meter in two smaller columns and a hostname + uptime label in two smaller columns. I'm sure others can chime in with more useful combinations.

Cheers!

**Comment by mneilly** [comment]
It might be useful to add an option to allow page up and page down to include the meters. Currently, it seems to only include the process list.

**Comment by cgzones** [comment]
A combined memory and swap meter was introduced with b965417b.
