### ISSUE TITLE
Not able to persist changes in Setup -> Meters

### ISSUE THREAD

**Issue by backbone-link** [htop-dev/htop#975]
Would like to have the option to have more rows (and hence more horizontal room per CPU core metric) on high core count CPUs so we can see all core info (CPU freq, % used, etc.) Currently it looks too small per core.
<img width="1546" alt="Screen Shot 2022-04-09 at 6 34 57 AM" src="https://user-images.githubusercontent.com/71556187/162572389-e2a0d542-6b7e-4f23-956e-d00528a17f94.png">

**Comment by BenBE** [comment]
In the setup screen (<kbd>F2</kbd>) there's a section to configure the `Meters`. There you need to choose the various CPU views you want to have. By default this depends on the number of cores already, to prefer a relatively flat header, by packing more columns for systems with many CPU cores. The entry `CPU (1/1)` shows all CPUs in one column, `CPU (1&2/2)` uses two columns and `CPU (1&2&3&4/4)` uses 4 columns. The entries `CPU (1/2)`+`CPU (2/2)` use one column each, but only show the first/second half of all CPUs. For the other entries accordingly.

**Comment by backbone-link** [comment]
Awesome that did the trick. Many thanks and sorry for the noise.

**Comment by backbone-link** [comment]
@BenBE Now I am not able to persist changes done in the `Meters`. Could you please advise?

**Comment by BenBE** [comment]
@backbone-link Usually one issue per problem. ;-)

Regarding that config issue: Please check `~/.config/htop/htoprc` is writable to the user running the process (should have permissions `0664` or `0644` and be owned by your user – owner and group). Same applies to `~/.config` (usually `0775`) and `~/.config/htop` (usually `0775`).

When terminating `htop` you should use <kbd>q</kbd> or <kbd>F10</kbd> (on most graphical terminals <kbd>alt</kbd>+<kbd>0</kbd>). **Do NOT use <kbd>ctrl</kbd>+<kbd>c</kbd>!**

Also check if there is an old configuration file `~/.htoprc` in your home directory: If present `htop` tries to migrate its settings over to `~/.config/htop/htoprc`. Remove the old file in the top of your home directory if necessary.

**Comment by backbone-link** [comment]
Thank you! Closing this.
