### ISSUE TITLE
Feature Request: add a Date meter

### ISSUE THREAD

**Issue by jvalrog** [htop-dev/htop#98]
There is already a Clock meter but not a Date meter. Should be trivial to implement and would be useful to some of us.

Regards.

**Comment by BenBE** [comment]
Maybe also a combined one? Cf. #96

**Comment by Nudin** [comment]
I would volunteer to implement this if it is accepted in general.

**Comment by BenBE** [comment]
Supported format should be ISO-8601.

**Comment by cgzones** [comment]
Applied via #159

**Comment by campones** [comment]
is  this available in ubuntu repository?   
is the date the real date, or the one that the server is using (it's pretty different)
