### ISSUE TITLE
Too many CPUs in LXC

### ISSUE THREAD

**Issue by odo2063** [htop-dev/htop#993]
htop 3.2.0 running in LXC shows all Cores available on Host, but statistics only for the available CPUs in the container.
![Bildschirmfoto von 2022-05-04 14-33-17@2x](https://user-images.githubusercontent.com/15078667/166685145-f2f6f7fa-2612-41c0-bcf2-76e847dd9105.png)
.

**Comment by odo2063** [comment]
V 3.0.5 is ok
V 3.1.2 has same problem

**Comment by fasterit** [comment]
That is because your `.htoprc` has that layout saved. Delete it or select better meters in the Setup menu (F2).

**Comment by odo2063** [comment]
nope, removed all configs and tried all meter settings. It stays in 2 lines. which is simply not enough...

**Comment by odo2063** [comment]
but this is maybe more related to the original problem.

I have bzip2 running which is single threaded but it shows 200% usage. (I applied your patch)
![Bildschirmfoto von 2022-05-07 08-37-24@2x](https://user-images.githubusercontent.com/15078667/167242225-a409b0d0-163e-466e-8ab5-b82394c803dd.png)

**Comment by fasterit** [comment]
The initial htoprc is generated to account for the `active` CPUs and these are again not properly managed by LXC.
Try with https://github.com/htop-dev/htop/pull/995/commits/33973f7e40b6b24e219f5c9d19b205f6f9ddeed4 applied.

**Comment by odo2063** [comment]
seems fine now. Thanks.

**Comment by fasterit** [comment]
Cool, thanks @odo2063 for reporting and testing. I'll merge this into main now.
